In [ ]:
import requests
import torch

import pandas as pd

from datasets import load_dataset

In [2]:
ds = load_dataset("KushT/bbc_news_multiclass_train_val_test")

val = ds['validation'].to_pandas()

val.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 379 entries, 0 to 378
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   text    379 non-null    object
 1   label   379 non-null    int64
dtypes: int64(1), object(1)
memory usage: 6.1+ KB

In [3]:
val['label'] = val['label'].apply(lambda x: 'business' if x == 0 else 'entertainment' if x == 1 else 'politics' if x == 2 else 'sport' if x == 3 else 'tech')

labels = val['label'].unique()

val

                                                  text          label
0    Why Cell will get the hard sell The world is c...           tech
1    Iranian MPs threaten mobile deal Turkey's bigg...       business
2    Google launches TV search service The net sear...           tech
3    Dutch bank to lay off 2,850 staff ABN Amro, th...       business
4    Franz Ferdinand's art school lesson Scottish r...  entertainment
..                                                 ...            ...
374  Karachi stocks hit historic high The Karachi S...       business
375  Dance music not dead says Fatboy DJ Norman Coo...  entertainment
376  Real in talks over Gravesen move Real Madrid a...          sport
377  Man Utd stroll to Cup win Wayne Rooney made a ...          sport
378  Election 'could be terror target' Terrorists m...       politics

[379 rows x 2 columns]

In [4]:
def generate_text(message, url):
    payload = {
        "model": "deepseek-r1:1.5b",
        "prompt": message,
        "stream": False,
        "options": {
            "temperature": 0.0,
            "num_predict": 5000,
        },
        "raw": True
    }

    response = requests.post(url, json=payload)

    return response.json()

In [5]:
def classify(text, labels):

    url = "http://localhost:11434/api/generate"

    message = f"""[INST]
        System: You are a classification assistant. Your objective is to read the provided text and classify it according to the task and labels described. You are capable of handling binary classification tasks based on user instructions.
        User: Classify the following text based on the task: Category classification of news articles. Only respond with the label that best describe the text. The possible labels are: {', '.join(labels)}. Text: {text}
        [/INST]
        """

    response = generate_text(message, url)

    done_reason = response['done_reason']
    num_tokens = response['eval_count']
    response = response['response'].strip().lower()


    if done_reason != 'length':
        content = response.split('</think>')[1]
    else:
        return "loop", num_tokens, response

    if 'business' in content:
        content = 'business'
    elif 'sport' in content:
        content = 'sport'
    elif 'entertainment' in content:
        content = 'entertainment'
    elif 'politics' in content:
        content = 'politics'
    elif 'tech' in content:
        content = 'tech'
    else:
        content = 'error'

    print(content, num_tokens)

    return content, num_tokens, response

In [ ]:
val['prediction'], val['num_tokens'], val['response'] = zip(*val['text'].apply(lambda x: classify(x, labels)))

business 435
business 532
entertainment 958
tech 18
tech 55
politics 562
business 740
sport 551
entertainment 247
tech 1411
entertainment 389
entertainment 472
sport 396
politics 688
entertainment 118
error 458
entertainment 1331
politics 535
sport 515
sport 754
business 640
politics 42
sport 262
business 617
entertainment 410
entertainment 570
entertainment 608
business 525
entertainment 562
politics 733
entertainment 353
business 842
tech 19
sport 413
politics 918
tech 21
tech 115
politics 64
tech 22
business 294
sport 95
tech 93
sport 957
politics 659
sport 332
business 477
entertainment 923
politics 30
sport 738
business 429
tech 23
politics 18
business 405
tech 323
entertainment 991
business 481
sport 511
business 483
business 996
entertainment 295
business 730
business 915
business 295
politics 601
business 671
politics 82
tech 57
entertainment 542
tech 2075
business 679
sport 297
politics 66
politics 351
tech 21
entertainment 438
sport 505
business 428
business 619
tech 889
tech 14
sport 85
sport 347
tech 575
sport 54
tech 18
business 407
entertainment 1161
sport 613
sport 465
tech 27
entertainment 999
error 276
sport 71
sport 202
sport 246
entertainment 430
business 701
politics 80
politics 90
tech 498
tech 20
tech 55
sport 392
tech 398
tech 24
politics 539
business 617
sport 364
politics 750
entertainment 367
tech 137
politics 735
entertainment 221
business 99
tech 73
politics 30
tech 533
politics 114
sport 365
tech 115
politics 106
business 783
politics 81
business 630
sport 803
business 96
business 93
business 626
tech 19
politics 1420
entertainment 523
entertainment 76
business 820
business 559
tech 74
entertainment 403
sport 629
business 438
politics 252
politics 344
entertainment 891
business 377
tech 20
business 314
entertainment 477
tech 379
business 412
tech 156
tech 388
business 727
sport 83
politics 111
sport 286
entertainment 1516
business 393
sport 74
entertainment 192
entertainment 183
entertainment 1441
business 494
politics 184
error 211
politics 85
business 577
sport 365
tech 20
sport 30
business 99
business 415
business 67
business 253
business 400
business 431
entertainment 435
politics 304
sport 554
tech 37
business 367
tech 383
business 1253
politics 774
sport 165
business 488
business 559
business 550
business 584
politics 358
entertainment 474
sport 483
business 450
business 1479
entertainment 66
business 486
entertainment 606
tech 99
sport 463
business 718
politics 73
business 699
politics 87
business 748
business 585
business 418
business 468
tech 20
tech 11
politics 388
entertainment 406
entertainment 557
entertainment 274
error 582
business 527
tech 21
tech 7
politics 95
politics 644
business 337
business 445
business 586
business 217
business 574
politics 446
business 398
business 381
tech 303
tech 74
business 418
business 489
tech 72
business 548
politics 66
business 423
error 2926
politics 190
entertainment 780
politics 70
sport 602
business 596
business 547
business 534
business 425
business 460
business 759
sport 347
tech 424
business 470
business 563
business 74
tech 234
politics 440
sport 256
business 262
tech 58
politics 121
entertainment 28
business 633
business 440
business 311
tech 9
business 606
tech 185
sport 817
sport 448
tech 92
politics 48
politics 22
tech 20
business 3043
business 634
entertainment 211
business 427
politics 498
sport 605
sport 166
business 919
tech 415
business 1138
sport 586
business 375
business 587
entertainment 561
business 272
tech 24
entertainment 253
politics 75
sport 30
entertainment 1425
politics 304
entertainment 283
politics 730
entertainment 558
business 1028
sport 492
business 846
business 28
tech 20
business 538
tech 47
tech 21
tech 25
politics 441
business 520
sport 294
business 567
tech 378
sport 247
politics 830
politics 57
sport 423
politics 59
business 498
entertainment 410
tech 35
tech 16
politics 610
tech 20
entertainment 340
tech 641
sport 457
politics 749
entertainment 422
politics 261
politics 403
tech 9
entertainment 610
politics 129
sport 415
business 983
entertainment 1061
tech 457
error 2323
politics 28
business 461
tech 8
business 442
tech 73
tech 950
entertainment 441
business 1459
tech 7
politics 960
politics 340
sport 610
business 470
politics 1177
tech 728
business 613
politics 27
politics 958
sport 426
sport 587
politics 27
politics 506
politics 377
business 115
business 115
sport 555
sport 120
politics 58

In [7]:
val

,text,label,prediction,num_tokens,response
0,Why Cell will get the hard sell The world is c...,tech,business,435,[text] [labels]\n\nto determine whether you ca...
1,Iranian MPs threaten mobile deal Turkey's bigg...,business,business,532,so i have to classify this text into one of th...
2,Google launches TV search service The net sear...,tech,entertainment,958,"[text]\n [options: tech, business, ent..."
3,"Dutch bank to lay off 2,850 staff ABN Amro, th...",business,tech,18,[inst] \n answer with the correct labe...
4,Franz Ferdinand's art school lesson Scottish r...,entertainment,tech,55,[inst]\n answer with the correct label...
...,...,...,...,...,...
374,Karachi stocks hit historic high The Karachi S...,business,business,115,[inst]\n text: the text is about the p...
375,Dance music not dead says Fatboy DJ Norman Coo...,entertainment,business,115,"[inst]\n please reason step by step, a..."
376,Real in talks over Gravesen move Real Madrid a...,sport,sport,555,"-- so, i need to figure out which category thi..."
377,Man Utd stroll to Cup win Wayne Rooney made a ...,sport,sport,120,[inst]\n text: the text is about the f...
378,Election 'could be terror target' Terrorists m...,politics,politics,58,[text]\n [options: a] tech b] business...

In [8]:
val.prediction.value_counts()

prediction
business         110
tech              69
politics          68
sport             55
entertainment     51
loop              20
error              6
Name: count, dtype: int64

In [12]:
max_num_tokens = val[val['prediction'] != 'loop']['num_tokens'].max()
print(f'Max number of tokens: {max_num_tokens}')

Max number of tokens: 3043

In [ ]:
average_num_tokens = val[(val['prediction'] != 'loop') & (val['prediction'] != 'error')]['num_tokens'].mean()
print(f'Average number of tokens: {average_num_tokens}')

Average number of tokens: 424.5269121813031

In [9]:
val.to_csv('reasoning_size_val.csv', index=False)