# Importing libraries

In [1]:
# Basic libraries
import pandas as pd
from datasets import load_dataset
import time
import pickle


# Classification models
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
from sklearn.naive_bayes import MultinomialNB

# Vectorizers
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer

# Utilities and metrics
from itertools import product
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
from memory_profiler import memory_usage

# Preprocessing
import nltk
import re

# Download nltk resources
nltk.download('wordnet')

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Rafael\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

# Setting seeds

In [2]:
s1 = 2
s2 = 3
s3 = 5

seeds = [s1, s2, s3]

# Importing datasets

In [3]:
ds = load_dataset("cardiffnlp/tweet_eval", "sentiment")

train = ds['train'].to_pandas()
val = ds['validation'].to_pandas()
test = ds['test'].to_pandas()

train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45615 entries, 0 to 45614
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   text    45615 non-null  object
 1   label   45615 non-null  int64
dtypes: int64(1), object(1)
memory usage: 712.9+ KB

# Dataset preprocessing

In [4]:
stop_words = set(nltk.corpus.stopwords.words('english'))
lemmatizer = nltk.stem.WordNetLemmatizer()

def preprocess_text(text):
    text = text.lower()

    text = re.sub(r'[^\w\s]', '', text)
    
    words = text.split()
    words = [word for word in words if word not in stop_words]
    words = [lemmatizer.lemmatize(word) for word in words]

    return ' '.join(words)
train['text'] = train['text'].apply(preprocess_text)

# GridSearch implementation

In [5]:
vectorizers = [
    TfidfVectorizer(),
    CountVectorizer()
]

models = {
    'RandomForest': {
        'model': RandomForestClassifier(),
        'params': {
            'n_estimators': [50, 100, 150],
            'criterion': ['gini', 'entropy', 'log_loss']
        }
    },
    'SVC': {
        'model': SVC(),
        'params': {
            'C': [0.1, 1, 10],
            'kernel': ['linear', 'rbf', 'sigmoid']
        }
    },
    'MultinomialNB': {
        'model': MultinomialNB(),
        'params': {
            'alpha': [0.01, 0.1, 1.0]
        }
    },
    'LogisticRegression': {
        'model': LogisticRegression(max_iter=1000),
        'params': {
            'C': [0.1, 1, 10],
            'penalty': ['l2']
        }
    },
    'KNeighbors': {
        'model': KNeighborsClassifier(),
        'params': {
            'n_neighbors': [3, 5, 7],
            'algorithm': ['ball_tree', 'kd_tree', 'brute']
        }
    },
    'DecisionTree': {
        'model': DecisionTreeClassifier(),
        'params': {
            'criterion': ['gini', 'entropy', 'log_loss'],
            'max_features': ['sqrt', 'log2', None]
        }
    },
    'GradientBoosting': {
        'model': GradientBoostingClassifier(),
        'params': {
            'n_estimators': [100, 150, 200],
            'criterion': ['friedman_mse', 'squared_error'],
        }
    },
    'AdaBoost': {
        'model': AdaBoostClassifier(),
        'params': {
            'n_estimators': [50, 100, 150],
            'learning_rate': [0.01, 0.1, 1.0]
        }
    },
    'SGD': {
        'model': SGDClassifier(),
        'params': {
            'alpha': [0.0001, 0.001, 0.01],
            'penalty': ['l2', 'l1', 'elasticnet']
        }
    }
}

In [6]:
columns = ['seed', 'vectorizer', 'model', 'params', 'accuracy', 'training_time', 'prediction_time', 'peak_memory_train', 'peak_memory_prediction']

classes = sorted(train['label'].unique())
for c in classes:
    columns.extend([
        f'precision_class_{c}',
        f'recall_class_{c}',
        f'f1_class_{c}'
    ])

results = pd.DataFrame(columns=columns)

In [7]:
for seed in seeds:
    print(f"Processing seed: {seed}")
    for vectorizer in vectorizers:
        print(f"Processing vectorizer: {vectorizer.__class__.__name__}")
        for name, info in models.items():
            print(f"Processing model: {name}")

            model = info['model']
            param_grid = info['params']
            param_combinations = product(*param_grid.values())
            
            for combination in param_combinations:
                params = dict(zip(param_grid.keys(), combination))
                model.set_params(**params)
                if 'random_state' in model.get_params():
                    model.set_params(random_state=seed)

                print(f"Training {name} with params {params} and vectorizer {vectorizer.__class__.__name__}")

                pipeline = Pipeline([
                    ('vectorizer', vectorizer),
                    ('model', model)
                ])

                def train_model():
                    pipeline.fit(train['text'], train['label'])

                def predict_model():
                    return pipeline.predict(val['text'])

                # Training Phase
                start_time = time.perf_counter()
                peak_memory_train = memory_usage(train_model, max_usage=True)
                train_time = time.perf_counter() - start_time
                print(f"Training time: {train_time}")
                print(f"Peak memory usage during training: {peak_memory_train} MB")

                # Prediction Phase
                start_time = time.perf_counter()
                peak_memory_pred, y_pred = memory_usage(predict_model, max_usage=True, retval=True)
                prediction_time = time.perf_counter() - start_time
                print(f"Prediction time: {prediction_time}")
                print(f"Peak memory usage during prediction: {peak_memory_pred} MB")
                
                accuracy = accuracy_score(val['label'], y_pred)
                precisions, recalls, f1s, supports = precision_recall_fscore_support(val['label'], y_pred, average=None, labels=classes, zero_division=0)

                result_dict = {
                    'seed': seed,
                    'vectorizer': vectorizer.__class__.__name__,
                    'model': name,
                    'params': params,
                    'accuracy': accuracy,
                    'training_time': train_time,
                    'prediction_time': prediction_time,
                    'peak_memory_train': peak_memory_train,
                    'peak_memory_prediction': peak_memory_pred,
                }

                for i, c in enumerate(classes):
                    result_dict[f'precision_class_{c}'] = precisions[i]
                    result_dict[f'recall_class_{c}'] = recalls[i]
                    result_dict[f'f1_class_{c}'] = f1s[i]

                result = pd.DataFrame([result_dict])
                results = pd.concat([results, result], ignore_index=True)
                print("-"*100)

results.to_csv('results/results_sklearn_multiclass1.csv', index=False)

Processing seed: 2
Processing vectorizer: TfidfVectorizer
Processing model: RandomForest
Training RandomForest with params {'n_estimators': 50, 'criterion': 'gini'} and vectorizer TfidfVectorizer
Training time: 76.19586860004347
Peak memory usage during training: 562.30078125 MB
Prediction time: 1.133649300027173
Peak memory usage during prediction: 556.421875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'entropy'} and vectorizer TfidfVectorizer

C:\Users\Rafael\AppData\Local\Temp\ipykernel_3720\1197191698.py:66: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results = pd.concat([results, result], ignore_index=True)

Training time: 75.1951239000191
Peak memory usage during training: 567.50390625 MB
Prediction time: 1.0976236999849789
Peak memory usage during prediction: 563.453125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'log_loss'} and vectorizer TfidfVectorizer
Training time: 75.31954990001395
Peak memory usage during training: 573.76171875 MB
Prediction time: 1.0989768000436015
Peak memory usage during prediction: 559.41015625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'gini'} and vectorizer TfidfVectorizer
Training time: 143.82616779999807
Peak memory usage during training: 731.71484375 MB
Prediction time: 1.3263453000108711
Peak memory usage during prediction: 732.0625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'entropy'} and vectorizer TfidfVectorizer
Training time: 150.82840370002668
Peak memory usage during training: 743.0625 MB
Prediction time: 1.2647580999764614
Peak memory usage during prediction: 743.00390625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'log_loss'} and vectorizer TfidfVectorizer
Training time: 149.85843020002358
Peak memory usage during training: 757.81640625 MB
Prediction time: 1.2618478999938816
Peak memory usage during prediction: 745.26171875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'gini'} and vectorizer TfidfVectorizer
Training time: 213.649984699965
Peak memory usage during training: 888.0234375 MB
Prediction time: 2.5299087000312284
Peak memory usage during prediction: 888.0234375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'entropy'} and vectorizer TfidfVectorizer
Training time: 225.04407409997657
Peak memory usage during training: 917.59375 MB
Prediction time: 0.7115446000243537
Peak memory usage during prediction: 917.9296875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'log_loss'} and vectorizer TfidfVectorizer
Training time: 224.84144300001208
Peak memory usage during training: 934.6640625 MB
Prediction time: 0.7090678999666125
Peak memory usage during prediction: 917.83984375 MB
----------------------------------------------------------------------------------------------------
Processing model: SVC
Training SVC with params {'C': 0.1, 'kernel': 'linear'} and vectorizer TfidfVectorizer
Training time: 185.47272650001105
Peak memory usage during training: 1174.4921875 MB
Prediction time: 5.257228500035126
Peak memory usage during prediction: 959.48046875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 0.1, 'kernel': 'rbf'} and vectorizer TfidfVectorizer
Training time: 273.3961845000158
Peak memory usage during training: 1215.140625 MB
Prediction time: 6.973778799991123
Peak memory usage during prediction: 943.4296875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 0.1, 'kernel': 'sigmoid'} and vectorizer TfidfVectorizer
Training time: 185.3808091999963
Peak memory usage during training: 1164.015625 MB
Prediction time: 5.42603119998239
Peak memory usage during prediction: 944.38671875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'linear'} and vectorizer TfidfVectorizer
Training time: 288.5808894999791
Peak memory usage during training: 1246.09375 MB
Prediction time: 4.75059319997672
Peak memory usage during prediction: 951.12109375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'rbf'} and vectorizer TfidfVectorizer
Training time: 452.35667120001744
Peak memory usage during training: 1212.2265625 MB
Prediction time: 6.614837000030093
Peak memory usage during prediction: 952.65234375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'sigmoid'} and vectorizer TfidfVectorizer
Training time: 336.49819859996205
Peak memory usage during training: 1189.6171875 MB
Prediction time: 4.732567499973811
Peak memory usage during prediction: 949.58984375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'linear'} and vectorizer TfidfVectorizer
Training time: 1321.8100469000055
Peak memory usage during training: 1252.77734375 MB
Prediction time: 4.4878439999883994
Peak memory usage during prediction: 949.83984375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'rbf'} and vectorizer TfidfVectorizer
Training time: 665.7081495000166
Peak memory usage during training: 1185.44921875 MB
Prediction time: 6.790804999996908
Peak memory usage during prediction: 959.21484375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'sigmoid'} and vectorizer TfidfVectorizer
Training time: 1687.993301999988
Peak memory usage during training: 1259.1484375 MB
Prediction time: 3.9879633000236936
Peak memory usage during prediction: 947.0546875 MB
----------------------------------------------------------------------------------------------------
Processing model: MultinomialNB
Training MultinomialNB with params {'alpha': 0.01} and vectorizer TfidfVectorizer
Training time: 0.8591836999985389
Peak memory usage during training: 936.55078125 MB
Prediction time: 1.395042599993758
Peak memory usage during prediction: 903.77734375 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'alpha': 0.1} and vectorizer TfidfVectorizer
Training time: 0.8270852999994531
Peak memory usage during training: 935.4609375 MB
Prediction time: 1.8190874999854714
Peak memory usage during prediction: 903.90625 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'alpha': 1.0} and vectorizer TfidfVectorizer
Training time: 0.8148203000309877
Peak memory usage during training: 937.86328125 MB
Prediction time: 1.8063540000002831
Peak memory usage during prediction: 904.02734375 MB
----------------------------------------------------------------------------------------------------
Processing model: LogisticRegression
Training LogisticRegression with params {'C': 0.1, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.5939930999884382
Peak memory usage during training: 969.05859375 MB
Prediction time: 1.807243200019002
Peak memory usage during prediction: 905.33984375 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'C': 1, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 2.712567299953662
Peak memory usage during training: 970.30078125 MB
Prediction time: 1.8219738000188954
Peak memory usage during prediction: 905.515625 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'C': 10, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 4.498706899990793
Peak memory usage during training: 969.67578125 MB
Prediction time: 1.3654076000093482
Peak memory usage during prediction: 905.61328125 MB
----------------------------------------------------------------------------------------------------
Processing model: KNeighbors
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'ball_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 0.8293976999702863
Peak memory usage during training: 936.87890625 MB
Prediction time: 1.8185971000348218
Peak memory usage during prediction: 2101.359375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'kd_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 0.8224684000015259
Peak memory usage during training: 945.7109375 MB
Prediction time: 1.7577406999771483
Peak memory usage during prediction: 2260.4140625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'brute'} and vectorizer TfidfVectorizer
Training time: 0.8117553999763913
Peak memory usage during training: 943.734375 MB
Prediction time: 1.701005199982319
Peak memory usage during prediction: 2123.3046875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'ball_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 0.8213622000184841
Peak memory usage during training: 946.04296875 MB
Prediction time: 1.7578133000060916
Peak memory usage during prediction: 2262.2890625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'kd_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 0.8191065000137314
Peak memory usage during training: 948.26953125 MB
Prediction time: 1.7676171000348404
Peak memory usage during prediction: 2251.4375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'brute'} and vectorizer TfidfVectorizer
Training time: 0.8203587000025436
Peak memory usage during training: 944.66796875 MB
Prediction time: 1.7224150000256486
Peak memory usage during prediction: 2287.28515625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'ball_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 0.8240734999999404
Peak memory usage during training: 942.9140625 MB
Prediction time: 1.7383654000004753
Peak memory usage during prediction: 2303.25 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'kd_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 0.8199011000106111
Peak memory usage during training: 941.91796875 MB
Prediction time: 1.708769500022754
Peak memory usage during prediction: 2134.3125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'brute'} and vectorizer TfidfVectorizer
Training time: 0.8308422000263818
Peak memory usage during training: 947.3515625 MB
Prediction time: 1.7519116000039503
Peak memory usage during prediction: 2262.08203125 MB
----------------------------------------------------------------------------------------------------
Processing model: DecisionTree
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'sqrt'} and vectorizer TfidfVectorizer
Training time: 2.9958892000140622
Peak memory usage during training: 949.5703125 MB
Prediction time: 1.8169502000091597
Peak memory usage during prediction: 916.5546875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'log2'} and vectorizer TfidfVectorizer
Training time: 3.2193582999752834
Peak memory usage during training: 952.85546875 MB
Prediction time: 1.8238769000163302
Peak memory usage during prediction: 917.67578125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': None} and vectorizer TfidfVectorizer
Training time: 27.616204900026787
Peak memory usage during training: 950.54296875 MB
Prediction time: 1.3893300999770872
Peak memory usage during prediction: 928.7578125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'sqrt'} and vectorizer TfidfVectorizer
Training time: 3.301488999975845
Peak memory usage during training: 947.21875 MB
Prediction time: 1.8219793000025675
Peak memory usage during prediction: 916.625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'log2'} and vectorizer TfidfVectorizer
Training time: 3.3181274000089616
Peak memory usage during training: 950.17578125 MB
Prediction time: 1.8280899999663234
Peak memory usage during prediction: 917.61328125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': None} and vectorizer TfidfVectorizer
Training time: 25.493240599986166
Peak memory usage during training: 946.5546875 MB
Prediction time: 1.3824970999849029
Peak memory usage during prediction: 928.453125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'sqrt'} and vectorizer TfidfVectorizer
Training time: 3.1678579000290483
Peak memory usage during training: 949.61328125 MB
Prediction time: 1.3871970000327565
Peak memory usage during prediction: 931.9609375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'log2'} and vectorizer TfidfVectorizer
Training time: 3.3608135999529622
Peak memory usage during training: 949.828125 MB
Prediction time: 1.3741241000243463
Peak memory usage during prediction: 917.66015625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': None} and vectorizer TfidfVectorizer
Training time: 25.52852960000746
Peak memory usage during training: 951.80859375 MB
Prediction time: 1.8126813999842852
Peak memory usage during prediction: 913.28515625 MB
----------------------------------------------------------------------------------------------------
Processing model: GradientBoosting
Training GradientBoosting with params {'n_estimators': 100, 'criterion': 'friedman_mse'} and vectorizer TfidfVectorizer
Training time: 52.30383789999178
Peak memory usage during training: 954.484375 MB
Prediction time: 1.8363244000356644
Peak memory usage during prediction: 915.6484375 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 100, 'criterion': 'squared_error'} and vectorizer TfidfVectorizer
Training time: 51.98634820000734
Peak memory usage during training: 954.86328125 MB
Prediction time: 1.386034999974072
Peak memory usage during prediction: 915.09375 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 150, 'criterion': 'friedman_mse'} and vectorizer TfidfVectorizer
Training time: 77.80065780004952
Peak memory usage during training: 954.72265625 MB
Prediction time: 0.9654946000082418
Peak memory usage during prediction: 937.73828125 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 150, 'criterion': 'squared_error'} and vectorizer TfidfVectorizer
Training time: 77.92465889995219
Peak memory usage during training: 956.12109375 MB
Prediction time: 0.9659888000460342
Peak memory usage during prediction: 915.43359375 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 200, 'criterion': 'friedman_mse'} and vectorizer TfidfVectorizer
Training time: 103.67689850000897
Peak memory usage during training: 955.48828125 MB
Prediction time: 1.8603538000024855
Peak memory usage during prediction: 916.16796875 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 200, 'criterion': 'squared_error'} and vectorizer TfidfVectorizer
Training time: 103.37836089998018
Peak memory usage during training: 956.29296875 MB
Prediction time: 0.961488000000827
Peak memory usage during prediction: 938.15234375 MB
----------------------------------------------------------------------------------------------------
Processing model: AdaBoost
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 0.01} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 4.789684500021394
Peak memory usage during training: 954.71484375 MB
Prediction time: 1.4031275999732316
Peak memory usage during prediction: 915.90625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 0.1} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 4.815229600004386
Peak memory usage during training: 954.9296875 MB
Prediction time: 1.4161407999927178
Peak memory usage during prediction: 915.25390625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 1.0} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 4.813120800012257
Peak memory usage during training: 954.515625 MB
Prediction time: 0.9551881999941543
Peak memory usage during prediction: 937.34375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 0.01} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 8.70502779999515
Peak memory usage during training: 954.609375 MB
Prediction time: 0.9827843999955803
Peak memory usage during prediction: 932.88671875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 0.1} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 8.798897600034252
Peak memory usage during training: 954.31640625 MB
Prediction time: 0.9786097999894992
Peak memory usage during prediction: 933.0 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 1.0} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 8.817856300040148
Peak memory usage during training: 954.54296875 MB
Prediction time: 0.9845435000024736
Peak memory usage during prediction: 932.9296875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 0.01} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 12.66185360000236
Peak memory usage during training: 954.27734375 MB
Prediction time: 1.0046512000262737
Peak memory usage during prediction: 915.4453125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 0.1} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 12.786861899949145
Peak memory usage during training: 954.53125 MB
Prediction time: 1.0198914000065997
Peak memory usage during prediction: 915.53515625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 1.0} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 12.826057200029027
Peak memory usage during training: 954.61328125 MB
Prediction time: 1.0218217999790795
Peak memory usage during prediction: 915.43359375 MB
----------------------------------------------------------------------------------------------------
Processing model: SGD
Training SGD with params {'alpha': 0.0001, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 0.9389551999629475
Peak memory usage during training: 950.8984375 MB
Prediction time: 1.8088321999530308
Peak memory usage during prediction: 917.2109375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.0001, 'penalty': 'l1'} and vectorizer TfidfVectorizer
Training time: 0.9476242000237107
Peak memory usage during training: 950.8046875 MB
Prediction time: 1.818513999984134
Peak memory usage during prediction: 917.21484375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.0001, 'penalty': 'elasticnet'} and vectorizer TfidfVectorizer
Training time: 1.0614417999750003
Peak memory usage during training: 950.71875 MB
Prediction time: 1.8186214999877848
Peak memory usage during prediction: 917.21875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 0.885166099993512
Peak memory usage during training: 950.7734375 MB
Prediction time: 1.3734632999985479
Peak memory usage during prediction: 917.08203125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'l1'} and vectorizer TfidfVectorizer
Training time: 0.9092878000228666
Peak memory usage during training: 950.60546875 MB
Prediction time: 1.8281251000007614
Peak memory usage during prediction: 917.22265625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'elasticnet'} and vectorizer TfidfVectorizer
Training time: 0.9327912000007927
Peak memory usage during training: 950.7734375 MB
Prediction time: 1.8172268999624066
Peak memory usage during prediction: 917.16796875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 0.8772000999888405
Peak memory usage during training: 950.75 MB
Prediction time: 1.8100093000102788
Peak memory usage during prediction: 917.1796875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'l1'} and vectorizer TfidfVectorizer
Training time: 0.9203540000016801
Peak memory usage during training: 951.4140625 MB
Prediction time: 0.9422615000512451
Peak memory usage during prediction: 951.41015625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'elasticnet'} and vectorizer TfidfVectorizer
Training time: 0.9336726000183262
Peak memory usage during training: 951.359375 MB
Prediction time: 1.826964300009422
Peak memory usage during prediction: 917.4375 MB
----------------------------------------------------------------------------------------------------
Processing vectorizer: CountVectorizer
Processing model: RandomForest
Training RandomForest with params {'n_estimators': 50, 'criterion': 'gini'} and vectorizer CountVectorizer
Training time: 86.51983170001768
Peak memory usage during training: 947.5078125 MB
Prediction time: 1.100508900010027
Peak memory usage during prediction: 605.875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'entropy'} and vectorizer CountVectorizer
Training time: 90.52384450001409
Peak memory usage during training: 616.4375 MB
Prediction time: 1.0879434999660589
Peak memory usage during prediction: 594.07421875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'log_loss'} and vectorizer CountVectorizer
Training time: 90.57865500001935
Peak memory usage during training: 621.234375 MB
Prediction time: 1.0915928999893367
Peak memory usage during prediction: 594.21484375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'gini'} and vectorizer CountVectorizer
Training time: 171.8500923999818
Peak memory usage during training: 797.38671875 MB
Prediction time: 1.2746654999791645
Peak memory usage during prediction: 778.2421875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'entropy'} and vectorizer CountVectorizer
Training time: 179.4924795999541
Peak memory usage during training: 814.05078125 MB
Prediction time: 1.2515656999894418
Peak memory usage during prediction: 779.97265625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'log_loss'} and vectorizer CountVectorizer
Training time: 179.63103729998693
Peak memory usage during training: 817.375 MB
Prediction time: 1.2547556000063196
Peak memory usage during prediction: 784.38671875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'gini'} and vectorizer CountVectorizer
Training time: 257.6508457000018
Peak memory usage during training: 984.3203125 MB
Prediction time: 0.724217500013765
Peak memory usage during prediction: 984.4140625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'entropy'} and vectorizer CountVectorizer
Training time: 268.9879728999804
Peak memory usage during training: 999.0625 MB
Prediction time: 0.7050736999954097
Peak memory usage during prediction: 995.79296875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'log_loss'} and vectorizer CountVectorizer
Training time: 269.2098920000135
Peak memory usage during training: 1012.65625 MB
Prediction time: 0.7139988000271842
Peak memory usage during prediction: 992.046875 MB
----------------------------------------------------------------------------------------------------
Processing model: SVC
Training SVC with params {'C': 0.1, 'kernel': 'linear'} and vectorizer CountVectorizer
Training time: 244.07231369998772
Peak memory usage during training: 1305.28125 MB
Prediction time: 4.618699199985713
Peak memory usage during prediction: 1026.5078125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 0.1, 'kernel': 'rbf'} and vectorizer CountVectorizer
Training time: 298.80795719998423
Peak memory usage during training: 1286.6171875 MB
Prediction time: 6.816126299963798
Peak memory usage during prediction: 1029.52734375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 0.1, 'kernel': 'sigmoid'} and vectorizer CountVectorizer
Training time: 155.1504051000229
Peak memory usage during training: 1237.39453125 MB
Prediction time: 5.276949799968861
Peak memory usage during prediction: 1028.29296875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'linear'} and vectorizer CountVectorizer
Training time: 1369.739329700009
Peak memory usage during training: 1320.22265625 MB
Prediction time: 4.3545120999915525
Peak memory usage during prediction: 1020.9140625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'rbf'} and vectorizer CountVectorizer
Training time: 447.0327469999902
Peak memory usage during training: 1296.42578125 MB
Prediction time: 6.530874099989887
Peak memory usage during prediction: 1024.8515625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'sigmoid'} and vectorizer CountVectorizer
Training time: 145.88290619995678
Peak memory usage during training: 1243.59375 MB
Prediction time: 4.322385999956168
Peak memory usage during prediction: 1014.17578125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'linear'} and vectorizer CountVectorizer
Training time: 4147.425511400041
Peak memory usage during training: 1362.4765625 MB
Prediction time: 4.00703669997165
Peak memory usage during prediction: 1020.21484375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'rbf'} and vectorizer CountVectorizer
Training time: 748.8678899999941
Peak memory usage during training: 1264.4296875 MB
Prediction time: 6.755563799990341
Peak memory usage during prediction: 1026.359375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'sigmoid'} and vectorizer CountVectorizer
Training time: 232.18615429999772
Peak memory usage during training: 1258.78515625 MB
Prediction time: 3.6913377000018954
Peak memory usage during prediction: 1019.484375 MB
----------------------------------------------------------------------------------------------------
Processing model: MultinomialNB
Training MultinomialNB with params {'alpha': 0.01} and vectorizer CountVectorizer
Training time: 0.8502501000184566
Peak memory usage during training: 1013.33984375 MB
Prediction time: 1.8618172000278719
Peak memory usage during prediction: 972.04296875 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'alpha': 0.1} and vectorizer CountVectorizer
Training time: 0.8465871000080369
Peak memory usage during training: 1011.32421875 MB
Prediction time: 1.8651483999565244
Peak memory usage during prediction: 970.51171875 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'alpha': 1.0} and vectorizer CountVectorizer
Training time: 0.8323017000220716
Peak memory usage during training: 1009.54296875 MB
Prediction time: 1.828385700006038
Peak memory usage during prediction: 969.921875 MB
----------------------------------------------------------------------------------------------------
Processing model: LogisticRegression
Training LogisticRegression with params {'C': 0.1, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.876773800002411
Peak memory usage during training: 1048.76953125 MB
Prediction time: 1.8253238999750465
Peak memory usage during prediction: 969.82421875 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'C': 1, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 3.318331099988427
Peak memory usage during training: 1048.12109375 MB
Prediction time: 1.8432136000483297
Peak memory usage during prediction: 969.90234375 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'C': 10, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 5.733151599997655
Peak memory usage during training: 1048.11328125 MB
Prediction time: 1.3898362999898382
Peak memory usage during prediction: 969.80859375 MB
----------------------------------------------------------------------------------------------------
Processing model: KNeighbors
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'ball_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 0.8069876999943517
Peak memory usage during training: 1006.97265625 MB
Prediction time: 1.9187068999744952
Peak memory usage during prediction: 2277.14453125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'kd_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 0.8109285000246018
Peak memory usage during training: 1009.76171875 MB
Prediction time: 1.7511317000025883
Peak memory usage during prediction: 2311.2578125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'brute'} and vectorizer CountVectorizer
Training time: 0.8242321000434458
Peak memory usage during training: 1008.0078125 MB
Prediction time: 1.788575399958063
Peak memory usage during prediction: 2315.62109375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'ball_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 0.8157791999983601
Peak memory usage during training: 1009.6484375 MB
Prediction time: 1.7941571000264958
Peak memory usage during prediction: 2332.46875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'kd_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 0.8116486999788322
Peak memory usage during training: 1009.88671875 MB
Prediction time: 1.7649528000038117
Peak memory usage during prediction: 2337.171875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'brute'} and vectorizer CountVectorizer
Training time: 0.8234172000084072
Peak memory usage during training: 1009.05859375 MB
Prediction time: 1.8046266000019386
Peak memory usage during prediction: 2314.3984375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'ball_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 0.8196941000060178
Peak memory usage during training: 1009.8984375 MB
Prediction time: 1.7673322000191547
Peak memory usage during prediction: 2359.20703125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'kd_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 0.8181178999948315
Peak memory usage during training: 1005.421875 MB
Prediction time: 1.7917008000076748
Peak memory usage during prediction: 2339.66796875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'brute'} and vectorizer CountVectorizer
Training time: 0.8208336000097916
Peak memory usage during training: 1009.7734375 MB
Prediction time: 1.7913730000145733
Peak memory usage during prediction: 2347.02734375 MB
----------------------------------------------------------------------------------------------------
Processing model: DecisionTree
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'sqrt'} and vectorizer CountVectorizer
Training time: 3.542661399987992
Peak memory usage during training: 1010.56640625 MB
Prediction time: 1.3897761999978684
Peak memory usage during prediction: 972.7734375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'log2'} and vectorizer CountVectorizer
Training time: 4.522473499993794
Peak memory usage during training: 1015.88671875 MB
Prediction time: 1.3734939999994822
Peak memory usage during prediction: 973.43359375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': None} and vectorizer CountVectorizer
Training time: 22.098517600039486
Peak memory usage during training: 1015.265625 MB
Prediction time: 1.3850100000272505
Peak memory usage during prediction: 983.87890625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'sqrt'} and vectorizer CountVectorizer
Training time: 3.849177600000985
Peak memory usage during training: 1009.23046875 MB
Prediction time: 1.8104233000194654
Peak memory usage during prediction: 972.7578125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'log2'} and vectorizer CountVectorizer
Training time: 4.64268390001962
Peak memory usage during training: 1019.23828125 MB
Prediction time: 1.811907900031656
Peak memory usage during prediction: 973.65625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': None} and vectorizer CountVectorizer
Training time: 18.92273859999841
Peak memory usage during training: 1015.41796875 MB
Prediction time: 1.8118523000157438
Peak memory usage during prediction: 969.25390625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'sqrt'} and vectorizer CountVectorizer
Training time: 3.8490729999612086
Peak memory usage during training: 1009.3828125 MB
Prediction time: 1.8221550000016578
Peak memory usage during prediction: 972.64453125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'log2'} and vectorizer CountVectorizer
Training time: 4.7434502999531105
Peak memory usage during training: 1019.3359375 MB
Prediction time: 1.3849213999928907
Peak memory usage during prediction: 973.453125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': None} and vectorizer CountVectorizer
Training time: 18.906393599987496
Peak memory usage during training: 1015.34375 MB
Prediction time: 1.828359699982684
Peak memory usage during prediction: 968.546875 MB
----------------------------------------------------------------------------------------------------
Processing model: GradientBoosting
Training GradientBoosting with params {'n_estimators': 100, 'criterion': 'friedman_mse'} and vectorizer CountVectorizer
Training time: 24.840511600021273
Peak memory usage during training: 1012.125 MB
Prediction time: 1.3851678000064567
Peak memory usage during prediction: 969.69921875 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 100, 'criterion': 'squared_error'} and vectorizer CountVectorizer
Training time: 24.8822402000078
Peak memory usage during training: 1012.25390625 MB
Prediction time: 1.374848400009796
Peak memory usage during prediction: 969.6015625 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 150, 'criterion': 'friedman_mse'} and vectorizer CountVectorizer
Training time: 36.72838499996578
Peak memory usage during training: 1012.5625 MB
Prediction time: 1.85807700001169
Peak memory usage during prediction: 970.0859375 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 150, 'criterion': 'squared_error'} and vectorizer CountVectorizer
Training time: 36.841541400004644
Peak memory usage during training: 1012.546875 MB
Prediction time: 0.9524638999719173
Peak memory usage during prediction: 970.07421875 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 200, 'criterion': 'friedman_mse'} and vectorizer CountVectorizer
Training time: 48.709479000011925
Peak memory usage during training: 1012.48828125 MB
Prediction time: 1.4036720999865793
Peak memory usage during prediction: 969.66015625 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 200, 'criterion': 'squared_error'} and vectorizer CountVectorizer
Training time: 48.573327200021595
Peak memory usage during training: 1012.58203125 MB
Prediction time: 1.3922325000166893
Peak memory usage during prediction: 970.13671875 MB
----------------------------------------------------------------------------------------------------
Processing model: AdaBoost
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 0.01} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 2.924460000009276
Peak memory usage during training: 1009.16015625 MB
Prediction time: 1.4244420999893919
Peak memory usage during prediction: 970.0546875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 0.1} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 2.9715156000456773
Peak memory usage during training: 1008.35546875 MB
Prediction time: 1.4067077999934554
Peak memory usage during prediction: 970.0234375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 1.0} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 2.9998104000114836
Peak memory usage during training: 1008.10546875 MB
Prediction time: 1.406312400009483
Peak memory usage during prediction: 969.3671875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 0.01} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 5.065008899953682
Peak memory usage during training: 1007.8671875 MB
Prediction time: 0.9824124000151642
Peak memory usage during prediction: 969.23828125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 0.1} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 5.227976199996192
Peak memory usage during training: 1007.87890625 MB
Prediction time: 0.989161100005731
Peak memory usage during prediction: 969.2421875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 1.0} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 5.176852000004146
Peak memory usage during training: 1007.875 MB
Prediction time: 0.9817136999918148
Peak memory usage during prediction: 969.1796875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 0.01} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 7.2402828999911435
Peak memory usage during training: 1007.83203125 MB
Prediction time: 1.0035554000060074
Peak memory usage during prediction: 969.09765625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 0.1} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 7.3740211999975145
Peak memory usage during training: 1007.70703125 MB
Prediction time: 1.003340199997183
Peak memory usage during prediction: 969.140625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 1.0} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 7.383144000021275
Peak memory usage during training: 1007.80078125 MB
Prediction time: 0.9982859999872744
Peak memory usage during prediction: 969.16796875 MB
----------------------------------------------------------------------------------------------------
Processing model: SGD
Training SGD with params {'alpha': 0.0001, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.1051252000033855
Peak memory usage during training: 1007.87109375 MB
Prediction time: 1.3637348999618553
Peak memory usage during prediction: 970.50390625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.0001, 'penalty': 'l1'} and vectorizer CountVectorizer
Training time: 1.2913937999983318
Peak memory usage during training: 1008.97265625 MB
Prediction time: 1.8049885000218637
Peak memory usage during prediction: 970.51953125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.0001, 'penalty': 'elasticnet'} and vectorizer CountVectorizer
Training time: 1.5345943999709561
Peak memory usage during training: 1009.02734375 MB
Prediction time: 1.8033147999667563
Peak memory usage during prediction: 970.5 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 0.9432203000178561
Peak memory usage during training: 1008.98828125 MB
Prediction time: 1.8287859999691136
Peak memory usage during prediction: 970.57421875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'l1'} and vectorizer CountVectorizer
Training time: 0.952293100010138
Peak memory usage during training: 1009.0625 MB
Prediction time: 1.800656599982176
Peak memory usage during prediction: 970.63671875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'elasticnet'} and vectorizer CountVectorizer
Training time: 1.031122999964282
Peak memory usage during training: 1008.96484375 MB
Prediction time: 1.801819600048475
Peak memory usage during prediction: 970.40234375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 0.8953031999990344
Peak memory usage during training: 1008.84765625 MB
Prediction time: 1.379325299989432
Peak memory usage during prediction: 970.46875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'l1'} and vectorizer CountVectorizer
Training time: 0.9197612999705598
Peak memory usage during training: 1008.90234375 MB
Prediction time: 1.8037501000217162
Peak memory usage during prediction: 970.5 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'elasticnet'} and vectorizer CountVectorizer
Training time: 0.9300144000444561
Peak memory usage during training: 1008.9140625 MB
Prediction time: 1.7928523999871686
Peak memory usage during prediction: 970.421875 MB
----------------------------------------------------------------------------------------------------
Processing seed: 3
Processing vectorizer: TfidfVectorizer
Processing model: RandomForest
Training RandomForest with params {'n_estimators': 50, 'criterion': 'gini'} and vectorizer TfidfVectorizer
Training time: 72.1619381000055
Peak memory usage during training: 1008.34765625 MB
Prediction time: 1.1087599000311457
Peak memory usage during prediction: 587.2109375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'entropy'} and vectorizer TfidfVectorizer
Training time: 75.50288519996684
Peak memory usage during training: 596.10546875 MB
Prediction time: 1.0870910999947228
Peak memory usage during prediction: 595.125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'log_loss'} and vectorizer TfidfVectorizer
Training time: 75.53308120003203
Peak memory usage during training: 605.6796875 MB
Prediction time: 1.0913758999668062
Peak memory usage during prediction: 594.8828125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'gini'} and vectorizer TfidfVectorizer
Training time: 142.8510017999797
Peak memory usage during training: 755.35546875 MB
Prediction time: 1.2986313999863341
Peak memory usage during prediction: 755.015625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'entropy'} and vectorizer TfidfVectorizer
Training time: 149.94943470001454
Peak memory usage during training: 773.3359375 MB
Prediction time: 1.2497889999649487
Peak memory usage during prediction: 773.45703125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'log_loss'} and vectorizer TfidfVectorizer
Training time: 149.7949193000095
Peak memory usage during training: 787.2890625 MB
Prediction time: 1.2616982000181451
Peak memory usage during prediction: 769.609375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'gini'} and vectorizer TfidfVectorizer
Training time: 213.40988799999468
Peak memory usage during training: 925.73828125 MB
Prediction time: 0.745631100027822
Peak memory usage during prediction: 925.76953125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'entropy'} and vectorizer TfidfVectorizer
Training time: 224.41014110000106
Peak memory usage during training: 947.875 MB
Prediction time: 0.7113918999675661
Peak memory usage during prediction: 948.00390625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'log_loss'} and vectorizer TfidfVectorizer
Training time: 224.50064829998882
Peak memory usage during training: 962.28515625 MB
Prediction time: 0.7066683999728411
Peak memory usage during prediction: 948.23046875 MB
----------------------------------------------------------------------------------------------------
Processing model: SVC
Training SVC with params {'C': 0.1, 'kernel': 'linear'} and vectorizer TfidfVectorizer
Training time: 185.37755599996308
Peak memory usage during training: 1198.18359375 MB
Prediction time: 5.28226230002474
Peak memory usage during prediction: 970.08203125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 0.1, 'kernel': 'rbf'} and vectorizer TfidfVectorizer
Training time: 273.763531900011
Peak memory usage during training: 1225.36328125 MB
Prediction time: 6.937593000009656
Peak memory usage during prediction: 963.5234375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 0.1, 'kernel': 'sigmoid'} and vectorizer TfidfVectorizer
Training time: 185.71686609997414
Peak memory usage during training: 1183.51953125 MB
Prediction time: 5.434680000005756
Peak memory usage during prediction: 963.33203125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'linear'} and vectorizer TfidfVectorizer
Training time: 288.69424570002593
Peak memory usage during training: 1262.81640625 MB
Prediction time: 4.767037099984009
Peak memory usage during prediction: 970.53125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'rbf'} and vectorizer TfidfVectorizer
Training time: 452.3283761999919
Peak memory usage during training: 1229.48828125 MB
Prediction time: 6.614950800023507
Peak memory usage during prediction: 971.54296875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'sigmoid'} and vectorizer TfidfVectorizer
Training time: 336.2258365000016
Peak memory usage during training: 1206.86328125 MB
Prediction time: 4.733866100024898
Peak memory usage during prediction: 968.38671875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'linear'} and vectorizer TfidfVectorizer
Training time: 1316.6657228999538
Peak memory usage during training: 1269.4921875 MB
Prediction time: 4.473624299978837
Peak memory usage during prediction: 968.80859375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'rbf'} and vectorizer TfidfVectorizer
Training time: 666.1415551999817
Peak memory usage during training: 1204.60546875 MB
Prediction time: 6.816528299998026
Peak memory usage during prediction: 978.5546875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'sigmoid'} and vectorizer TfidfVectorizer
Training time: 1686.2289869000087
Peak memory usage during training: 1274.95703125 MB
Prediction time: 3.9991954999859445
Peak memory usage during prediction: 965.91796875 MB
----------------------------------------------------------------------------------------------------
Processing model: MultinomialNB
Training MultinomialNB with params {'alpha': 0.01} and vectorizer TfidfVectorizer
Training time: 0.8475997999776155
Peak memory usage during training: 956.04296875 MB
Prediction time: 1.7891428000293672
Peak memory usage during prediction: 920.390625 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'alpha': 0.1} and vectorizer TfidfVectorizer
Training time: 0.8220894999685697
Peak memory usage during training: 959.17578125 MB
Prediction time: 1.801606900000479
Peak memory usage during prediction: 920.5703125 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'alpha': 1.0} and vectorizer TfidfVectorizer
Training time: 0.8137402000138536
Peak memory usage during training: 958.2734375 MB
Prediction time: 1.8049022000050172
Peak memory usage during prediction: 920.48046875 MB
----------------------------------------------------------------------------------------------------
Processing model: LogisticRegression
Training LogisticRegression with params {'C': 0.1, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.5445261999848299
Peak memory usage during training: 989.77734375 MB
Prediction time: 1.36956670001382
Peak memory usage during prediction: 946.2109375 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'C': 1, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 2.739756499999203
Peak memory usage during training: 990.73046875 MB
Prediction time: 1.3682953999959864
Peak memory usage during prediction: 920.37109375 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'C': 10, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 4.4704989999881946
Peak memory usage during training: 990.1171875 MB
Prediction time: 1.3779983999556862
Peak memory usage during prediction: 920.46875 MB
----------------------------------------------------------------------------------------------------
Processing model: KNeighbors
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'ball_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 0.8159469999955036
Peak memory usage during training: 957.43359375 MB
Prediction time: 1.8377091999864206
Peak memory usage during prediction: 2295.76171875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'kd_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 0.8216210000100546
Peak memory usage during training: 959.671875 MB
Prediction time: 1.7438980000442825
Peak memory usage during prediction: 2274.44140625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'brute'} and vectorizer TfidfVectorizer
Training time: 0.8221921999938786
Peak memory usage during training: 955.40234375 MB
Prediction time: 1.7162756000179797
Peak memory usage during prediction: 2227.64453125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'ball_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 0.8328996999771334
Peak memory usage during training: 959.55859375 MB
Prediction time: 1.7236755000194535
Peak memory usage during prediction: 2307.7265625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'kd_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 0.8278793999925256
Peak memory usage during training: 955.46875 MB
Prediction time: 1.7081317999982275
Peak memory usage during prediction: 2120.640625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'brute'} and vectorizer TfidfVectorizer
Training time: 0.8317839999799617
Peak memory usage during training: 959.5625 MB
Prediction time: 1.761594099982176
Peak memory usage during prediction: 2267.40234375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'ball_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 0.8195813999627717
Peak memory usage during training: 955.47265625 MB
Prediction time: 1.718286600022111
Peak memory usage during prediction: 2141.05078125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'kd_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 0.8262114999815822
Peak memory usage during training: 959.6875 MB
Prediction time: 1.7507946999976411
Peak memory usage during prediction: 2264.13671875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'brute'} and vectorizer TfidfVectorizer
Training time: 0.8285348999779671
Peak memory usage during training: 955.46875 MB
Prediction time: 1.706510599993635
Peak memory usage during prediction: 2149.91015625 MB
----------------------------------------------------------------------------------------------------
Processing model: DecisionTree
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'sqrt'} and vectorizer TfidfVectorizer
Training time: 3.0019271000055596
Peak memory usage during training: 962.88671875 MB
Prediction time: 1.8153880000463687
Peak memory usage during prediction: 922.52734375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'log2'} and vectorizer TfidfVectorizer
Training time: 3.2048490999732167
Peak memory usage during training: 966.56640625 MB
Prediction time: 1.3902172000380233
Peak memory usage during prediction: 923.52734375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': None} and vectorizer TfidfVectorizer
Training time: 27.791262099985033
Peak memory usage during training: 963.328125 MB
Prediction time: 1.8000143999815919
Peak memory usage during prediction: 919.15625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'sqrt'} and vectorizer TfidfVectorizer
Training time: 3.0864436999545433
Peak memory usage during training: 957.56640625 MB
Prediction time: 1.8027412999654189
Peak memory usage during prediction: 922.484375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'log2'} and vectorizer TfidfVectorizer
Training time: 3.362832700018771
Peak memory usage during training: 966.02734375 MB
Prediction time: 1.8240590000059456
Peak memory usage during prediction: 923.4453125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': None} and vectorizer TfidfVectorizer
Training time: 25.703118299948983
Peak memory usage during training: 968.78515625 MB
Prediction time: 1.3806521999649704
Peak memory usage during prediction: 933.8671875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'sqrt'} and vectorizer TfidfVectorizer
Training time: 3.255639099981636
Peak memory usage during training: 956.1640625 MB
Prediction time: 1.810637799964752
Peak memory usage during prediction: 922.42578125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'log2'} and vectorizer TfidfVectorizer
Training time: 3.5103646000497974
Peak memory usage during training: 965.65234375 MB
Prediction time: 0.9405205000075512
Peak memory usage during prediction: 945.0625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': None} and vectorizer TfidfVectorizer
Training time: 25.350772400037386
Peak memory usage during training: 968.5 MB
Prediction time: 1.8170755000319332
Peak memory usage during prediction: 919.36328125 MB
----------------------------------------------------------------------------------------------------
Processing model: GradientBoosting
Training GradientBoosting with params {'n_estimators': 100, 'criterion': 'friedman_mse'} and vectorizer TfidfVectorizer
Training time: 52.4523275999818
Peak memory usage during training: 964.75 MB
Prediction time: 1.3902422999963164
Peak memory usage during prediction: 941.94921875 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 100, 'criterion': 'squared_error'} and vectorizer TfidfVectorizer
Training time: 52.13728050002828
Peak memory usage during training: 964.328125 MB
Prediction time: 1.4038964999490418
Peak memory usage during prediction: 941.9140625 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 150, 'criterion': 'friedman_mse'} and vectorizer TfidfVectorizer
Training time: 78.04653390002204
Peak memory usage during training: 964.1875 MB
Prediction time: 1.4009594999952242
Peak memory usage during prediction: 920.13671875 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 150, 'criterion': 'squared_error'} and vectorizer TfidfVectorizer
Training time: 77.79304660001071
Peak memory usage during training: 964.5546875 MB
Prediction time: 1.4012481999816373
Peak memory usage during prediction: 941.3984375 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 200, 'criterion': 'friedman_mse'} and vectorizer TfidfVectorizer
Training time: 102.31406820000848
Peak memory usage during training: 964.69140625 MB
Prediction time: 1.4076370000257157
Peak memory usage during prediction: 920.25 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 200, 'criterion': 'squared_error'} and vectorizer TfidfVectorizer
Training time: 103.3326993000228
Peak memory usage during training: 964.46875 MB
Prediction time: 1.3966370000271127
Peak memory usage during prediction: 920.0546875 MB
----------------------------------------------------------------------------------------------------
Processing model: AdaBoost
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 0.01} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 4.743733899958897
Peak memory usage during training: 959.32421875 MB
Prediction time: 1.4085953999892808
Peak memory usage during prediction: 919.578125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 0.1} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 4.817200999998022
Peak memory usage during training: 958.58984375 MB
Prediction time: 1.4070134999928996
Peak memory usage during prediction: 919.671875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 1.0} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 4.810284200008027
Peak memory usage during training: 958.85546875 MB
Prediction time: 0.9681363999843597
Peak memory usage during prediction: 941.1328125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 0.01} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 8.689058899995871
Peak memory usage during training: 959.1171875 MB
Prediction time: 0.9879473999608308
Peak memory usage during prediction: 937.2265625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 0.1} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 8.796600400004536
Peak memory usage during training: 958.94921875 MB
Prediction time: 0.9841955000301823
Peak memory usage during prediction: 937.234375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 1.0} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 8.933662199997343
Peak memory usage during training: 958.77734375 MB
Prediction time: 0.9868495000409894
Peak memory usage during prediction: 941.39453125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 0.01} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 12.65472019999288
Peak memory usage during training: 958.8671875 MB
Prediction time: 1.0155154999811202
Peak memory usage during prediction: 919.40234375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 0.1} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 12.79076200001873
Peak memory usage during training: 957.94921875 MB
Prediction time: 1.0095668000285514
Peak memory usage during prediction: 919.05859375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 1.0} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 12.792040099971928
Peak memory usage during training: 958.546875 MB
Prediction time: 1.0097863000119105
Peak memory usage during prediction: 919.17578125 MB
----------------------------------------------------------------------------------------------------
Processing model: SGD
Training SGD with params {'alpha': 0.0001, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 0.9265471000107937
Peak memory usage during training: 955.86328125 MB
Prediction time: 1.360652500006836
Peak memory usage during prediction: 920.03125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.0001, 'penalty': 'l1'} and vectorizer TfidfVectorizer
Training time: 0.9737781000440009
Peak memory usage during training: 955.984375 MB
Prediction time: 1.8045723999966867
Peak memory usage during prediction: 920.14453125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.0001, 'penalty': 'elasticnet'} and vectorizer TfidfVectorizer
Training time: 1.0532997999689542
Peak memory usage during training: 955.9296875 MB
Prediction time: 1.8029486000305042
Peak memory usage during prediction: 920.19140625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 0.8849795999703929
Peak memory usage during training: 955.97265625 MB
Prediction time: 1.3706405000411905
Peak memory usage during prediction: 920.15625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'l1'} and vectorizer TfidfVectorizer
Training time: 0.9133015999686904
Peak memory usage during training: 956.0 MB
Prediction time: 1.3888915000134148
Peak memory usage during prediction: 920.15625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'elasticnet'} and vectorizer TfidfVectorizer
Training time: 0.958954099973198
Peak memory usage during training: 955.94140625 MB
Prediction time: 1.3734267000108957
Peak memory usage during prediction: 920.17578125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 0.8906705999979749
Peak memory usage during training: 955.95703125 MB
Prediction time: 1.8092089999699965
Peak memory usage during prediction: 920.14453125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'l1'} and vectorizer TfidfVectorizer
Training time: 0.9245124000008218
Peak memory usage during training: 955.98828125 MB
Prediction time: 1.372898300003726
Peak memory usage during prediction: 920.15234375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'elasticnet'} and vectorizer TfidfVectorizer
Training time: 0.924366099992767
Peak memory usage during training: 955.9375 MB
Prediction time: 1.3750588999828324
Peak memory usage during prediction: 920.19921875 MB
----------------------------------------------------------------------------------------------------
Processing vectorizer: CountVectorizer
Processing model: RandomForest
Training RandomForest with params {'n_estimators': 50, 'criterion': 'gini'} and vectorizer CountVectorizer
Training time: 86.17580769996857
Peak memory usage during training: 955.83203125 MB
Prediction time: 1.1067807999788783
Peak memory usage during prediction: 608.34765625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'entropy'} and vectorizer CountVectorizer
Training time: 90.28676780004753
Peak memory usage during training: 616.56640625 MB
Prediction time: 1.0914674999658018
Peak memory usage during prediction: 595.828125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'log_loss'} and vectorizer CountVectorizer
Training time: 90.16219730000012
Peak memory usage during training: 622.97265625 MB
Prediction time: 1.0923218000098132
Peak memory usage during prediction: 590.6171875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'gini'} and vectorizer CountVectorizer
Training time: 171.67442360002315
Peak memory usage during training: 794.3359375 MB
Prediction time: 1.2641225999686867
Peak memory usage during prediction: 794.7890625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'entropy'} and vectorizer CountVectorizer
Training time: 179.55995870003244
Peak memory usage during training: 814.5703125 MB
Prediction time: 1.2456309999688528
Peak memory usage during prediction: 803.99609375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'log_loss'} and vectorizer CountVectorizer
Training time: 179.76102500001434
Peak memory usage during training: 824.8515625 MB
Prediction time: 1.2394057999481447
Peak memory usage during prediction: 803.9609375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'gini'} and vectorizer CountVectorizer
Training time: 256.7639433000004
Peak memory usage during training: 982.29296875 MB
Prediction time: 0.7281078000087291
Peak memory usage during prediction: 982.36328125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'entropy'} and vectorizer CountVectorizer
Training time: 268.27674729999853
Peak memory usage during training: 1001.20703125 MB
Prediction time: 0.7036950999754481
Peak memory usage during prediction: 992.4375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'log_loss'} and vectorizer CountVectorizer
Training time: 269.69819299998926
Peak memory usage during training: 1011.828125 MB
Prediction time: 0.7105220999801531
Peak memory usage during prediction: 997.48828125 MB
----------------------------------------------------------------------------------------------------
Processing model: SVC
Training SVC with params {'C': 0.1, 'kernel': 'linear'} and vectorizer CountVectorizer
Training time: 244.00803590001306
Peak memory usage during training: 1311.67578125 MB
Prediction time: 4.598176400002558
Peak memory usage during prediction: 1032.05078125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 0.1, 'kernel': 'rbf'} and vectorizer CountVectorizer
Training time: 297.16889440000523
Peak memory usage during training: 1294.23828125 MB
Prediction time: 6.805246600008104
Peak memory usage during prediction: 1025.3203125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 0.1, 'kernel': 'sigmoid'} and vectorizer CountVectorizer
Training time: 155.11266690003686
Peak memory usage during training: 1233.984375 MB
Prediction time: 5.285406000039075
Peak memory usage during prediction: 1024.6484375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'linear'} and vectorizer CountVectorizer
Training time: 1370.6075912999804
Peak memory usage during training: 1325.27734375 MB
Prediction time: 4.419999799982179
Peak memory usage during prediction: 1022.38671875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'rbf'} and vectorizer CountVectorizer
Training time: 448.8183638000046
Peak memory usage during training: 1297.3359375 MB
Prediction time: 6.565830200037453
Peak memory usage during prediction: 1025.5078125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'sigmoid'} and vectorizer CountVectorizer
Training time: 146.32494720001705
Peak memory usage during training: 1244.56640625 MB
Prediction time: 4.355741599982139
Peak memory usage during prediction: 1023.03515625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'linear'} and vectorizer CountVectorizer
Training time: 4149.852424499986
Peak memory usage during training: 1362.625 MB
Prediction time: 3.999074599996675
Peak memory usage during prediction: 1022.34375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'rbf'} and vectorizer CountVectorizer
Training time: 772.2050603000098
Peak memory usage during training: 1262.59765625 MB
Prediction time: 6.839434799971059
Peak memory usage during prediction: 1027.171875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'sigmoid'} and vectorizer CountVectorizer
Training time: 232.8343960000202
Peak memory usage during training: 1258.90625 MB
Prediction time: 3.6692639000248164
Peak memory usage during prediction: 1017.65625 MB
----------------------------------------------------------------------------------------------------
Processing model: MultinomialNB
Training MultinomialNB with params {'alpha': 0.01} and vectorizer CountVectorizer
Training time: 0.8393282999750227
Peak memory usage during training: 1009.8984375 MB
Prediction time: 1.4021278999862261
Peak memory usage during prediction: 969.9765625 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'alpha': 0.1} and vectorizer CountVectorizer
Training time: 0.8324710000306368
Peak memory usage during training: 1012.19140625 MB
Prediction time: 1.3893625999917276
Peak memory usage during prediction: 968.64453125 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'alpha': 1.0} and vectorizer CountVectorizer
Training time: 0.8302765000262298
Peak memory usage during training: 1009.3125 MB
Prediction time: 1.3862812999868765
Peak memory usage during prediction: 967.4140625 MB
----------------------------------------------------------------------------------------------------
Processing model: LogisticRegression
Training LogisticRegression with params {'C': 0.1, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.932043300010264
Peak memory usage during training: 1048.078125 MB
Prediction time: 1.8424289000104181
Peak memory usage during prediction: 967.4921875 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'C': 1, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 3.385692099982407
Peak memory usage during training: 1050.234375 MB
Prediction time: 1.8387195999966934
Peak memory usage during prediction: 967.4921875 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'C': 10, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 5.900446699990425
Peak memory usage during training: 1050.8828125 MB
Prediction time: 1.8443868999602273
Peak memory usage during prediction: 967.125 MB
----------------------------------------------------------------------------------------------------
Processing model: KNeighbors
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'ball_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 0.8272890000371262
Peak memory usage during training: 1009.66796875 MB
Prediction time: 1.9319899999536574
Peak memory usage during prediction: 2319.73046875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'kd_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 0.8668995999614708
Peak memory usage during training: 1010.9765625 MB
Prediction time: 1.82512409996707
Peak memory usage during prediction: 2290.73828125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'brute'} and vectorizer CountVectorizer
Training time: 0.863618899951689
Peak memory usage during training: 1009.6015625 MB
Prediction time: 1.8013366000377573
Peak memory usage during prediction: 2345.12109375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'ball_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 0.8436137000098825
Peak memory usage during training: 1010.48046875 MB
Prediction time: 1.8379845999879763
Peak memory usage during prediction: 2254.8984375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'kd_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 0.8518797000288032
Peak memory usage during training: 1009.328125 MB
Prediction time: 1.8307810999685898
Peak memory usage during prediction: 2283.5859375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'brute'} and vectorizer CountVectorizer
Training time: 0.8458987000049092
Peak memory usage during training: 1010.890625 MB
Prediction time: 1.8053911999450065
Peak memory usage during prediction: 2343.828125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'ball_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 0.8438033999991603
Peak memory usage during training: 1009.0625 MB
Prediction time: 1.8457960999803618
Peak memory usage during prediction: 2239.91796875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'kd_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 0.8359644000302069
Peak memory usage during training: 1010.86328125 MB
Prediction time: 1.8270096000051126
Peak memory usage during prediction: 2299.5 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'brute'} and vectorizer CountVectorizer
Training time: 0.859081199974753
Peak memory usage during training: 1009.5 MB
Prediction time: 1.8015482000191696
Peak memory usage during prediction: 2322.0859375 MB
----------------------------------------------------------------------------------------------------
Processing model: DecisionTree
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'sqrt'} and vectorizer CountVectorizer
Training time: 3.7773059000028297
Peak memory usage during training: 1010.8046875 MB
Prediction time: 1.8576224999851547
Peak memory usage during prediction: 970.12890625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'log2'} and vectorizer CountVectorizer
Training time: 4.7722915999474935
Peak memory usage during training: 1014.3984375 MB
Prediction time: 1.8737606999929994
Peak memory usage during prediction: 970.97265625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': None} and vectorizer CountVectorizer
Training time: 21.74340990005294
Peak memory usage during training: 1015.16015625 MB
Prediction time: 1.856710199965164
Peak memory usage during prediction: 966.52734375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'sqrt'} and vectorizer CountVectorizer
Training time: 3.7795323000173084
Peak memory usage during training: 1011.49609375 MB
Prediction time: 1.4235946999979205
Peak memory usage during prediction: 970.2421875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'log2'} and vectorizer CountVectorizer
Training time: 4.8781390999793075
Peak memory usage during training: 1014.74609375 MB
Prediction time: 1.8523786999867298
Peak memory usage during prediction: 970.9140625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': None} and vectorizer CountVectorizer
Training time: 18.94782619999023
Peak memory usage during training: 1015.37109375 MB
Prediction time: 1.8246765999938361
Peak memory usage during prediction: 966.72265625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'sqrt'} and vectorizer CountVectorizer
Training time: 3.690934300015215
Peak memory usage during training: 1012.1875 MB
Prediction time: 1.8236189999734052
Peak memory usage during prediction: 970.1484375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'log2'} and vectorizer CountVectorizer
Training time: 4.662052700005006
Peak memory usage during training: 1016.51953125 MB
Prediction time: 1.3788763000047766
Peak memory usage during prediction: 970.9609375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': None} and vectorizer CountVectorizer
Training time: 18.982471099996474
Peak memory usage during training: 1014.8359375 MB
Prediction time: 0.9629026000038721
Peak memory usage during prediction: 981.2734375 MB
----------------------------------------------------------------------------------------------------
Processing model: GradientBoosting
Training GradientBoosting with params {'n_estimators': 100, 'criterion': 'friedman_mse'} and vectorizer CountVectorizer
Training time: 25.016416800033767
Peak memory usage during training: 1013.0859375 MB
Prediction time: 1.390792499994859
Peak memory usage during prediction: 989.578125 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 100, 'criterion': 'squared_error'} and vectorizer CountVectorizer
Training time: 25.118148699984886
Peak memory usage during training: 1010.43359375 MB
Prediction time: 1.385783099976834
Peak memory usage during prediction: 918.60546875 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 150, 'criterion': 'friedman_mse'} and vectorizer CountVectorizer
Training time: 37.20275320002111
Peak memory usage during training: 964.91796875 MB
Prediction time: 1.3943777999957092
Peak memory usage during prediction: 918.94140625 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 150, 'criterion': 'squared_error'} and vectorizer CountVectorizer
Training time: 37.252115199982654
Peak memory usage during training: 965.54296875 MB
Prediction time: 1.8530368999927305
Peak memory usage during prediction: 918.96484375 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 200, 'criterion': 'friedman_mse'} and vectorizer CountVectorizer
Training time: 49.38812479999615
Peak memory usage during training: 964.78125 MB
Prediction time: 1.4086534000234678
Peak memory usage during prediction: 918.70703125 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 200, 'criterion': 'squared_error'} and vectorizer CountVectorizer
Training time: 49.30646809999598
Peak memory usage during training: 964.78125 MB
Prediction time: 0.9570966000319459
Peak memory usage during prediction: 940.08984375 MB
----------------------------------------------------------------------------------------------------
Processing model: AdaBoost
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 0.01} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 2.9671247000223957
Peak memory usage during training: 962.90234375 MB
Prediction time: 1.4224402999971062
Peak memory usage during prediction: 919.078125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 0.1} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 3.0135353000368923
Peak memory usage during training: 963.05078125 MB
Prediction time: 0.9621766000054777
Peak memory usage during prediction: 939.57421875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 1.0} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 3.0234077000059187
Peak memory usage during training: 962.984375 MB
Prediction time: 0.9989980000536889
Peak memory usage during prediction: 917.66796875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 0.01} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 5.131805100012571
Peak memory usage during training: 963.125 MB
Prediction time: 0.9889264999656007
Peak memory usage during prediction: 917.66796875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 0.1} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 5.225861599959899
Peak memory usage during training: 962.8359375 MB
Prediction time: 0.9832884999923408
Peak memory usage during prediction: 917.83984375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 1.0} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 5.250999900046736
Peak memory usage during training: 963.05078125 MB
Prediction time: 0.9868693000171334
Peak memory usage during prediction: 917.5546875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 0.01} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 7.327043600031175
Peak memory usage during training: 962.375 MB
Prediction time: 1.0169761999859475
Peak memory usage during prediction: 917.66796875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 0.1} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 7.4346543999854475
Peak memory usage during training: 962.65234375 MB
Prediction time: 1.0229528999770992
Peak memory usage during prediction: 917.70703125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 1.0} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 7.436437500000466
Peak memory usage during training: 961.953125 MB
Prediction time: 1.0122569000232033
Peak memory usage during prediction: 917.4921875 MB
----------------------------------------------------------------------------------------------------
Processing model: SGD
Training SGD with params {'alpha': 0.0001, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.1023142999620177
Peak memory usage during training: 962.71484375 MB
Prediction time: 1.7969267999869771
Peak memory usage during prediction: 919.25390625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.0001, 'penalty': 'l1'} and vectorizer CountVectorizer
Training time: 1.3034402999910526
Peak memory usage during training: 962.74609375 MB
Prediction time: 1.8163181000272743
Peak memory usage during prediction: 919.015625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.0001, 'penalty': 'elasticnet'} and vectorizer CountVectorizer
Training time: 1.5377254000050016
Peak memory usage during training: 962.72265625 MB
Prediction time: 1.3753084000200033
Peak memory usage during prediction: 932.0703125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 0.951475300011225
Peak memory usage during training: 962.49609375 MB
Prediction time: 1.369162300019525
Peak memory usage during prediction: 918.7890625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'l1'} and vectorizer CountVectorizer
Training time: 0.9616730000125244
Peak memory usage during training: 962.49609375 MB
Prediction time: 1.801315999997314
Peak memory usage during prediction: 919.0859375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'elasticnet'} and vectorizer CountVectorizer
Training time: 1.06401409994578
Peak memory usage during training: 962.53515625 MB
Prediction time: 1.3716447999468073
Peak memory usage during prediction: 918.9296875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 0.8985568999778479
Peak memory usage during training: 962.6640625 MB
Prediction time: 1.3797637000097893
Peak memory usage during prediction: 918.7734375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'l1'} and vectorizer CountVectorizer
Training time: 0.9368201999459416
Peak memory usage during training: 962.64453125 MB
Prediction time: 1.8334449999965727
Peak memory usage during prediction: 919.12109375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'elasticnet'} and vectorizer CountVectorizer
Training time: 0.9554956000065431
Peak memory usage during training: 962.734375 MB
Prediction time: 1.3731962000019848
Peak memory usage during prediction: 918.890625 MB
----------------------------------------------------------------------------------------------------
Processing seed: 5
Processing vectorizer: TfidfVectorizer
Processing model: RandomForest
Training RandomForest with params {'n_estimators': 50, 'criterion': 'gini'} and vectorizer TfidfVectorizer
Training time: 72.23630259995116
Peak memory usage during training: 962.30859375 MB
Prediction time: 1.1116198999807239
Peak memory usage during prediction: 524.0703125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'entropy'} and vectorizer TfidfVectorizer
Training time: 75.71120109996991
Peak memory usage during training: 533.73828125 MB
Prediction time: 1.0918566000182182
Peak memory usage during prediction: 533.1875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'log_loss'} and vectorizer TfidfVectorizer
Training time: 76.03182679996826
Peak memory usage during training: 543.66796875 MB
Prediction time: 1.1010561999864876
Peak memory usage during prediction: 531.5625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'gini'} and vectorizer TfidfVectorizer
Training time: 143.38690730003873
Peak memory usage during training: 693.98046875 MB
Prediction time: 1.2962387000443414
Peak memory usage during prediction: 694.125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'entropy'} and vectorizer TfidfVectorizer
Training time: 150.42053770000348
Peak memory usage during training: 709.4609375 MB
Prediction time: 1.2673946000286378
Peak memory usage during prediction: 707.85546875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'log_loss'} and vectorizer TfidfVectorizer
Training time: 150.5862803000491
Peak memory usage during training: 726.4140625 MB
Prediction time: 1.2673292999970727
Peak memory usage during prediction: 707.734375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'gini'} and vectorizer TfidfVectorizer
Training time: 214.408824299986
Peak memory usage during training: 852.515625 MB
Prediction time: 0.7477007000125013
Peak memory usage during prediction: 852.375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'entropy'} and vectorizer TfidfVectorizer
Training time: 225.79319870000472
Peak memory usage during training: 884.37890625 MB
Prediction time: 0.7160224000108428
Peak memory usage during prediction: 884.54296875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'log_loss'} and vectorizer TfidfVectorizer
Training time: 226.22607700002845
Peak memory usage during training: 900.984375 MB
Prediction time: 0.7164353000116535
Peak memory usage during prediction: 884.54296875 MB
----------------------------------------------------------------------------------------------------
Processing model: SVC
Training SVC with params {'C': 0.1, 'kernel': 'linear'} and vectorizer TfidfVectorizer
Training time: 193.36448170000222
Peak memory usage during training: 1136.10546875 MB
Prediction time: 5.350475599989295
Peak memory usage during prediction: 917.765625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 0.1, 'kernel': 'rbf'} and vectorizer TfidfVectorizer
Training time: 281.43367820000276
Peak memory usage during training: 1173.1328125 MB
Prediction time: 7.898125100007746
Peak memory usage during prediction: 918.78515625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 0.1, 'kernel': 'sigmoid'} and vectorizer TfidfVectorizer
Training time: 190.27113959996495
Peak memory usage during training: 1127.99609375 MB
Prediction time: 5.522287499974482
Peak memory usage during prediction: 910.0390625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'linear'} and vectorizer TfidfVectorizer
Training time: 306.41420030000154
Peak memory usage during training: 1170.703125 MB
Prediction time: 4.93247210001573
Peak memory usage during prediction: 741.47265625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'rbf'} and vectorizer TfidfVectorizer
Training time: 474.2747148000053
Peak memory usage during training: 1002.22265625 MB
Prediction time: 6.883138999983203
Peak memory usage during prediction: 737.89453125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'sigmoid'} and vectorizer TfidfVectorizer
Training time: 356.857814899995
Peak memory usage during training: 969.4921875 MB
Prediction time: 4.926832799974363
Peak memory usage during prediction: 727.640625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'linear'} and vectorizer TfidfVectorizer
Training time: 1359.6274431999773
Peak memory usage during training: 968.39453125 MB
Prediction time: 4.68728769995505
Peak memory usage during prediction: 185.49609375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'rbf'} and vectorizer TfidfVectorizer
Training time: 707.7541270000511
Peak memory usage during training: 421.77734375 MB
Prediction time: 7.490087600017432
Peak memory usage during prediction: 194.578125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'sigmoid'} and vectorizer TfidfVectorizer
Training time: 1763.824553900049
Peak memory usage during training: 492.68359375 MB
Prediction time: 4.051356200012378
Peak memory usage during prediction: 181.71875 MB
----------------------------------------------------------------------------------------------------
Processing model: MultinomialNB
Training MultinomialNB with params {'alpha': 0.01} and vectorizer TfidfVectorizer
Training time: 0.8462891000090167
Peak memory usage during training: 173.328125 MB
Prediction time: 1.8336599000031129
Peak memory usage during prediction: 139.296875 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'alpha': 0.1} and vectorizer TfidfVectorizer
Training time: 0.8534086000290699
Peak memory usage during training: 176.58203125 MB
Prediction time: 1.8608010999741964
Peak memory usage during prediction: 139.515625 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'alpha': 1.0} and vectorizer TfidfVectorizer
Training time: 0.8506549000157975
Peak memory usage during training: 180.84765625 MB
Prediction time: 1.8613020000047982
Peak memory usage during prediction: 139.53125 MB
----------------------------------------------------------------------------------------------------
Processing model: LogisticRegression
Training LogisticRegression with params {'C': 0.1, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.6483924000058323
Peak memory usage during training: 211.39453125 MB
Prediction time: 1.4027215000241995
Peak memory usage during prediction: 142.95703125 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'C': 1, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 2.881651400006376
Peak memory usage during training: 214.63671875 MB
Prediction time: 1.8678466000128537
Peak memory usage during prediction: 143.03515625 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'C': 10, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 4.6755373000050895
Peak memory usage during training: 214.43359375 MB
Prediction time: 1.8523382000275888
Peak memory usage during prediction: 143.140625 MB
----------------------------------------------------------------------------------------------------
Processing model: KNeighbors
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'ball_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 0.8378149999771267
Peak memory usage during training: 184.484375 MB
Prediction time: 1.847272899991367
Peak memory usage during prediction: 1524.36328125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'kd_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 0.8711807000217959
Peak memory usage during training: 189.70703125 MB
Prediction time: 1.7950755000347272
Peak memory usage during prediction: 1436.61328125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'brute'} and vectorizer TfidfVectorizer
Training time: 0.8459840000141412
Peak memory usage during training: 190.9609375 MB
Prediction time: 1.7957560999784619
Peak memory usage during prediction: 1457.625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'ball_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 0.85702430002857
Peak memory usage during training: 189.5390625 MB
Prediction time: 1.763314799987711
Peak memory usage during prediction: 1490.65234375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'kd_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 0.874261699966155
Peak memory usage during training: 190.97265625 MB
Prediction time: 1.8116826000041328
Peak memory usage during prediction: 1433.9921875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'brute'} and vectorizer TfidfVectorizer
Training time: 0.8514964000205509
Peak memory usage during training: 189.76953125 MB
Prediction time: 1.8490235999925062
Peak memory usage during prediction: 1390.3203125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'ball_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 0.9216167000122368
Peak memory usage during training: 191.1953125 MB
Prediction time: 1.8680092999711633
Peak memory usage during prediction: 1529.69140625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'kd_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 0.9154951000236906
Peak memory usage during training: 189.8828125 MB
Prediction time: 1.8768242999794893
Peak memory usage during prediction: 1532.5859375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'brute'} and vectorizer TfidfVectorizer
Training time: 0.9340541000128724
Peak memory usage during training: 190.55078125 MB
Prediction time: 1.8812020000186749
Peak memory usage during prediction: 1539.96484375 MB
----------------------------------------------------------------------------------------------------
Processing model: DecisionTree
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'sqrt'} and vectorizer TfidfVectorizer
Training time: 3.3388906000182033
Peak memory usage during training: 191.48046875 MB
Prediction time: 1.9616385999834165
Peak memory usage during prediction: 155.15625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'log2'} and vectorizer TfidfVectorizer
Training time: 3.7866330000106245
Peak memory usage during training: 194.34375 MB
Prediction time: 1.476243999961298
Peak memory usage during prediction: 156.05859375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': None} and vectorizer TfidfVectorizer
Training time: 28.75345129997004
Peak memory usage during training: 195.578125 MB
Prediction time: 1.9464377999538556
Peak memory usage during prediction: 151.68359375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'sqrt'} and vectorizer TfidfVectorizer
Training time: 3.397755899990443
Peak memory usage during training: 192.45703125 MB
Prediction time: 1.9243210999993607
Peak memory usage during prediction: 155.30859375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'log2'} and vectorizer TfidfVectorizer
Training time: 3.5293283000355586
Peak memory usage during training: 194.703125 MB
Prediction time: 1.4701284999609925
Peak memory usage during prediction: 156.0546875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': None} and vectorizer TfidfVectorizer
Training time: 27.536177600035444
Peak memory usage during training: 195.51171875 MB
Prediction time: 1.9495347999618389
Peak memory usage during prediction: 151.9453125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'sqrt'} and vectorizer TfidfVectorizer
Training time: 3.278510499978438
Peak memory usage during training: 192.7890625 MB
Prediction time: 1.4679436999722384
Peak memory usage during prediction: 155.125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'log2'} and vectorizer TfidfVectorizer
Training time: 3.6802992000011727
Peak memory usage during training: 194.42578125 MB
Prediction time: 1.4698481999803334
Peak memory usage during prediction: 156.00390625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': None} and vectorizer TfidfVectorizer
Training time: 27.252927599998657
Peak memory usage during training: 196.421875 MB
Prediction time: 1.9459508000290953
Peak memory usage during prediction: 151.71875 MB
----------------------------------------------------------------------------------------------------
Processing model: GradientBoosting
Training GradientBoosting with params {'n_estimators': 100, 'criterion': 'friedman_mse'} and vectorizer TfidfVectorizer
Training time: 56.60633149999194
Peak memory usage during training: 196.22265625 MB
Prediction time: 1.4471286999760196
Peak memory usage during prediction: 155.59375 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 100, 'criterion': 'squared_error'} and vectorizer TfidfVectorizer
Training time: 55.7617128000129
Peak memory usage during training: 199.1328125 MB
Prediction time: 1.4510654999758117
Peak memory usage during prediction: 155.59375 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 150, 'criterion': 'friedman_mse'} and vectorizer TfidfVectorizer
Training time: 83.26436029997421
Peak memory usage during training: 197.7421875 MB
Prediction time: 1.031115299963858
Peak memory usage during prediction: 156.59765625 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 150, 'criterion': 'squared_error'} and vectorizer TfidfVectorizer
Training time: 81.01382990001002
Peak memory usage during training: 199.15234375 MB
Prediction time: 1.4496186999604106
Peak memory usage during prediction: 156.1484375 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 200, 'criterion': 'friedman_mse'} and vectorizer TfidfVectorizer
Training time: 107.19220550003229
Peak memory usage during training: 198.0546875 MB
Prediction time: 1.4620162000064738
Peak memory usage during prediction: 156.46484375 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 200, 'criterion': 'squared_error'} and vectorizer TfidfVectorizer
Training time: 107.64106980001088
Peak memory usage during training: 199.5 MB
Prediction time: 0.9979294000077061
Peak memory usage during prediction: 156.421875 MB
----------------------------------------------------------------------------------------------------
Processing model: AdaBoost
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 0.01} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 5.162634400010575
Peak memory usage during training: 197.59765625 MB
Prediction time: 1.5228005000390112
Peak memory usage during prediction: 156.43359375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 0.1} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 5.112158800009638
Peak memory usage during training: 198.41796875 MB
Prediction time: 1.0301507000112906
Peak memory usage during prediction: 156.34375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 1.0} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 4.997240700002294
Peak memory usage during training: 197.6640625 MB
Prediction time: 1.072438000002876
Peak memory usage during prediction: 178.37890625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 0.01} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 9.508743299986236
Peak memory usage during training: 199.25390625 MB
Prediction time: 1.1034879999933764
Peak memory usage during prediction: 156.1328125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 0.1} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 9.32683909998741
Peak memory usage during training: 197.62890625 MB
Prediction time: 1.024732399964705
Peak memory usage during prediction: 156.0390625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 1.0} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 9.393146599992178
Peak memory usage during training: 198.453125 MB
Prediction time: 1.0607645999989472
Peak memory usage during prediction: 155.94140625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 0.01} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 13.171561099996325
Peak memory usage during training: 197.609375 MB
Prediction time: 1.0477274999720976
Peak memory usage during prediction: 173.74609375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 0.1} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 13.251861599972472
Peak memory usage during training: 197.65234375 MB
Prediction time: 1.045453600003384
Peak memory usage during prediction: 177.51171875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 1.0} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 13.22743069997523
Peak memory usage during training: 196.74609375 MB
Prediction time: 1.0530052999965847
Peak memory usage during prediction: 177.4453125 MB
----------------------------------------------------------------------------------------------------
Processing model: SGD
Training SGD with params {'alpha': 0.0001, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 0.9823215000214987
Peak memory usage during training: 196.34765625 MB
Prediction time: 1.9799420000053942
Peak memory usage during prediction: 157.7890625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.0001, 'penalty': 'l1'} and vectorizer TfidfVectorizer
Training time: 1.047525100002531
Peak memory usage during training: 196.35546875 MB
Prediction time: 1.8688644000212662
Peak memory usage during prediction: 157.82421875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.0001, 'penalty': 'elasticnet'} and vectorizer TfidfVectorizer
Training time: 1.0999306999729015
Peak memory usage during training: 196.64453125 MB
Prediction time: 1.846218199993018
Peak memory usage during prediction: 157.89453125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 0.9153623000020161
Peak memory usage during training: 196.6953125 MB
Prediction time: 1.8775435000425205
Peak memory usage during prediction: 157.84765625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'l1'} and vectorizer TfidfVectorizer
Training time: 0.9539579999982379
Peak memory usage during training: 196.421875 MB
Prediction time: 1.8603007000056095
Peak memory usage during prediction: 157.890625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'elasticnet'} and vectorizer TfidfVectorizer
Training time: 0.9746885999920778
Peak memory usage during training: 196.703125 MB
Prediction time: 1.8702770000090823
Peak memory usage during prediction: 157.8984375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 0.9227077000541613
Peak memory usage during training: 196.7109375 MB
Prediction time: 1.902136699995026
Peak memory usage during prediction: 158.1640625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'l1'} and vectorizer TfidfVectorizer
Training time: 0.9640160999842919
Peak memory usage during training: 196.640625 MB
Prediction time: 1.4099941999884322
Peak memory usage during prediction: 158.07421875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'elasticnet'} and vectorizer TfidfVectorizer
Training time: 0.9709451000089757
Peak memory usage during training: 196.55859375 MB
Prediction time: 1.8634465000359342
Peak memory usage during prediction: 158.10546875 MB
----------------------------------------------------------------------------------------------------
Processing vectorizer: CountVectorizer
Processing model: RandomForest
Training RandomForest with params {'n_estimators': 50, 'criterion': 'gini'} and vectorizer CountVectorizer
Training time: 90.3908858000068
Peak memory usage during training: 368.60546875 MB
Prediction time: 1.1930836000246927
Peak memory usage during prediction: 351.4296875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'entropy'} and vectorizer CountVectorizer
Training time: 94.43271960003767
Peak memory usage during training: 378.92578125 MB
Prediction time: 1.1666131999809295
Peak memory usage during prediction: 355.76953125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'log_loss'} and vectorizer CountVectorizer
Training time: 92.47915179998381
Peak memory usage during training: 386.56640625 MB
Prediction time: 1.1635446000145748
Peak memory usage during prediction: 355.671875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'gini'} and vectorizer CountVectorizer
Training time: 178.00786309997784
Peak memory usage during training: 558.796875 MB
Prediction time: 1.406216899980791
Peak memory usage during prediction: 539.9140625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'entropy'} and vectorizer CountVectorizer
Training time: 189.7609444000409
Peak memory usage during training: 574.5859375 MB
Prediction time: 1.2831441999878734
Peak memory usage during prediction: 547.80859375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'log_loss'} and vectorizer CountVectorizer
Training time: 192.29909430001862
Peak memory usage during training: 584.46875 MB
Prediction time: 3.5895006000064313
Peak memory usage during prediction: 547.59765625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'gini'} and vectorizer CountVectorizer
Training time: 265.2213499000063
Peak memory usage during training: 745.3359375 MB
Prediction time: 0.7525033999700099
Peak memory usage during prediction: 745.41796875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'entropy'} and vectorizer CountVectorizer
Training time: 276.3495656999876
Peak memory usage during training: 763.29296875 MB
Prediction time: 0.7671919999993406
Peak memory usage during prediction: 736.55859375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'log_loss'} and vectorizer CountVectorizer
Training time: 270.5487490000087
Peak memory usage during training: 752.484375 MB
Prediction time: 0.7273875999962911
Peak memory usage during prediction: 736.47265625 MB
----------------------------------------------------------------------------------------------------
Processing model: SVC
Training SVC with params {'C': 0.1, 'kernel': 'linear'} and vectorizer CountVectorizer
Training time: 246.3522183999885
Peak memory usage during training: 1032.3671875 MB
Prediction time: 6.999227399996016
Peak memory usage during prediction: 748.91796875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 0.1, 'kernel': 'rbf'} and vectorizer CountVectorizer
Training time: 298.4283166999812
Peak memory usage during training: 1019.50390625 MB
Prediction time: 6.8748115000198595
Peak memory usage during prediction: 760.5703125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 0.1, 'kernel': 'sigmoid'} and vectorizer CountVectorizer
Training time: 155.91627749998588
Peak memory usage during training: 968.609375 MB
Prediction time: 5.286558199964929
Peak memory usage during prediction: 760.1171875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'linear'} and vectorizer CountVectorizer
Training time: 1368.1910148999887
Peak memory usage during training: 1054.65234375 MB
Prediction time: 4.393734199984465
Peak memory usage during prediction: 757.41796875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'rbf'} and vectorizer CountVectorizer
Training time: 447.6458815000369
Peak memory usage during training: 1035.95703125 MB
Prediction time: 6.535241700010374
Peak memory usage during prediction: 761.3984375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'sigmoid'} and vectorizer CountVectorizer
Training time: 145.85059140005615
Peak memory usage during training: 980.890625 MB
Prediction time: 4.320885599998292
Peak memory usage during prediction: 756.55859375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'linear'} and vectorizer CountVectorizer
Training time: 4331.964726899983
Peak memory usage during training: 1097.74609375 MB
Prediction time: 4.203806699952111
Peak memory usage during prediction: 157.34375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'rbf'} and vectorizer CountVectorizer
Training time: 787.1172695999849
Peak memory usage during training: 423.765625 MB
Prediction time: 7.541297600022517
Peak memory usage during prediction: 189.765625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'sigmoid'} and vectorizer CountVectorizer
Training time: 246.94109879998723
Peak memory usage during training: 425.46875 MB
Prediction time: 3.8606421000440605
Peak memory usage during prediction: 186.1015625 MB
----------------------------------------------------------------------------------------------------
Processing model: MultinomialNB
Training MultinomialNB with params {'alpha': 0.01} and vectorizer CountVectorizer
Training time: 0.9404580999980681
Peak memory usage during training: 182.28125 MB
Prediction time: 1.9452633999753743
Peak memory usage during prediction: 141.359375 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'alpha': 0.1} and vectorizer CountVectorizer
Training time: 0.878877199953422
Peak memory usage during training: 185.2734375 MB
Prediction time: 1.942261399992276
Peak memory usage during prediction: 140.41015625 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'alpha': 1.0} and vectorizer CountVectorizer
Training time: 0.8931318000541069
Peak memory usage during training: 182.80859375 MB
Prediction time: 1.4692243000026792
Peak memory usage during prediction: 139.82421875 MB
----------------------------------------------------------------------------------------------------
Processing model: LogisticRegression
Training LogisticRegression with params {'C': 0.1, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 2.1489370999624953
Peak memory usage during training: 225.83203125 MB
Prediction time: 2.015106900013052
Peak memory usage during prediction: 143.109375 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'C': 1, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 3.8570813999976963
Peak memory usage during training: 226.8984375 MB
Prediction time: 2.0031958000035957
Peak memory usage during prediction: 142.77734375 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'C': 10, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 6.284613299998455
Peak memory usage during training: 226.796875 MB
Prediction time: 1.5124757000012323
Peak memory usage during prediction: 142.69140625 MB
----------------------------------------------------------------------------------------------------
Processing model: KNeighbors
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'ball_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 0.9417644999921322
Peak memory usage during training: 185.87890625 MB
Prediction time: 2.1261333999573253
Peak memory usage during prediction: 1462.40625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'kd_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 0.9656831999891438
Peak memory usage during training: 194.5625 MB
Prediction time: 1.9969600000185892
Peak memory usage during prediction: 1501.30078125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'brute'} and vectorizer CountVectorizer
Training time: 0.9246551999822259
Peak memory usage during training: 193.35546875 MB
Prediction time: 2.0058868000051007
Peak memory usage during prediction: 1550.75 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'ball_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 0.9283936999854632
Peak memory usage during training: 194.37890625 MB
Prediction time: 1.9155553999589756
Peak memory usage during prediction: 1418.05859375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'kd_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 0.9054343000170775
Peak memory usage during training: 194.80859375 MB
Prediction time: 1.9511733000399545
Peak memory usage during prediction: 1514.75 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'brute'} and vectorizer CountVectorizer
Training time: 0.9430774999782443
Peak memory usage during training: 194.4375 MB
Prediction time: 1.8893918999820016
Peak memory usage during prediction: 1526.9453125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'ball_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 0.9279962000437081
Peak memory usage during training: 194.5390625 MB
Prediction time: 1.9473731000325643
Peak memory usage during prediction: 1523.6953125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'kd_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 0.9602636999916285
Peak memory usage during training: 195.015625 MB
Prediction time: 2.041492799995467
Peak memory usage during prediction: 1547.3203125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'brute'} and vectorizer CountVectorizer
Training time: 0.9078640000079758
Peak memory usage during training: 193.7421875 MB
Prediction time: 1.9220233000232838
Peak memory usage during prediction: 1537.96484375 MB
----------------------------------------------------------------------------------------------------
Processing model: DecisionTree
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'sqrt'} and vectorizer CountVectorizer
Training time: 3.963556900038384
Peak memory usage during training: 195.703125 MB
Prediction time: 1.9655596999800764
Peak memory usage during prediction: 156.140625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'log2'} and vectorizer CountVectorizer
Training time: 4.7364028000156395
Peak memory usage during training: 197.83984375 MB
Prediction time: 1.9259707999881357
Peak memory usage during prediction: 157.0859375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': None} and vectorizer CountVectorizer
Training time: 22.79473899997538
Peak memory usage during training: 196.94921875 MB
Prediction time: 1.9763448999729007
Peak memory usage during prediction: 152.4921875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'sqrt'} and vectorizer CountVectorizer
Training time: 3.9669190000277013
Peak memory usage during training: 198.0 MB
Prediction time: 1.5958448000019416
Peak memory usage during prediction: 156.171875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'log2'} and vectorizer CountVectorizer
Training time: 4.9898989999783225
Peak memory usage during training: 199.78515625 MB
Prediction time: 1.535453199991025
Peak memory usage during prediction: 157.0 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': None} and vectorizer CountVectorizer
Training time: 20.751136699982453
Peak memory usage during training: 200.0859375 MB
Prediction time: 2.1252383000100963
Peak memory usage during prediction: 152.7421875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'sqrt'} and vectorizer CountVectorizer
Training time: 4.0095415999530815
Peak memory usage during training: 198.4140625 MB
Prediction time: 1.4873239999869838
Peak memory usage during prediction: 156.2890625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'log2'} and vectorizer CountVectorizer
Training time: 4.87796289997641
Peak memory usage during training: 198.50390625 MB
Prediction time: 1.4875816999701783
Peak memory usage during prediction: 157.078125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': None} and vectorizer CountVectorizer
Training time: 19.5427297000424
Peak memory usage during training: 200.55859375 MB
Prediction time: 1.55733290000353
Peak memory usage during prediction: 152.5390625 MB
----------------------------------------------------------------------------------------------------
Processing model: GradientBoosting
Training GradientBoosting with params {'n_estimators': 100, 'criterion': 'friedman_mse'} and vectorizer CountVectorizer
Training time: 25.814284899970517
Peak memory usage during training: 201.9453125 MB
Prediction time: 1.9439642999786884
Peak memory usage during prediction: 155.4140625 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 100, 'criterion': 'squared_error'} and vectorizer CountVectorizer
Training time: 26.22153730003629
Peak memory usage during training: 203.67578125 MB
Prediction time: 1.9062307000276633
Peak memory usage during prediction: 155.85546875 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 150, 'criterion': 'friedman_mse'} and vectorizer CountVectorizer
Training time: 38.193751199985854
Peak memory usage during training: 203.21875 MB
Prediction time: 1.4892955999821424
Peak memory usage during prediction: 156.46484375 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 150, 'criterion': 'squared_error'} and vectorizer CountVectorizer
Training time: 37.18761369999265
Peak memory usage during training: 203.17578125 MB
Prediction time: 1.4470008999924175
Peak memory usage during prediction: 156.3671875 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 200, 'criterion': 'friedman_mse'} and vectorizer CountVectorizer
Training time: 49.84900980000384
Peak memory usage during training: 203.32421875 MB
Prediction time: 1.490689600002952
Peak memory usage during prediction: 156.13671875 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 200, 'criterion': 'squared_error'} and vectorizer CountVectorizer
Training time: 50.18128690001322
Peak memory usage during training: 203.203125 MB
Prediction time: 1.5842695999890566
Peak memory usage during prediction: 155.7734375 MB
----------------------------------------------------------------------------------------------------
Processing model: AdaBoost
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 0.01} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 3.1480232999892905
Peak memory usage during training: 201.7265625 MB
Prediction time: 1.0150180999771692
Peak memory usage during prediction: 156.12109375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 0.1} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 3.172080999996979
Peak memory usage during training: 201.47265625 MB
Prediction time: 1.5035170000046492
Peak memory usage during prediction: 155.91796875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 1.0} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 3.1680678999982774
Peak memory usage during training: 201.60546875 MB
Prediction time: 1.5283342000329867
Peak memory usage during prediction: 155.796875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 0.01} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 5.400487500010058
Peak memory usage during training: 200.98828125 MB
Prediction time: 1.081494800047949
Peak memory usage during prediction: 155.53125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 0.1} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 5.495722399966326
Peak memory usage during training: 201.1796875 MB
Prediction time: 1.0813119999947958
Peak memory usage during prediction: 155.69921875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 1.0} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 5.489425299980212
Peak memory usage during training: 201.046875 MB
Prediction time: 1.0506434999988414
Peak memory usage during prediction: 155.6328125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 0.01} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 7.815516300033778
Peak memory usage during training: 201.23828125 MB
Prediction time: 1.0453059999854304
Peak memory usage during prediction: 177.37890625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 0.1} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 7.796173200011253
Peak memory usage during training: 201.0078125 MB
Prediction time: 1.1603092000004835
Peak memory usage during prediction: 177.21484375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 1.0} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 7.897672499995679
Peak memory usage during training: 201.18359375 MB
Prediction time: 1.0959071000106633
Peak memory usage during prediction: 177.390625 MB
----------------------------------------------------------------------------------------------------
Processing model: SGD
Training SGD with params {'alpha': 0.0001, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.324422899982892
Peak memory usage during training: 200.4921875 MB
Prediction time: 1.4696710999705829
Peak memory usage during prediction: 157.546875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.0001, 'penalty': 'l1'} and vectorizer CountVectorizer
Training time: 1.4402074000099674
Peak memory usage during training: 200.73046875 MB
Prediction time: 1.9452456000144593
Peak memory usage during prediction: 157.546875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.0001, 'penalty': 'elasticnet'} and vectorizer CountVectorizer
Training time: 1.7285524999606423
Peak memory usage during training: 200.51953125 MB
Prediction time: 1.4392392999725416
Peak memory usage during prediction: 157.37890625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 0.9845956999924965
Peak memory usage during training: 200.49609375 MB
Prediction time: 1.8800329999648966
Peak memory usage during prediction: 157.48828125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'l1'} and vectorizer CountVectorizer
Training time: 1.095747399958782
Peak memory usage during training: 200.4453125 MB
Prediction time: 1.945797499967739
Peak memory usage during prediction: 157.50390625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'elasticnet'} and vectorizer CountVectorizer
Training time: 1.2243052000412717
Peak memory usage during training: 200.6015625 MB
Prediction time: 1.4606371000409126
Peak memory usage during prediction: 157.47265625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 0.9428569999872707
Peak memory usage during training: 200.30078125 MB
Prediction time: 1.9212006999878213
Peak memory usage during prediction: 157.546875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'l1'} and vectorizer CountVectorizer
Training time: 1.0122810000320897
Peak memory usage during training: 200.50390625 MB
Prediction time: 1.9032882999745198
Peak memory usage during prediction: 157.53125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'elasticnet'} and vectorizer CountVectorizer
Training time: 1.0377717000083067
Peak memory usage during training: 200.3671875 MB
Prediction time: 1.8930320999934338
Peak memory usage during prediction: 157.515625 MB
----------------------------------------------------------------------------------------------------

# Process results

In [8]:
results.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 396 entries, 0 to 395
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seed                    396 non-null    object
 1   vectorizer              396 non-null    object
 2   model                   396 non-null    object
 3   params                  396 non-null    object
 4   accuracy                396 non-null    float64
 5   training_time           396 non-null    float64
 6   prediction_time         396 non-null    float64
 7   peak_memory_train       396 non-null    float64
 8   peak_memory_prediction  396 non-null    float64
 9   precision_class_0       396 non-null    float64
 10  recall_class_0          396 non-null    float64
 11  f1_class_0              396 non-null    float64
 12  precision_class_1       396 non-null    float64
 13  recall_class_1          396 non-null    float64
 14  f1_class_1              396 non-null    float64
 15  precision_class_2       396 non-null    float64
 16  recall_class_2          396 non-null    float64
 17  f1_class_2              396 non-null    float64
dtypes: float64(14), object(4)
memory usage: 55.8+ KB

In [9]:
results.head()

,seed,vectorizer,model,params,accuracy,training_time,prediction_time,peak_memory_train,peak_memory_prediction,precision_class_0,recall_class_0,f1_class_0,precision_class_1,recall_class_1,f1_class_1,precision_class_2,recall_class_2,f1_class_2
0,2,TfidfVectorizer,RandomForest,"{'n_estimators': 50, 'criterion': 'gini'}",0.6175,76.195869,1.133649,562.300781,556.421875,0.552941,0.150641,0.236776,0.565842,0.815880,0.668238,0.723565,0.584860,0.646860
1,2,TfidfVectorizer,RandomForest,"{'n_estimators': 50, 'criterion': 'entropy'}",0.6245,75.195124,1.097624,567.503906,563.453125,0.647059,0.176282,0.277078,0.567546,0.817031,0.669811,0.728916,0.590965,0.652731
2,2,TfidfVectorizer,RandomForest,"{'n_estimators': 50, 'criterion': 'log_loss'}",0.6245,75.319550,1.098977,573.761719,559.410156,0.647059,0.176282,0.277078,0.567546,0.817031,0.669811,0.728916,0.590965,0.652731
3,2,TfidfVectorizer,RandomForest,"{'n_estimators': 100, 'criterion': 'gini'}",0.6255,143.826168,1.326345,731.714844,732.062500,0.597826,0.176282,0.272277,0.573529,0.807825,0.670807,0.722222,0.603175,0.657352
4,2,TfidfVectorizer,RandomForest,"{'n_estimators': 100, 'criterion': 'entropy'}",0.6240,150.828404,1.264758,743.062500,743.003906,0.654762,0.176282,0.277778,0.567891,0.818182,0.670438,0.725904,0.588523,0.650034

In [10]:
results['params'] = results['params'].astype(str)
results_avg_seed = results.groupby(['model', 'vectorizer', 'params']).mean().reset_index()
results_avg_seed['f1_avg'] = results_avg_seed[[col for col in results_avg_seed.columns if 'f1_class' in col]].mean(axis=1)
results_avg_seed

,model,vectorizer,params,seed,accuracy,training_time,prediction_time,peak_memory_train,peak_memory_prediction,precision_class_0,recall_class_0,f1_class_0,precision_class_1,recall_class_1,f1_class_1,precision_class_2,recall_class_2,f1_class_2,f1_avg
0,AdaBoost,CountVectorizer,"{'n_estimators': 100, 'learning_rate': 0.01}",3.333333,0.5175,5.199100,1.017611,723.993490,680.812500,0.000000,0.000000,0.000000,0.476434,0.965478,0.638023,0.820084,0.239316,0.370510,0.336178
1,AdaBoost,CountVectorizer,"{'n_estimators': 100, 'learning_rate': 0.1}",3.333333,0.5305,5.316520,1.017921,723.964844,680.927083,0.500000,0.003205,0.006369,0.484229,0.953970,0.642387,0.807692,0.282051,0.418100,0.355619
2,AdaBoost,CountVectorizer,"{'n_estimators': 100, 'learning_rate': 1.0}",3.333333,0.5885,5.305759,1.006409,723.990885,680.789062,0.470238,0.253205,0.329167,0.540340,0.840046,0.657658,0.765073,0.449328,0.566154,0.517659
3,AdaBoost,CountVectorizer,"{'n_estimators': 150, 'learning_rate': 0.01}",3.333333,0.5175,7.460948,1.021946,723.815104,688.048177,0.000000,0.000000,0.000000,0.476434,0.965478,0.638023,0.820084,0.239316,0.370510,0.336178
4,AdaBoost,CountVectorizer,"{'n_estimators': 150, 'learning_rate': 0.1}",3.333333,0.5405,7.534950,1.062201,723.789062,688.020833,0.800000,0.025641,0.049689,0.489869,0.945915,0.645465,0.804487,0.306471,0.443855,0.379670
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
127,SVC,TfidfVectorizer,"{'C': 1, 'kernel': 'rbf'}",3.333333,0.6440,459.653254,6.704309,1147.979167,887.363281,0.630252,0.240385,0.348028,0.579688,0.853855,0.690554,0.783694,0.575092,0.663380,0.567321
128,SVC,TfidfVectorizer,"{'C': 1, 'kernel': 'sigmoid'}",3.333333,0.6445,343.193950,4.797755,1121.990885,881.872396,0.552486,0.320513,0.405680,0.595960,0.814730,0.688381,0.762282,0.587302,0.663448,0.585836
129,SVC,TfidfVectorizer,"{'C': 10, 'kernel': 'linear'}",3.333333,0.5995,1332.701071,4.549585,1163.554688,701.381510,0.477193,0.435897,0.455611,0.573501,0.682394,0.623226,0.690162,0.573871,0.626667,0.568502
130,SVC,TfidfVectorizer,"{'C': 10, 'kernel': 'rbf'}",3.333333,0.6465,679.867944,7.032474,937.277344,710.782552,0.575758,0.304487,0.398323,0.595034,0.799770,0.682376,0.754123,0.614164,0.676985,0.585895
131,SVC,TfidfVectorizer,"{'C': 10, 'kernel': 'sigmoid'}",3.333333,0.5940,1712.682281,4.012838,1008.929688,698.230469,0.447917,0.413462,0.430000,0.568851,0.689298,0.623309,0.698027,0.561661,0.622463,0.558591

In [11]:
best_result = results_avg_seed.loc[results_avg_seed['f1_avg'].idxmax()]

best_model = models[best_result['model']]['model']
best_params = eval(best_result['params'])
best_model.set_params(**best_params)

best_result_vectorizer = eval(best_result['vectorizer'])()

pipeline = Pipeline([
    ('vectorizer', best_result_vectorizer),
    ('model', best_model)
])

pipeline.fit(train['text'], train['label'])
y_pred = pipeline.predict(test['text'])

accuracy = accuracy_score(test['label'], y_pred)
precisions, recalls, f1s, supports = precision_recall_fscore_support(test['label'], y_pred, average=None, labels=classes, zero_division=0)

print(f"Best model: {best_result['model']}")
print(f"Best model params: {best_result['params']}")
print(f"Best vectorizer: {best_result['vectorizer']}")
print(f"Best accuracy: {accuracy}\n")

for i, c in enumerate(classes):
    print(f"Class {c}")
    print(f"Precision: {precisions[i]}")
    print(f"Recall: {recalls[i]}")
    print(f"F1: {f1s[i]}")
    print(f"Support: {supports[i]}\n")

Best model: SVC
Best model params: {'C': 0.1, 'kernel': 'linear'}
Best vectorizer: CountVectorizer
Best accuracy: 0.5825464018235103

Class 0
Precision: 0.6826983135540288
Recall: 0.27517623363544813
F1: 0.39224834021173516
Support: 3972

Class 1
Precision: 0.5647874516935667
Recall: 0.8369546909213408
F1: 0.6744485917882592
Support: 5937

Class 2
Precision: 0.5803713527851458
Recall: 0.46063157894736845
F1: 0.5136150234741784
Support: 2375

In [12]:
with open('models/best_model_sklearn_multiclass1.pkl', 'wb') as f:
    pickle.dump(pipeline, f)