# Importing libraries

In [1]:
# Basic libraries
import pandas as pd
from datasets import load_dataset
import time
import pickle


# Classification models
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
from sklearn.naive_bayes import MultinomialNB

# Vectorizers
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer

# Utilities and metrics
from itertools import product
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
from memory_profiler import memory_usage

# Preprocessing
import nltk
import re

# Download nltk resources
nltk.download('wordnet')

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Rafael\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

# Setting seeds

In [2]:
s1 = 2
s2 = 3
s3 = 5

seeds = [s1, s2, s3]

# Importing datasets

In [3]:
ds = load_dataset("thien/political", "classifier")

train = ds['train'].to_pandas()
val = ds['eval'].to_pandas()
test = ds['test'].to_pandas()

train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80000 entries, 0 to 79999
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        80000 non-null  int64
 1   raw_text  80000 non-null  object
 2   filename  80000 non-null  object
 3   text      80000 non-null  object
 4   split     80000 non-null  object
 5   label     80000 non-null  object
dtypes: int64(1), object(5)
memory usage: 3.7+ MB

# Dataset preprocessing

In [4]:
train = train[['text', 'label']]
val = val[['text', 'label']]
test = test[['text', 'label']]

train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80000 entries, 0 to 79999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   text    80000 non-null  object
 1   label   80000 non-null  object
dtypes: object(2)
memory usage: 1.2+ MB

In [5]:
stop_words = set(nltk.corpus.stopwords.words('english'))
lemmatizer = nltk.stem.WordNetLemmatizer()

def preprocess_text(text):
    text = text.lower()

    text = re.sub(r'[^\w\s]', '', text)
    
    words = text.split()
    words = [word for word in words if word not in stop_words]
    words = [lemmatizer.lemmatize(word) for word in words]

    return ' '.join(words)
train['text'] = train['text'].apply(preprocess_text)

# GridSearch implementation

In [6]:
vectorizers = [
    TfidfVectorizer(),
    CountVectorizer()
]

models = {
    'RandomForest': {
        'model': RandomForestClassifier(),
        'params': {
            'n_estimators': [50, 100, 150],
            'criterion': ['gini', 'entropy', 'log_loss']
        }
    },
    'SVC': {
        'model': SVC(),
        'params': {
            'C': [0.1, 1, 10],
            'kernel': ['linear', 'rbf', 'sigmoid']
        }
    },
    'MultinomialNB': {
        'model': MultinomialNB(),
        'params': {
            'alpha': [0.01, 0.1, 1.0]
        }
    },
    'LogisticRegression': {
        'model': LogisticRegression(max_iter=1000),
        'params': {
            'C': [0.1, 1, 10],
            'penalty': ['l2']
        }
    },
    'KNeighbors': {
        'model': KNeighborsClassifier(),
        'params': {
            'n_neighbors': [3, 5, 7],
            'algorithm': ['ball_tree', 'kd_tree', 'brute']
        }
    },
    'DecisionTree': {
        'model': DecisionTreeClassifier(),
        'params': {
            'criterion': ['gini', 'entropy', 'log_loss'],
            'max_features': ['sqrt', 'log2', None]
        }
    },
    'GradientBoosting': {
        'model': GradientBoostingClassifier(),
        'params': {
            'n_estimators': [100, 150, 200],
            'criterion': ['friedman_mse', 'squared_error'],
        }
    },
    'AdaBoost': {
        'model': AdaBoostClassifier(),
        'params': {
            'n_estimators': [50, 100, 150],
            'learning_rate': [0.01, 0.1, 1.0]
        }
    },
    'SGD': {
        'model': SGDClassifier(),
        'params': {
            'alpha': [0.0001, 0.001, 0.01],
            'penalty': ['l2', 'l1', 'elasticnet']
        }
    }
}

In [7]:
columns = ['seed', 'vectorizer', 'model', 'params', 'accuracy', 'training_time', 'prediction_time', 'peak_memory_train', 'peak_memory_prediction']

classes = sorted(train['label'].unique())
for c in classes:
    columns.extend([
        f'precision_class_{c}',
        f'recall_class_{c}',
        f'f1_class_{c}'
    ])

results = pd.DataFrame(columns=columns)

In [8]:
for seed in seeds:
    print(f"Processing seed: {seed}")
    for vectorizer in vectorizers:
        print(f"Processing vectorizer: {vectorizer.__class__.__name__}")
        for name, info in models.items():
            print(f"Processing model: {name}")

            model = info['model']
            param_grid = info['params']
            param_combinations = product(*param_grid.values())
            
            for combination in param_combinations:
                params = dict(zip(param_grid.keys(), combination))
                model.set_params(**params)
                if 'random_state' in model.get_params():
                    model.set_params(random_state=seed)

                print(f"Training {name} with params {params} and vectorizer {vectorizer.__class__.__name__}")

                pipeline = Pipeline([
                    ('vectorizer', vectorizer),
                    ('model', model)
                ])

                def train_model():
                    pipeline.fit(train['text'], train['label'])

                def predict_model():
                    return pipeline.predict(val['text'])

                # Training Phase
                start_time = time.perf_counter()
                peak_memory_train = memory_usage(train_model, max_usage=True)
                train_time = time.perf_counter() - start_time
                print(f"Training time: {train_time}")
                print(f"Peak memory usage during training: {peak_memory_train} MB")

                # Prediction Phase
                start_time = time.perf_counter()
                peak_memory_pred, y_pred = memory_usage(predict_model, max_usage=True, retval=True)
                prediction_time = time.perf_counter() - start_time
                print(f"Prediction time: {prediction_time}")
                print(f"Peak memory usage during prediction: {peak_memory_pred} MB")
                
                accuracy = accuracy_score(val['label'], y_pred)
                precisions, recalls, f1s, supports = precision_recall_fscore_support(val['label'], y_pred, average=None, labels=classes, zero_division=0)

                result_dict = {
                    'seed': seed,
                    'vectorizer': vectorizer.__class__.__name__,
                    'model': name,
                    'params': params,
                    'accuracy': accuracy,
                    'training_time': train_time,
                    'prediction_time': prediction_time,
                    'peak_memory_train': peak_memory_train,
                    'peak_memory_prediction': peak_memory_pred,
                }

                for i, c in enumerate(classes):
                    result_dict[f'precision_class_{c}'] = precisions[i]
                    result_dict[f'recall_class_{c}'] = recalls[i]
                    result_dict[f'f1_class_{c}'] = f1s[i]

                result = pd.DataFrame([result_dict])
                results = pd.concat([results, result], ignore_index=True)
                print("-"*100)

results.to_csv('results/results_sklearn_binary3.csv', index=False)

Processing seed: 2
Processing vectorizer: TfidfVectorizer
Processing model: RandomForest
Training RandomForest with params {'n_estimators': 50, 'criterion': 'gini'} and vectorizer TfidfVectorizer
Training time: 49.92307339981198
Peak memory usage during training: 608.8984375 MB
Prediction time: 1.2106924999970943
Peak memory usage during prediction: 603.57421875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'entropy'} and vectorizer TfidfVectorizer

C:\Users\Rafael\AppData\Local\Temp\ipykernel_12868\2750059118.py:66: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results = pd.concat([results, result], ignore_index=True)

Training time: 45.51909630000591
Peak memory usage during training: 610.55859375 MB
Prediction time: 1.1890758001245558
Peak memory usage during prediction: 581.609375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'log_loss'} and vectorizer TfidfVectorizer
Training time: 45.98057230003178
Peak memory usage during training: 605.8359375 MB
Prediction time: 1.2111456000711769
Peak memory usage during prediction: 581.3984375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'gini'} and vectorizer TfidfVectorizer
Training time: 99.16859339992516
Peak memory usage during training: 745.375 MB
Prediction time: 0.7300742999650538
Peak memory usage during prediction: 745.67578125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'entropy'} and vectorizer TfidfVectorizer
Training time: 90.63544959994033
Peak memory usage during training: 751.75 MB
Prediction time: 0.7221633000299335
Peak memory usage during prediction: 721.4296875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'log_loss'} and vectorizer TfidfVectorizer
Training time: 90.37062820000574
Peak memory usage during training: 727.59765625 MB
Prediction time: 0.7236306997947395
Peak memory usage during prediction: 720.96484375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'gini'} and vectorizer TfidfVectorizer
Training time: 147.440634700004
Peak memory usage during training: 867.51953125 MB
Prediction time: 0.847219199873507
Peak memory usage during prediction: 866.7421875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'entropy'} and vectorizer TfidfVectorizer
Training time: 134.5286908999551
Peak memory usage during training: 879.60546875 MB
Prediction time: 0.835963899968192
Peak memory usage during prediction: 838.4609375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'log_loss'} and vectorizer TfidfVectorizer
Training time: 134.6951900999993
Peak memory usage during training: 847.48046875 MB
Prediction time: 0.8373106999788433
Peak memory usage during prediction: 838.6640625 MB
----------------------------------------------------------------------------------------------------
Processing model: SVC
Training SVC with params {'C': 0.1, 'kernel': 'linear'} and vectorizer TfidfVectorizer
Training time: 138.77348440000787
Peak memory usage during training: 1096.953125 MB
Prediction time: 4.9929561000317335
Peak memory usage during prediction: 862.6640625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 0.1, 'kernel': 'rbf'} and vectorizer TfidfVectorizer
Training time: 207.89015179988928
Peak memory usage during training: 1099.265625 MB
Prediction time: 9.283742100000381
Peak memory usage during prediction: 865.85546875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 0.1, 'kernel': 'sigmoid'} and vectorizer TfidfVectorizer
Training time: 148.57801129994914
Peak memory usage during training: 1084.453125 MB
Prediction time: 5.21442209999077
Peak memory usage during prediction: 854.78515625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'linear'} and vectorizer TfidfVectorizer
Training time: 149.51864919997752
Peak memory usage during training: 1163.328125 MB
Prediction time: 2.5415994999930263
Peak memory usage during prediction: 848.22265625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'rbf'} and vectorizer TfidfVectorizer
Training time: 325.63891500001773
Peak memory usage during training: 1130.62109375 MB
Prediction time: 5.908889900194481
Peak memory usage during prediction: 859.56640625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'sigmoid'} and vectorizer TfidfVectorizer
Training time: 235.0243905999232
Peak memory usage during training: 1117.76953125 MB
Prediction time: 2.4640923000406474
Peak memory usage during prediction: 852.8828125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'linear'} and vectorizer TfidfVectorizer
Training time: 163.4994049000088
Peak memory usage during training: 1212.546875 MB
Prediction time: 1.7485109998378903
Peak memory usage during prediction: 852.1015625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'rbf'} and vectorizer TfidfVectorizer
Training time: 453.6938779000193
Peak memory usage during training: 1109.58984375 MB
Prediction time: 5.955162599915639
Peak memory usage during prediction: 857.671875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'sigmoid'} and vectorizer TfidfVectorizer
Training time: 545.4875482001808
Peak memory usage during training: 1132.44921875 MB
Prediction time: 1.3459171000868082
Peak memory usage during prediction: 851.32421875 MB
----------------------------------------------------------------------------------------------------
Processing model: MultinomialNB
Training MultinomialNB with params {'alpha': 0.01} and vectorizer TfidfVectorizer
Training time: 0.9740162999369204
Peak memory usage during training: 849.6015625 MB
Prediction time: 1.4381734000053257
Peak memory usage during prediction: 823.1796875 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'alpha': 0.1} and vectorizer TfidfVectorizer
Training time: 0.9642540998756886
Peak memory usage during training: 848.06640625 MB
Prediction time: 1.4136034999974072
Peak memory usage during prediction: 821.84765625 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'alpha': 1.0} and vectorizer TfidfVectorizer
Training time: 0.9719187999144197
Peak memory usage during training: 846.53515625 MB
Prediction time: 1.4330396999139339
Peak memory usage during prediction: 821.93359375 MB
----------------------------------------------------------------------------------------------------
Processing model: LogisticRegression
Training LogisticRegression with params {'C': 0.1, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.0052536998409778
Peak memory usage during training: 852.51953125 MB
Prediction time: 1.4347532999236137
Peak memory usage during prediction: 821.66796875 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'C': 1, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.0122295999899507
Peak memory usage during training: 852.4140625 MB
Prediction time: 0.9756448999978602
Peak memory usage during prediction: 820.23828125 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'C': 10, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.0125891000498086
Peak memory usage during training: 851.1953125 MB
Prediction time: 1.4315779998432845
Peak memory usage during prediction: 820.27734375 MB
----------------------------------------------------------------------------------------------------
Processing model: KNeighbors
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'ball_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 0.9089448000304401
Peak memory usage during training: 844.06640625 MB
Prediction time: 4.315642199944705
Peak memory usage during prediction: 2838.9921875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'kd_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 0.9099747000727803
Peak memory usage during training: 849.49609375 MB
Prediction time: 4.255059200106189
Peak memory usage during prediction: 2873.9375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'brute'} and vectorizer TfidfVectorizer
Training time: 0.8971071001142263
Peak memory usage during training: 849.6328125 MB
Prediction time: 4.175599900074303
Peak memory usage during prediction: 2826.46484375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'ball_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 0.9203391000628471
Peak memory usage during training: 849.0625 MB
Prediction time: 4.222681900020689
Peak memory usage during prediction: 2853.2734375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'kd_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 0.9040145999751985
Peak memory usage during training: 849.55078125 MB
Prediction time: 4.218367699999362
Peak memory usage during prediction: 2827.2265625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'brute'} and vectorizer TfidfVectorizer
Training time: 0.9121042001061141
Peak memory usage during training: 848.9921875 MB
Prediction time: 4.220332799945027
Peak memory usage during prediction: 2818.63671875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'ball_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 0.9042649001348764
Peak memory usage during training: 849.55078125 MB
Prediction time: 4.294248499907553
Peak memory usage during prediction: 2833.1484375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'kd_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 0.9092053999193013
Peak memory usage during training: 848.96875 MB
Prediction time: 4.2293495000340044
Peak memory usage during prediction: 2872.9765625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'brute'} and vectorizer TfidfVectorizer
Training time: 0.9188492998946458
Peak memory usage during training: 849.53515625 MB
Prediction time: 4.177832100074738
Peak memory usage during prediction: 2831.19921875 MB
----------------------------------------------------------------------------------------------------
Processing model: DecisionTree
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'sqrt'} and vectorizer TfidfVectorizer
Training time: 2.295655199792236
Peak memory usage during training: 853.421875 MB
Prediction time: 0.9692085001152009
Peak memory usage during prediction: 850.02734375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'log2'} and vectorizer TfidfVectorizer
Training time: 3.233276999788359
Peak memory usage during training: 858.4453125 MB
Prediction time: 0.9965488999150693
Peak memory usage during prediction: 855.60546875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': None} and vectorizer TfidfVectorizer
Training time: 18.449964700033888
Peak memory usage during training: 860.0546875 MB
Prediction time: 1.4403706998564303
Peak memory usage during prediction: 828.9609375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'sqrt'} and vectorizer TfidfVectorizer
Training time: 2.2262478000484407
Peak memory usage during training: 856.40625 MB
Prediction time: 1.427859499817714
Peak memory usage during prediction: 850.28125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'log2'} and vectorizer TfidfVectorizer
Training time: 3.0081935001071543
Peak memory usage during training: 859.328125 MB
Prediction time: 1.44754260010086
Peak memory usage during prediction: 834.703125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': None} and vectorizer TfidfVectorizer
Training time: 15.455011799931526
Peak memory usage during training: 860.9375 MB
Prediction time: 1.444560500094667
Peak memory usage during prediction: 828.7578125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'sqrt'} and vectorizer TfidfVectorizer
Training time: 2.237688000081107
Peak memory usage during training: 856.48046875 MB
Prediction time: 1.4327521999366581
Peak memory usage during prediction: 831.83984375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'log2'} and vectorizer TfidfVectorizer
Training time: 2.9864928000606596
Peak memory usage during training: 859.3046875 MB
Prediction time: 0.9821194000542164
Peak memory usage during prediction: 855.703125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': None} and vectorizer TfidfVectorizer
Training time: 15.638641400029883
Peak memory usage during training: 860.35546875 MB
Prediction time: 1.4345607000868767
Peak memory usage during prediction: 828.92578125 MB
----------------------------------------------------------------------------------------------------
Processing model: GradientBoosting
Training GradientBoosting with params {'n_estimators': 100, 'criterion': 'friedman_mse'} and vectorizer TfidfVectorizer
Training time: 18.83092759991996
Peak memory usage during training: 859.61328125 MB
Prediction time: 1.4521908999886364
Peak memory usage during prediction: 830.203125 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 100, 'criterion': 'squared_error'} and vectorizer TfidfVectorizer
Training time: 18.876502400031313
Peak memory usage during training: 856.27734375 MB
Prediction time: 1.4489058000035584
Peak memory usage during prediction: 830.11328125 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 150, 'criterion': 'friedman_mse'} and vectorizer TfidfVectorizer
Training time: 27.794089999981225
Peak memory usage during training: 860.28515625 MB
Prediction time: 0.984110799850896
Peak memory usage during prediction: 853.93359375 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 150, 'criterion': 'squared_error'} and vectorizer TfidfVectorizer
Training time: 27.769915600074455
Peak memory usage during training: 856.1875 MB
Prediction time: 0.9781488999724388
Peak memory usage during prediction: 855.09375 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 200, 'criterion': 'friedman_mse'} and vectorizer TfidfVectorizer
Training time: 36.7418835000135
Peak memory usage during training: 860.41796875 MB
Prediction time: 0.9873575000092387
Peak memory usage during prediction: 829.95703125 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 200, 'criterion': 'squared_error'} and vectorizer TfidfVectorizer
Training time: 36.73999859998003
Peak memory usage during training: 856.3359375 MB
Prediction time: 0.9897284000180662
Peak memory usage during prediction: 829.91796875 MB
----------------------------------------------------------------------------------------------------
Processing model: AdaBoost
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 0.01} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 7.253564100014046
Peak memory usage during training: 856.83984375 MB
Prediction time: 1.0144205000251532
Peak memory usage during prediction: 829.83984375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 0.1} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 7.264645300107077
Peak memory usage during training: 855.734375 MB
Prediction time: 1.0133436999749392
Peak memory usage during prediction: 829.8515625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 1.0} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 7.254469099920243
Peak memory usage during training: 856.94140625 MB
Prediction time: 1.005679399939254
Peak memory usage during prediction: 829.94140625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 0.01} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 13.632608199957758
Peak memory usage during training: 856.13671875 MB
Prediction time: 1.049588300054893
Peak memory usage during prediction: 830.0 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 0.1} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 13.619481900008395
Peak memory usage during training: 857.09375 MB
Prediction time: 1.0437158001586795
Peak memory usage during prediction: 829.9296875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 1.0} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 13.64333470002748
Peak memory usage during training: 856.15234375 MB
Prediction time: 1.0467966001015157
Peak memory usage during prediction: 829.8125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 0.01} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 20.0267862000037
Peak memory usage during training: 856.94921875 MB
Prediction time: 1.083371700020507
Peak memory usage during prediction: 854.38671875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 0.1} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 20.036964500090107
Peak memory usage during training: 855.6640625 MB
Prediction time: 1.0889023002237082
Peak memory usage during prediction: 848.69140625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 1.0} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 20.05560449999757
Peak memory usage during training: 857.93359375 MB
Prediction time: 1.0897184000350535
Peak memory usage during prediction: 854.171875 MB
----------------------------------------------------------------------------------------------------
Processing model: SGD
Training SGD with params {'alpha': 0.0001, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 0.9382905000820756
Peak memory usage during training: 854.46875 MB
Prediction time: 0.9672201999928802
Peak memory usage during prediction: 854.46875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.0001, 'penalty': 'l1'} and vectorizer TfidfVectorizer
Training time: 0.9457205000799149
Peak memory usage during training: 853.6328125 MB
Prediction time: 1.427705200156197
Peak memory usage during prediction: 829.8046875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.0001, 'penalty': 'elasticnet'} and vectorizer TfidfVectorizer
Training time: 0.9713742998428643
Peak memory usage during training: 855.00390625 MB
Prediction time: 1.4480773999821395
Peak memory usage during prediction: 829.9296875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 0.9217766998335719
Peak memory usage during training: 853.78125 MB
Prediction time: 1.418006599880755
Peak memory usage during prediction: 829.89453125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'l1'} and vectorizer TfidfVectorizer
Training time: 0.9599708002060652
Peak memory usage during training: 855.07421875 MB
Prediction time: 1.4314264000859112
Peak memory usage during prediction: 830.0 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'elasticnet'} and vectorizer TfidfVectorizer
Training time: 0.9584151001181453
Peak memory usage during training: 853.77734375 MB
Prediction time: 1.4259687000885606
Peak memory usage during prediction: 829.78515625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 0.9128679998684675
Peak memory usage during training: 854.98046875 MB
Prediction time: 1.8859147001057863
Peak memory usage during prediction: 829.91796875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'l1'} and vectorizer TfidfVectorizer
Training time: 0.9442926000338048
Peak memory usage during training: 854.125 MB
Prediction time: 1.8843379002064466
Peak memory usage during prediction: 829.80859375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'elasticnet'} and vectorizer TfidfVectorizer
Training time: 0.9338004998862743
Peak memory usage during training: 855.03125 MB
Prediction time: 1.4288017998915166
Peak memory usage during prediction: 829.91796875 MB
----------------------------------------------------------------------------------------------------
Processing vectorizer: CountVectorizer
Processing model: RandomForest
Training RandomForest with params {'n_estimators': 50, 'criterion': 'gini'} and vectorizer CountVectorizer
Training time: 54.98210830008611
Peak memory usage during training: 849.20703125 MB
Prediction time: 1.2128361000213772
Peak memory usage during prediction: 630.515625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'entropy'} and vectorizer CountVectorizer
Training time: 50.616740899858996
Peak memory usage during training: 645.87890625 MB
Prediction time: 1.2083124998025596
Peak memory usage during prediction: 623.0078125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'log_loss'} and vectorizer CountVectorizer
Training time: 50.546136799966916
Peak memory usage during training: 636.08203125 MB
Prediction time: 1.20652320003137
Peak memory usage during prediction: 623.375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'gini'} and vectorizer CountVectorizer
Training time: 109.84419280011207
Peak memory usage during training: 783.578125 MB
Prediction time: 0.7162727999966592
Peak memory usage during prediction: 781.859375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'entropy'} and vectorizer CountVectorizer
Training time: 100.953887199983
Peak memory usage during training: 796.18359375 MB
Prediction time: 2.9020530998241156
Peak memory usage during prediction: 740.97265625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'log_loss'} and vectorizer CountVectorizer
Training time: 100.0444112000987
Peak memory usage during training: 773.9375 MB
Prediction time: 0.7306584999896586
Peak memory usage during prediction: 744.0078125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'gini'} and vectorizer CountVectorizer
Training time: 164.0404946000781
Peak memory usage during training: 926.73046875 MB
Prediction time: 0.8237686997745186
Peak memory usage during prediction: 924.75 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'entropy'} and vectorizer CountVectorizer
Training time: 150.1435273999814
Peak memory usage during training: 936.8828125 MB
Prediction time: 0.8398263999260962
Peak memory usage during prediction: 880.390625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'log_loss'} and vectorizer CountVectorizer
Training time: 150.46520960005
Peak memory usage during training: 910.77734375 MB
Prediction time: 0.8292417000047863
Peak memory usage during prediction: 880.2578125 MB
----------------------------------------------------------------------------------------------------
Processing model: SVC
Training SVC with params {'C': 0.1, 'kernel': 'linear'} and vectorizer CountVectorizer
Training time: 108.93056540004909
Peak memory usage during training: 1185.1328125 MB
Prediction time: 2.4395538999233395
Peak memory usage during prediction: 917.578125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 0.1, 'kernel': 'rbf'} and vectorizer CountVectorizer
Training time: 213.76246009999886
Peak memory usage during training: 1140.53515625 MB
Prediction time: 9.31535270018503
Peak memory usage during prediction: 919.73828125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 0.1, 'kernel': 'sigmoid'} and vectorizer CountVectorizer
Training time: 130.953500200063
Peak memory usage during training: 1141.33984375 MB
Prediction time: 4.7791815001983196
Peak memory usage during prediction: 914.96875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'linear'} and vectorizer CountVectorizer
Training time: 124.45847050007433
Peak memory usage during training: 1245.828125 MB
Prediction time: 1.5190318999812007
Peak memory usage during prediction: 909.76953125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'rbf'} and vectorizer CountVectorizer
Training time: 343.0564107999671
Peak memory usage during training: 1203.265625 MB
Prediction time: 6.443965299986303
Peak memory usage during prediction: 916.82421875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'sigmoid'} and vectorizer CountVectorizer
Training time: 113.63045649998821
Peak memory usage during training: 1154.00390625 MB
Prediction time: 2.267914099851623
Peak memory usage during prediction: 910.36328125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'linear'} and vectorizer CountVectorizer
Training time: 116.35895749996416
Peak memory usage during training: 1253.94921875 MB
Prediction time: 1.236460099928081
Peak memory usage during prediction: 909.8125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'rbf'} and vectorizer CountVectorizer
Training time: 389.35081110009924
Peak memory usage during training: 1155.140625 MB
Prediction time: 6.105966399889439
Peak memory usage during prediction: 916.26953125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'sigmoid'} and vectorizer CountVectorizer
Training time: 87.18496280000545
Peak memory usage during training: 1155.15625 MB
Prediction time: 1.4200476000551134
Peak memory usage during prediction: 910.98046875 MB
----------------------------------------------------------------------------------------------------
Processing model: MultinomialNB
Training MultinomialNB with params {'alpha': 0.01} and vectorizer CountVectorizer
Training time: 0.96373389987275
Peak memory usage during training: 909.203125 MB
Prediction time: 1.4354518000036478
Peak memory usage during prediction: 875.734375 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'alpha': 0.1} and vectorizer CountVectorizer
Training time: 0.9590496998280287
Peak memory usage during training: 907.36328125 MB
Prediction time: 1.8983556998427957
Peak memory usage during prediction: 874.6015625 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'alpha': 1.0} and vectorizer CountVectorizer
Training time: 0.9581450999248773
Peak memory usage during training: 906.55859375 MB
Prediction time: 1.4193122999276966
Peak memory usage during prediction: 874.3203125 MB
----------------------------------------------------------------------------------------------------
Processing model: LogisticRegression
Training LogisticRegression with params {'C': 0.1, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.0420982998330146
Peak memory usage during training: 914.015625 MB
Prediction time: 1.4252136999275535
Peak memory usage during prediction: 873.3984375 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'C': 1, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.06838500010781
Peak memory usage during training: 913.43359375 MB
Prediction time: 1.8748626001179218
Peak memory usage during prediction: 873.2578125 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'C': 10, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.092604500008747
Peak memory usage during training: 913.3515625 MB
Prediction time: 1.420784000074491
Peak memory usage during prediction: 873.06640625 MB
----------------------------------------------------------------------------------------------------
Processing model: KNeighbors
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'ball_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 0.9019053000956774
Peak memory usage during training: 905.83203125 MB
Prediction time: 4.472034800099209
Peak memory usage during prediction: 2835.23046875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'kd_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 0.9157714999746531
Peak memory usage during training: 905.2890625 MB
Prediction time: 4.482564200181514
Peak memory usage during prediction: 2925.078125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'brute'} and vectorizer CountVectorizer
Training time: 0.8960946998558939
Peak memory usage during training: 902.1875 MB
Prediction time: 4.526116800028831
Peak memory usage during prediction: 2828.109375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'ball_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 0.9211024001706392
Peak memory usage during training: 906.03125 MB
Prediction time: 4.4601706000976264
Peak memory usage during prediction: 2872.29296875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'kd_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 0.9006542998831719
Peak memory usage during training: 906.015625 MB
Prediction time: 4.436960400082171
Peak memory usage during prediction: 2836.125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'brute'} and vectorizer CountVectorizer
Training time: 0.9017227001022547
Peak memory usage during training: 902.95703125 MB
Prediction time: 4.4489603999536484
Peak memory usage during prediction: 2828.33984375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'ball_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 0.900579100009054
Peak memory usage during training: 902.65234375 MB
Prediction time: 4.465322100091726
Peak memory usage during prediction: 2861.34375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'kd_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 0.9064331999979913
Peak memory usage during training: 901.984375 MB
Prediction time: 4.5138861001469195
Peak memory usage during prediction: 2922.19140625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'brute'} and vectorizer CountVectorizer
Training time: 0.9067505998536944
Peak memory usage during training: 907.46484375 MB
Prediction time: 4.437102399999276
Peak memory usage during prediction: 2903.0703125 MB
----------------------------------------------------------------------------------------------------
Processing model: DecisionTree
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'sqrt'} and vectorizer CountVectorizer
Training time: 2.434602899942547
Peak memory usage during training: 907.39453125 MB
Prediction time: 1.4365110001526773
Peak memory usage during prediction: 876.4453125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'log2'} and vectorizer CountVectorizer
Training time: 4.061742399819195
Peak memory usage during training: 913.57421875 MB
Prediction time: 0.98362149996683
Peak memory usage during prediction: 879.4765625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': None} and vectorizer CountVectorizer
Training time: 11.493603500071913
Peak memory usage during training: 912.64453125 MB
Prediction time: 1.4410467999987304
Peak memory usage during prediction: 872.9453125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'sqrt'} and vectorizer CountVectorizer
Training time: 2.28863239986822
Peak memory usage during training: 907.9140625 MB
Prediction time: 1.4364265000913292
Peak memory usage during prediction: 876.08203125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'log2'} and vectorizer CountVectorizer
Training time: 4.086990799987689
Peak memory usage during training: 914.55859375 MB
Prediction time: 0.990254299947992
Peak memory usage during prediction: 879.26171875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': None} and vectorizer CountVectorizer
Training time: 9.060045100050047
Peak memory usage during training: 912.015625 MB
Prediction time: 0.982506699860096
Peak memory usage during prediction: 888.7265625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'sqrt'} and vectorizer CountVectorizer
Training time: 2.289658199995756
Peak memory usage during training: 907.72265625 MB
Prediction time: 1.4337532999925315
Peak memory usage during prediction: 876.07421875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'log2'} and vectorizer CountVectorizer
Training time: 4.0578562000300735
Peak memory usage during training: 915.30078125 MB
Prediction time: 1.438623100053519
Peak memory usage during prediction: 879.1953125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': None} and vectorizer CountVectorizer
Training time: 9.034881399944425
Peak memory usage during training: 912.34765625 MB
Prediction time: 0.9920479999855161
Peak memory usage during prediction: 888.703125 MB
----------------------------------------------------------------------------------------------------
Processing model: GradientBoosting
Training GradientBoosting with params {'n_estimators': 100, 'criterion': 'friedman_mse'} and vectorizer CountVectorizer
Training time: 8.037677200045437
Peak memory usage during training: 910.94140625 MB
Prediction time: 1.4550356999970973
Peak memory usage during prediction: 873.31640625 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 100, 'criterion': 'squared_error'} and vectorizer CountVectorizer
Training time: 8.065861799987033
Peak memory usage during training: 910.64453125 MB
Prediction time: 1.4399128998629749
Peak memory usage during prediction: 873.13671875 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 150, 'criterion': 'friedman_mse'} and vectorizer CountVectorizer
Training time: 11.616501100128517
Peak memory usage during training: 910.68359375 MB
Prediction time: 0.9850309998728335
Peak memory usage during prediction: 873.13671875 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 150, 'criterion': 'squared_error'} and vectorizer CountVectorizer
Training time: 11.635146399959922
Peak memory usage during training: 910.26171875 MB
Prediction time: 0.9901902000419796
Peak memory usage during prediction: 872.43359375 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 200, 'criterion': 'friedman_mse'} and vectorizer CountVectorizer
Training time: 15.281905699986964
Peak memory usage during training: 909.71484375 MB
Prediction time: 0.9889444999862462
Peak memory usage during prediction: 873.234375 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 200, 'criterion': 'squared_error'} and vectorizer CountVectorizer
Training time: 15.153242399916053
Peak memory usage during training: 909.83203125 MB
Prediction time: 0.9926483000162989
Peak memory usage during prediction: 872.546875 MB
----------------------------------------------------------------------------------------------------
Processing model: AdaBoost
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 0.01} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 5.1487942999228835
Peak memory usage during training: 907.65625 MB
Prediction time: 1.024895700160414
Peak memory usage during prediction: 872.6640625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 0.1} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 5.1449660998769104
Peak memory usage during training: 906.9453125 MB
Prediction time: 1.0078589001204818
Peak memory usage during prediction: 872.80859375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 1.0} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 5.150157199939713
Peak memory usage during training: 907.37109375 MB
Prediction time: 0.9976321998983622
Peak memory usage during prediction: 872.5546875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 0.01} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 9.432578100124374
Peak memory usage during training: 907.00390625 MB
Prediction time: 1.0462531000375748
Peak memory usage during prediction: 872.828125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 0.1} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 9.404223800171167
Peak memory usage during training: 907.3515625 MB
Prediction time: 1.0472206000704318
Peak memory usage during prediction: 872.77734375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 1.0} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 9.395888300146908
Peak memory usage during training: 907.03125 MB
Prediction time: 1.040018699830398
Peak memory usage during prediction: 872.72265625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 0.01} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 13.841490400023758
Peak memory usage during training: 907.28515625 MB
Prediction time: 1.0811432001646608
Peak memory usage during prediction: 872.72265625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 0.1} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 13.682326199952513
Peak memory usage during training: 906.921875 MB
Prediction time: 1.07573420018889
Peak memory usage during prediction: 872.48046875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 1.0} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 13.690590800018981
Peak memory usage during training: 907.2890625 MB
Prediction time: 1.0767923998646438
Peak memory usage during prediction: 872.8046875 MB
----------------------------------------------------------------------------------------------------
Processing model: SGD
Training SGD with params {'alpha': 0.0001, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 0.9307748000137508
Peak memory usage during training: 904.02734375 MB
Prediction time: 1.4165099998936057
Peak memory usage during prediction: 872.3203125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.0001, 'penalty': 'l1'} and vectorizer CountVectorizer
Training time: 1.0126555999740958
Peak memory usage during training: 904.40234375 MB
Prediction time: 0.9638229000847787
Peak memory usage during prediction: 872.37890625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.0001, 'penalty': 'elasticnet'} and vectorizer CountVectorizer
Training time: 0.9762996002100408
Peak memory usage during training: 904.140625 MB
Prediction time: 1.4110429000575095
Peak memory usage during prediction: 872.32421875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 0.9264870001934469
Peak memory usage during training: 904.421875 MB
Prediction time: 1.4314099000766873
Peak memory usage during prediction: 872.38671875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'l1'} and vectorizer CountVectorizer
Training time: 0.9680616999976337
Peak memory usage during training: 904.1015625 MB
Prediction time: 1.9027585999574512
Peak memory usage during prediction: 872.3671875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'elasticnet'} and vectorizer CountVectorizer
Training time: 0.9817272999789566
Peak memory usage during training: 904.46484375 MB
Prediction time: 0.9683386001270264
Peak memory usage during prediction: 900.05078125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 0.9238704000599682
Peak memory usage during training: 904.10546875 MB
Prediction time: 0.9727125999052078
Peak memory usage during prediction: 904.10546875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'l1'} and vectorizer CountVectorizer
Training time: 0.9441070000175387
Peak memory usage during training: 904.46484375 MB
Prediction time: 1.8883112000767142
Peak memory usage during prediction: 872.26953125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'elasticnet'} and vectorizer CountVectorizer
Training time: 0.9550439999438822
Peak memory usage during training: 904.046875 MB
Prediction time: 1.4269658999983221
Peak memory usage during prediction: 872.28515625 MB
----------------------------------------------------------------------------------------------------
Processing seed: 3
Processing vectorizer: TfidfVectorizer
Processing model: RandomForest
Training RandomForest with params {'n_estimators': 50, 'criterion': 'gini'} and vectorizer TfidfVectorizer
Training time: 49.913397199939936
Peak memory usage during training: 905.58984375 MB
Prediction time: 1.218464900040999
Peak memory usage during prediction: 619.8671875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'entropy'} and vectorizer TfidfVectorizer
Training time: 45.35316850012168
Peak memory usage during training: 631.50390625 MB
Prediction time: 1.203539300011471
Peak memory usage during prediction: 595.5546875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'log_loss'} and vectorizer TfidfVectorizer
Training time: 45.40817219996825
Peak memory usage during training: 616.98828125 MB
Prediction time: 1.2032349999062717
Peak memory usage during prediction: 594.32421875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'gini'} and vectorizer TfidfVectorizer
Training time: 99.0384967001155
Peak memory usage during training: 758.546875 MB
Prediction time: 0.7211070000194013
Peak memory usage during prediction: 759.06640625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'entropy'} and vectorizer TfidfVectorizer
Training time: 89.94850659999065
Peak memory usage during training: 767.44140625 MB
Prediction time: 0.7137786000967026
Peak memory usage during prediction: 734.61328125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'log_loss'} and vectorizer TfidfVectorizer
Training time: 89.8372847000137
Peak memory usage during training: 742.703125 MB
Prediction time: 0.7164755000267178
Peak memory usage during prediction: 734.671875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'gini'} and vectorizer TfidfVectorizer
Training time: 148.02707800013013
Peak memory usage during training: 887.23046875 MB
Prediction time: 0.8450472999829799
Peak memory usage during prediction: 887.8203125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'entropy'} and vectorizer TfidfVectorizer
Training time: 134.37292589992285
Peak memory usage during training: 895.7734375 MB
Prediction time: 0.8323468999005854
Peak memory usage during prediction: 856.1484375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'log_loss'} and vectorizer TfidfVectorizer
Training time: 134.39820299996063
Peak memory usage during training: 864.57421875 MB
Prediction time: 0.8463850999251008
Peak memory usage during prediction: 856.12890625 MB
----------------------------------------------------------------------------------------------------
Processing model: SVC
Training SVC with params {'C': 0.1, 'kernel': 'linear'} and vectorizer TfidfVectorizer
Training time: 143.08057400025427
Peak memory usage during training: 1107.94921875 MB
Prediction time: 4.971278100274503
Peak memory usage during prediction: 875.546875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 0.1, 'kernel': 'rbf'} and vectorizer TfidfVectorizer
Training time: 207.78000520030037
Peak memory usage during training: 1105.40234375 MB
Prediction time: 9.303465100005269
Peak memory usage during prediction: 872.70703125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 0.1, 'kernel': 'sigmoid'} and vectorizer TfidfVectorizer
Training time: 148.2334206001833
Peak memory usage during training: 1087.3046875 MB
Prediction time: 5.19084809999913
Peak memory usage during prediction: 866.98828125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'linear'} and vectorizer TfidfVectorizer
Training time: 149.28411120036617
Peak memory usage during training: 1168.33203125 MB
Prediction time: 2.5419250996783376
Peak memory usage during prediction: 860.73828125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'rbf'} and vectorizer TfidfVectorizer
Training time: 326.31788989994675
Peak memory usage during training: 1141.8359375 MB
Prediction time: 5.920359900221229
Peak memory usage during prediction: 870.7109375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'sigmoid'} and vectorizer TfidfVectorizer
Training time: 234.62430729996413
Peak memory usage during training: 1128.83984375 MB
Prediction time: 2.4630177998915315
Peak memory usage during prediction: 865.859375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'linear'} and vectorizer TfidfVectorizer
Training time: 164.04993409989402
Peak memory usage during training: 1224.421875 MB
Prediction time: 1.7176650003530085
Peak memory usage during prediction: 862.140625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'rbf'} and vectorizer TfidfVectorizer
Training time: 454.2088037999347
Peak memory usage during training: 1121.2578125 MB
Prediction time: 5.92223360016942
Peak memory usage during prediction: 867.1875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'sigmoid'} and vectorizer TfidfVectorizer
Training time: 548.189257199876
Peak memory usage during training: 1144.7578125 MB
Prediction time: 1.3476724000647664
Peak memory usage during prediction: 863.69921875 MB
----------------------------------------------------------------------------------------------------
Processing model: MultinomialNB
Training MultinomialNB with params {'alpha': 0.01} and vectorizer TfidfVectorizer
Training time: 0.9733519000001252
Peak memory usage during training: 861.12890625 MB
Prediction time: 0.9727165000513196
Peak memory usage during prediction: 832.59765625 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'alpha': 0.1} and vectorizer TfidfVectorizer
Training time: 0.9731695000082254
Peak memory usage during training: 859.5 MB
Prediction time: 1.4324408997781575
Peak memory usage during prediction: 832.32421875 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'alpha': 1.0} and vectorizer TfidfVectorizer
Training time: 0.9672995000146329
Peak memory usage during training: 859.1015625 MB
Prediction time: 1.4238269999623299
Peak memory usage during prediction: 831.34765625 MB
----------------------------------------------------------------------------------------------------
Processing model: LogisticRegression
Training LogisticRegression with params {'C': 0.1, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.004781600087881
Peak memory usage during training: 863.140625 MB
Prediction time: 0.9720668001100421
Peak memory usage during prediction: 830.62890625 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'C': 1, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.0138436001725495
Peak memory usage during training: 863.328125 MB
Prediction time: 1.4260825999081135
Peak memory usage during prediction: 829.97265625 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'C': 10, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.0143407001160085
Peak memory usage during training: 862.515625 MB
Prediction time: 0.9649009997956455
Peak memory usage during prediction: 829.671875 MB
----------------------------------------------------------------------------------------------------
Processing model: KNeighbors
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'ball_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 0.9069369998760521
Peak memory usage during training: 856.26171875 MB
Prediction time: 4.334591200109571
Peak memory usage during prediction: 2863.42578125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'kd_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 0.9103374998085201
Peak memory usage during training: 855.625 MB
Prediction time: 4.467680300120264
Peak memory usage during prediction: 2814.40625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'brute'} and vectorizer TfidfVectorizer
Training time: 0.9145121998153627
Peak memory usage during training: 860.01953125 MB
Prediction time: 4.336938200052828
Peak memory usage during prediction: 2856.265625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'ball_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 0.9113361998461187
Peak memory usage during training: 858.73828125 MB
Prediction time: 4.321880000177771
Peak memory usage during prediction: 2861.953125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'kd_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 0.9124529003165662
Peak memory usage during training: 854.65234375 MB
Prediction time: 4.420463299844414
Peak memory usage during prediction: 2835.39453125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'brute'} and vectorizer TfidfVectorizer
Training time: 0.9073681998997927
Peak memory usage during training: 855.5234375 MB
Prediction time: 4.359517099801451
Peak memory usage during prediction: 2845.015625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'ball_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 0.93474439997226
Peak memory usage during training: 853.64453125 MB
Prediction time: 4.32851850008592
Peak memory usage during prediction: 2859.90625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'kd_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 0.9108494999818504
Peak memory usage during training: 859.234375 MB
Prediction time: 4.324745700228959
Peak memory usage during prediction: 2776.6953125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'brute'} and vectorizer TfidfVectorizer
Training time: 0.917380299884826
Peak memory usage during training: 855.28515625 MB
Prediction time: 4.396254499908537
Peak memory usage during prediction: 2855.9375 MB
----------------------------------------------------------------------------------------------------
Processing model: DecisionTree
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'sqrt'} and vectorizer TfidfVectorizer
Training time: 2.2600225997157395
Peak memory usage during training: 859.9921875 MB
Prediction time: 0.9615910002030432
Peak memory usage during prediction: 851.4765625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'log2'} and vectorizer TfidfVectorizer
Training time: 3.3240167000330985
Peak memory usage during training: 862.38671875 MB
Prediction time: 0.9751967000775039
Peak memory usage during prediction: 856.8046875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': None} and vectorizer TfidfVectorizer
Training time: 18.503337500151247
Peak memory usage during training: 865.078125 MB
Prediction time: 1.4534803996793926
Peak memory usage during prediction: 829.8125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'sqrt'} and vectorizer TfidfVectorizer
Training time: 2.020480700302869
Peak memory usage during training: 857.9453125 MB
Prediction time: 0.9767880002036691
Peak memory usage during prediction: 851.32421875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'log2'} and vectorizer TfidfVectorizer
Training time: 3.0688974000513554
Peak memory usage during training: 862.74609375 MB
Prediction time: 0.9796165996231139
Peak memory usage during prediction: 856.48046875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': None} and vectorizer TfidfVectorizer
Training time: 15.455684799700975
Peak memory usage during training: 862.78515625 MB
Prediction time: 0.9703798000700772
Peak memory usage during prediction: 845.66015625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'sqrt'} and vectorizer TfidfVectorizer
Training time: 2.016159599646926
Peak memory usage during training: 860.12109375 MB
Prediction time: 0.9691403000615537
Peak memory usage during prediction: 851.3359375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'log2'} and vectorizer TfidfVectorizer
Training time: 3.0731343999505043
Peak memory usage during training: 865.17578125 MB
Prediction time: 0.984614800196141
Peak memory usage during prediction: 856.47265625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': None} and vectorizer TfidfVectorizer
Training time: 15.468083600047976
Peak memory usage during training: 862.69921875 MB
Prediction time: 1.426118299830705
Peak memory usage during prediction: 845.56640625 MB
----------------------------------------------------------------------------------------------------
Processing model: GradientBoosting
Training GradientBoosting with params {'n_estimators': 100, 'criterion': 'friedman_mse'} and vectorizer TfidfVectorizer
Training time: 18.83262149989605
Peak memory usage during training: 860.078125 MB
Prediction time: 0.9798343000002205
Peak memory usage during prediction: 853.99609375 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 100, 'criterion': 'squared_error'} and vectorizer TfidfVectorizer
Training time: 18.822432999964803
Peak memory usage during training: 859.49609375 MB
Prediction time: 1.4344763001427054
Peak memory usage during prediction: 830.046875 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 150, 'criterion': 'friedman_mse'} and vectorizer TfidfVectorizer
Training time: 27.74805109994486
Peak memory usage during training: 859.578125 MB
Prediction time: 1.4537337999790907
Peak memory usage during prediction: 830.52734375 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 150, 'criterion': 'squared_error'} and vectorizer TfidfVectorizer
Training time: 27.75024600001052
Peak memory usage during training: 860.22265625 MB
Prediction time: 0.9831785000860691
Peak memory usage during prediction: 854.5859375 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 200, 'criterion': 'friedman_mse'} and vectorizer TfidfVectorizer
Training time: 36.68049480021
Peak memory usage during training: 859.89453125 MB
Prediction time: 0.9880376001819968
Peak memory usage during prediction: 830.41796875 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 200, 'criterion': 'squared_error'} and vectorizer TfidfVectorizer
Training time: 36.59379109973088
Peak memory usage during training: 859.921875 MB
Prediction time: 1.451399200130254
Peak memory usage during prediction: 830.015625 MB
----------------------------------------------------------------------------------------------------
Processing model: AdaBoost
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 0.01} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 7.277843399904668
Peak memory usage during training: 859.109375 MB
Prediction time: 1.018204000312835
Peak memory usage during prediction: 829.45703125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 0.1} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 7.243006800301373
Peak memory usage during training: 858.8203125 MB
Prediction time: 1.016574699897319
Peak memory usage during prediction: 829.8359375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 1.0} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 7.267422900069505
Peak memory usage during training: 858.76953125 MB
Prediction time: 1.017897800076753
Peak memory usage during prediction: 829.54296875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 0.01} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 13.6387700997293
Peak memory usage during training: 858.5546875 MB
Prediction time: 1.039321799762547
Peak memory usage during prediction: 829.51171875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 0.1} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 13.664572299923748
Peak memory usage during training: 858.44921875 MB
Prediction time: 1.049723300151527
Peak memory usage during prediction: 829.57421875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 1.0} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 13.638446400407702
Peak memory usage during training: 858.609375 MB
Prediction time: 1.0392076997086406
Peak memory usage during prediction: 829.5625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 0.01} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 20.05407930025831
Peak memory usage during training: 858.5078125 MB
Prediction time: 1.0802302998490632
Peak memory usage during prediction: 851.3046875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 0.1} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 20.06953029986471
Peak memory usage during training: 858.62109375 MB
Prediction time: 1.0887429001741111
Peak memory usage during prediction: 847.6328125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 1.0} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 20.02851019985974
Peak memory usage during training: 858.51953125 MB
Prediction time: 1.0927046998403966
Peak memory usage during prediction: 851.375 MB
----------------------------------------------------------------------------------------------------
Processing model: SGD
Training SGD with params {'alpha': 0.0001, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 0.9301208998076618
Peak memory usage during training: 858.25 MB
Prediction time: 1.4115496999584138
Peak memory usage during prediction: 829.25390625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.0001, 'penalty': 'l1'} and vectorizer TfidfVectorizer
Training time: 0.9511778000742197
Peak memory usage during training: 858.484375 MB
Prediction time: 0.9594152001664042
Peak memory usage during prediction: 849.9765625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.0001, 'penalty': 'elasticnet'} and vectorizer TfidfVectorizer
Training time: 0.9669031999073923
Peak memory usage during training: 858.30078125 MB
Prediction time: 1.4256867999210954
Peak memory usage during prediction: 829.32421875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 0.9392955997027457
Peak memory usage during training: 858.4765625 MB
Prediction time: 0.9838957004249096
Peak memory usage during prediction: 849.93359375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'l1'} and vectorizer TfidfVectorizer
Training time: 0.9723900998942554
Peak memory usage during training: 858.29296875 MB
Prediction time: 0.9704668996855617
Peak memory usage during prediction: 858.28515625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'elasticnet'} and vectorizer TfidfVectorizer
Training time: 1.0335471997968853
Peak memory usage during training: 858.38671875 MB
Prediction time: 0.9957109000533819
Peak memory usage during prediction: 829.1875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 0.9200794999487698
Peak memory usage during training: 857.984375 MB
Prediction time: 0.9642984997481108
Peak memory usage during prediction: 857.9765625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'l1'} and vectorizer TfidfVectorizer
Training time: 0.9248335999436677
Peak memory usage during training: 858.23828125 MB
Prediction time: 1.4344983999617398
Peak memory usage during prediction: 829.31640625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'elasticnet'} and vectorizer TfidfVectorizer
Training time: 0.940440199803561
Peak memory usage during training: 858.0546875 MB
Prediction time: 0.9739518999122083
Peak memory usage during prediction: 858.05078125 MB
----------------------------------------------------------------------------------------------------
Processing vectorizer: CountVectorizer
Processing model: RandomForest
Training RandomForest with params {'n_estimators': 50, 'criterion': 'gini'} and vectorizer CountVectorizer
Training time: 55.41051730001345
Peak memory usage during training: 858.23828125 MB
Prediction time: 1.1913992995396256
Peak memory usage during prediction: 633.21484375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'entropy'} and vectorizer CountVectorizer
Training time: 51.061203399673104
Peak memory usage during training: 645.41796875 MB
Prediction time: 1.1995946001261473
Peak memory usage during prediction: 624.13671875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'log_loss'} and vectorizer CountVectorizer
Training time: 50.942511700093746
Peak memory usage during training: 634.140625 MB
Prediction time: 1.2090821000747383
Peak memory usage during prediction: 624.09765625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'gini'} and vectorizer CountVectorizer
Training time: 109.61054829973727
Peak memory usage during training: 781.80078125 MB
Prediction time: 0.7170669999904931
Peak memory usage during prediction: 779.87109375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'entropy'} and vectorizer CountVectorizer
Training time: 100.59464829973876
Peak memory usage during training: 788.1875 MB
Prediction time: 0.722165200393647
Peak memory usage during prediction: 767.44140625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'log_loss'} and vectorizer CountVectorizer
Training time: 100.67105109989643
Peak memory usage during training: 773.9375 MB
Prediction time: 0.7179891001433134
Peak memory usage during prediction: 766.57421875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'gini'} and vectorizer CountVectorizer
Training time: 163.26545439986512
Peak memory usage during training: 927.37109375 MB
Prediction time: 0.829834199976176
Peak memory usage during prediction: 903.97265625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'entropy'} and vectorizer CountVectorizer
Training time: 149.86359110008925
Peak memory usage during training: 937.02734375 MB
Prediction time: 0.8252151003107429
Peak memory usage during prediction: 900.36328125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'log_loss'} and vectorizer CountVectorizer
Training time: 149.85031710006297
Peak memory usage during training: 908.234375 MB
Prediction time: 0.8372657997533679
Peak memory usage during prediction: 872.171875 MB
----------------------------------------------------------------------------------------------------
Processing model: SVC
Training SVC with params {'C': 0.1, 'kernel': 'linear'} and vectorizer CountVectorizer
Training time: 109.24877860024571
Peak memory usage during training: 1178.3359375 MB
Prediction time: 2.4408388999290764
Peak memory usage during prediction: 909.55859375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 0.1, 'kernel': 'rbf'} and vectorizer CountVectorizer
Training time: 214.72039330005646
Peak memory usage during training: 1143.734375 MB
Prediction time: 9.310111400205642
Peak memory usage during prediction: 920.3671875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 0.1, 'kernel': 'sigmoid'} and vectorizer CountVectorizer
Training time: 131.11457780003548
Peak memory usage during training: 1142.4375 MB
Prediction time: 4.8048640000633895
Peak memory usage during prediction: 915.4375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'linear'} and vectorizer CountVectorizer
Training time: 123.83255429985002
Peak memory usage during training: 1245.546875 MB
Prediction time: 1.5278574000112712
Peak memory usage during prediction: 910.53515625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'rbf'} and vectorizer CountVectorizer
Training time: 352.58605570020154
Peak memory usage during training: 1201.078125 MB
Prediction time: 6.4513379000127316
Peak memory usage during prediction: 913.52734375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'sigmoid'} and vectorizer CountVectorizer
Training time: 113.95605240017176
Peak memory usage during training: 1152.48828125 MB
Prediction time: 2.259846500121057
Peak memory usage during prediction: 909.14453125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'linear'} and vectorizer CountVectorizer
Training time: 116.70287200016901
Peak memory usage during training: 1254.0078125 MB
Prediction time: 1.2314764996990561
Peak memory usage during prediction: 906.94921875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'rbf'} and vectorizer CountVectorizer
Training time: 389.98380080005154
Peak memory usage during training: 1154.16796875 MB
Prediction time: 6.111179099883884
Peak memory usage during prediction: 913.5859375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'sigmoid'} and vectorizer CountVectorizer
Training time: 87.321905199904
Peak memory usage during training: 1151.328125 MB
Prediction time: 1.4102489999495447
Peak memory usage during prediction: 909.19921875 MB
----------------------------------------------------------------------------------------------------
Processing model: MultinomialNB
Training MultinomialNB with params {'alpha': 0.01} and vectorizer CountVectorizer
Training time: 0.9816707000136375
Peak memory usage during training: 907.703125 MB
Prediction time: 1.8889264999888837
Peak memory usage during prediction: 873.63671875 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'alpha': 0.1} and vectorizer CountVectorizer
Training time: 0.9647412998601794
Peak memory usage during training: 905.734375 MB
Prediction time: 1.8804583000019193
Peak memory usage during prediction: 872.28515625 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'alpha': 1.0} and vectorizer CountVectorizer
Training time: 0.9580278997309506
Peak memory usage during training: 904.36328125 MB
Prediction time: 1.4405948999337852
Peak memory usage during prediction: 871.9140625 MB
----------------------------------------------------------------------------------------------------
Processing model: LogisticRegression
Training LogisticRegression with params {'C': 0.1, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.0247033000923693
Peak memory usage during training: 912.6796875 MB
Prediction time: 1.8835097001865506
Peak memory usage during prediction: 871.2265625 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'C': 1, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.0777392000891268
Peak memory usage during training: 912.203125 MB
Prediction time: 1.4376852000132203
Peak memory usage during prediction: 870.83203125 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'C': 10, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.1038756999187171
Peak memory usage during training: 912.359375 MB
Prediction time: 0.964223500341177
Peak memory usage during prediction: 870.5859375 MB
----------------------------------------------------------------------------------------------------
Processing model: KNeighbors
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'ball_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 0.901963799726218
Peak memory usage during training: 902.57421875 MB
Prediction time: 4.5640968000516295
Peak memory usage during prediction: 2856.5078125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'kd_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 0.9112350000068545
Peak memory usage during training: 901.73828125 MB
Prediction time: 4.505610099993646
Peak memory usage during prediction: 2899.140625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'brute'} and vectorizer CountVectorizer
Training time: 0.8993565998971462
Peak memory usage during training: 900.625 MB
Prediction time: 4.606174800079316
Peak memory usage during prediction: 2820.51171875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'ball_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 0.9070974998176098
Peak memory usage during training: 900.78515625 MB
Prediction time: 4.509796999860555
Peak memory usage during prediction: 2923.83203125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'kd_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 0.9032017001882195
Peak memory usage during training: 900.75390625 MB
Prediction time: 4.612908899784088
Peak memory usage during prediction: 2784.9765625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'brute'} and vectorizer CountVectorizer
Training time: 0.9086353997699916
Peak memory usage during training: 901.77734375 MB
Prediction time: 4.522572800051421
Peak memory usage during prediction: 2888.69140625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'ball_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 0.9171056998893619
Peak memory usage during training: 900.50390625 MB
Prediction time: 4.629144700244069
Peak memory usage during prediction: 2797.3515625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'kd_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 0.911555000115186
Peak memory usage during training: 900.34375 MB
Prediction time: 4.5120008001104
Peak memory usage during prediction: 2920.5390625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'brute'} and vectorizer CountVectorizer
Training time: 0.9055197997950017
Peak memory usage during training: 900.2734375 MB
Prediction time: 4.612522600218654
Peak memory usage during prediction: 2896.28125 MB
----------------------------------------------------------------------------------------------------
Processing model: DecisionTree
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'sqrt'} and vectorizer CountVectorizer
Training time: 2.392086799722165
Peak memory usage during training: 904.81640625 MB
Prediction time: 0.9690902000293136
Peak memory usage during prediction: 892.41015625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'log2'} and vectorizer CountVectorizer
Training time: 3.960443399846554
Peak memory usage during training: 911.640625 MB
Prediction time: 1.4367380002513528
Peak memory usage during prediction: 877.25 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': None} and vectorizer CountVectorizer
Training time: 11.486112700309604
Peak memory usage during training: 912.26171875 MB
Prediction time: 1.4495461997576058
Peak memory usage during prediction: 870.59375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'sqrt'} and vectorizer CountVectorizer
Training time: 2.212182800285518
Peak memory usage during training: 909.12109375 MB
Prediction time: 1.4199979999102652
Peak memory usage during prediction: 873.421875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'log2'} and vectorizer CountVectorizer
Training time: 3.9013958000577986
Peak memory usage during training: 912.05078125 MB
Prediction time: 0.9828928001224995
Peak memory usage during prediction: 876.51171875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': None} and vectorizer CountVectorizer
Training time: 9.012446099892259
Peak memory usage during training: 911.60546875 MB
Prediction time: 0.9856242998503149
Peak memory usage during prediction: 886.51171875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'sqrt'} and vectorizer CountVectorizer
Training time: 2.2056954000145197
Peak memory usage during training: 909.01953125 MB
Prediction time: 1.4165198002010584
Peak memory usage during prediction: 891.9453125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'log2'} and vectorizer CountVectorizer
Training time: 3.9569799001328647
Peak memory usage during training: 911.40625 MB
Prediction time: 1.4558063996955752
Peak memory usage during prediction: 876.55078125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': None} and vectorizer CountVectorizer
Training time: 8.970875099767
Peak memory usage during training: 911.67578125 MB
Prediction time: 1.4190643997862935
Peak memory usage during prediction: 870.48046875 MB
----------------------------------------------------------------------------------------------------
Processing model: GradientBoosting
Training GradientBoosting with params {'n_estimators': 100, 'criterion': 'friedman_mse'} and vectorizer CountVectorizer
Training time: 8.092944600153714
Peak memory usage during training: 910.984375 MB
Prediction time: 1.4512716000899673
Peak memory usage during prediction: 870.78515625 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 100, 'criterion': 'squared_error'} and vectorizer CountVectorizer
Training time: 8.081405700184405
Peak memory usage during training: 910.5234375 MB
Prediction time: 0.9703291999176145
Peak memory usage during prediction: 894.97265625 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 150, 'criterion': 'friedman_mse'} and vectorizer CountVectorizer
Training time: 11.639505200088024
Peak memory usage during training: 910.03515625 MB
Prediction time: 1.4324028003029525
Peak memory usage during prediction: 870.3671875 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 150, 'criterion': 'squared_error'} and vectorizer CountVectorizer
Training time: 11.69655800005421
Peak memory usage during training: 908.96484375 MB
Prediction time: 0.9801228996366262
Peak memory usage during prediction: 870.03515625 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 200, 'criterion': 'friedman_mse'} and vectorizer CountVectorizer
Training time: 15.188732499722391
Peak memory usage during training: 909.4296875 MB
Prediction time: 0.9886854998767376
Peak memory usage during prediction: 870.0859375 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 200, 'criterion': 'squared_error'} and vectorizer CountVectorizer
Training time: 15.145542099606246
Peak memory usage during training: 908.69921875 MB
Prediction time: 0.9796055001206696
Peak memory usage during prediction: 870.14453125 MB
----------------------------------------------------------------------------------------------------
Processing model: AdaBoost
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 0.01} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 5.12234180001542
Peak memory usage during training: 907.14453125 MB
Prediction time: 1.0007110997103155
Peak memory usage during prediction: 870.3515625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 0.1} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 5.164314799942076
Peak memory usage during training: 907.23046875 MB
Prediction time: 1.022225399967283
Peak memory usage during prediction: 870.07421875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 1.0} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 5.150782700162381
Peak memory usage during training: 907.21484375 MB
Prediction time: 1.0101421996951103
Peak memory usage during prediction: 870.0 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 0.01} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 9.478118599858135
Peak memory usage during training: 907.2734375 MB
Prediction time: 1.0519166998565197
Peak memory usage during prediction: 869.8984375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 0.1} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 9.419263700023293
Peak memory usage during training: 907.30859375 MB
Prediction time: 1.0499374996870756
Peak memory usage during prediction: 870.140625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 1.0} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 9.395383400376886
Peak memory usage during training: 907.48046875 MB
Prediction time: 1.0473098000511527
Peak memory usage during prediction: 870.01953125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 0.01} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 13.696085200179368
Peak memory usage during training: 907.48828125 MB
Prediction time: 1.0845778002403677
Peak memory usage during prediction: 869.609375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 0.1} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 13.701396499760449
Peak memory usage during training: 907.31640625 MB
Prediction time: 1.0767108998261392
Peak memory usage during prediction: 869.98046875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 1.0} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 13.696496500167996
Peak memory usage during training: 907.3828125 MB
Prediction time: 1.081095399800688
Peak memory usage during prediction: 869.8125 MB
----------------------------------------------------------------------------------------------------
Processing model: SGD
Training SGD with params {'alpha': 0.0001, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 0.9331530001945794
Peak memory usage during training: 902.12890625 MB
Prediction time: 1.4353960999287665
Peak memory usage during prediction: 869.65625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.0001, 'penalty': 'l1'} and vectorizer CountVectorizer
Training time: 1.0041024000383914
Peak memory usage during training: 902.34375 MB
Prediction time: 1.4309656000696123
Peak memory usage during prediction: 869.6484375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.0001, 'penalty': 'elasticnet'} and vectorizer CountVectorizer
Training time: 0.9785123998299241
Peak memory usage during training: 902.41796875 MB
Prediction time: 0.9702175999991596
Peak memory usage during prediction: 898.0078125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 0.9290330000221729
Peak memory usage during training: 902.43359375 MB
Prediction time: 1.4287654999643564
Peak memory usage during prediction: 869.62109375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'l1'} and vectorizer CountVectorizer
Training time: 0.9699336001649499
Peak memory usage during training: 902.49609375 MB
Prediction time: 0.9746828000061214
Peak memory usage during prediction: 898.0859375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'elasticnet'} and vectorizer CountVectorizer
Training time: 0.9831741000525653
Peak memory usage during training: 902.5 MB
Prediction time: 1.436598100233823
Peak memory usage during prediction: 869.6875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 0.9300754000432789
Peak memory usage during training: 901.89453125 MB
Prediction time: 1.4328316999599338
Peak memory usage during prediction: 869.61328125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'l1'} and vectorizer CountVectorizer
Training time: 0.9469698001630604
Peak memory usage during training: 902.4375 MB
Prediction time: 0.9771670000627637
Peak memory usage during prediction: 898.02734375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'elasticnet'} and vectorizer CountVectorizer
Training time: 0.9646767997182906
Peak memory usage during training: 902.33984375 MB
Prediction time: 1.4256521998904645
Peak memory usage during prediction: 869.5234375 MB
----------------------------------------------------------------------------------------------------
Processing seed: 5
Processing vectorizer: TfidfVectorizer
Processing model: RandomForest
Training RandomForest with params {'n_estimators': 50, 'criterion': 'gini'} and vectorizer TfidfVectorizer
Training time: 49.612844499759376
Peak memory usage during training: 903.99609375 MB
Prediction time: 1.2071446999907494
Peak memory usage during prediction: 617.96875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'entropy'} and vectorizer TfidfVectorizer
Training time: 45.13259950000793
Peak memory usage during training: 628.8671875 MB
Prediction time: 1.2080169999971986
Peak memory usage during prediction: 606.453125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'log_loss'} and vectorizer TfidfVectorizer
Training time: 45.21222620038316
Peak memory usage during training: 617.94921875 MB
Prediction time: 1.1963883000425994
Peak memory usage during prediction: 594.96484375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'gini'} and vectorizer TfidfVectorizer
Training time: 98.23920260043815
Peak memory usage during training: 755.37890625 MB
Prediction time: 0.7154526999220252
Peak memory usage during prediction: 756.13671875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'entropy'} and vectorizer TfidfVectorizer
Training time: 89.29696079995483
Peak memory usage during training: 766.77734375 MB
Prediction time: 0.7209779000841081
Peak memory usage during prediction: 733.4140625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'log_loss'} and vectorizer TfidfVectorizer
Training time: 89.60043649980798
Peak memory usage during training: 741.328125 MB
Prediction time: 0.7199756000190973
Peak memory usage during prediction: 734.453125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'gini'} and vectorizer TfidfVectorizer
Training time: 147.21981720020995
Peak memory usage during training: 886.1484375 MB
Prediction time: 0.8318316000513732
Peak memory usage during prediction: 884.37109375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'entropy'} and vectorizer TfidfVectorizer
Training time: 134.10818749992177
Peak memory usage during training: 900.80859375 MB
Prediction time: 0.837610200047493
Peak memory usage during prediction: 848.84375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'log_loss'} and vectorizer TfidfVectorizer
Training time: 134.25200759992003
Peak memory usage during training: 856.57421875 MB
Prediction time: 0.8373067998327315
Peak memory usage during prediction: 855.02734375 MB
----------------------------------------------------------------------------------------------------
Processing model: SVC
Training SVC with params {'C': 0.1, 'kernel': 'linear'} and vectorizer TfidfVectorizer
Training time: 138.62896130001172
Peak memory usage during training: 1109.23828125 MB
Prediction time: 4.960975100286305
Peak memory usage during prediction: 875.7265625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 0.1, 'kernel': 'rbf'} and vectorizer TfidfVectorizer
Training time: 207.3331963000819
Peak memory usage during training: 1111.6328125 MB
Prediction time: 9.301377600058913
Peak memory usage during prediction: 879.046875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 0.1, 'kernel': 'sigmoid'} and vectorizer TfidfVectorizer
Training time: 148.75901979999617
Peak memory usage during training: 1096.55859375 MB
Prediction time: 5.185584000311792
Peak memory usage during prediction: 876.328125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'linear'} and vectorizer TfidfVectorizer
Training time: 148.6229877001606
Peak memory usage during training: 1175.35546875 MB
Prediction time: 2.543116199783981
Peak memory usage during prediction: 871.08203125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'rbf'} and vectorizer TfidfVectorizer
Training time: 326.16869849991053
Peak memory usage during training: 1139.2734375 MB
Prediction time: 5.901632799766958
Peak memory usage during prediction: 870.5859375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'sigmoid'} and vectorizer TfidfVectorizer
Training time: 234.91850779997185
Peak memory usage during training: 1130.1171875 MB
Prediction time: 2.4288895996287465
Peak memory usage during prediction: 864.25 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'linear'} and vectorizer TfidfVectorizer
Training time: 163.67627319972962
Peak memory usage during training: 1226.40234375 MB
Prediction time: 1.7181904003955424
Peak memory usage during prediction: 862.3828125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'rbf'} and vectorizer TfidfVectorizer
Training time: 454.8237316003069
Peak memory usage during training: 1124.34375 MB
Prediction time: 5.939627499785274
Peak memory usage during prediction: 866.9765625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'sigmoid'} and vectorizer TfidfVectorizer
Training time: 545.8322480996139
Peak memory usage during training: 1140.8359375 MB
Prediction time: 1.3398278998211026
Peak memory usage during prediction: 862.80078125 MB
----------------------------------------------------------------------------------------------------
Processing model: MultinomialNB
Training MultinomialNB with params {'alpha': 0.01} and vectorizer TfidfVectorizer
Training time: 0.961871899664402
Peak memory usage during training: 860.41796875 MB
Prediction time: 1.4197710999287665
Peak memory usage during prediction: 832.6328125 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'alpha': 0.1} and vectorizer TfidfVectorizer
Training time: 0.960011400282383
Peak memory usage during training: 858.91796875 MB
Prediction time: 0.970650099683553
Peak memory usage during prediction: 859.07421875 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'alpha': 1.0} and vectorizer TfidfVectorizer
Training time: 0.9759047999978065
Peak memory usage during training: 858.7734375 MB
Prediction time: 1.4342767000198364
Peak memory usage during prediction: 831.28125 MB
----------------------------------------------------------------------------------------------------
Processing model: LogisticRegression
Training LogisticRegression with params {'C': 0.1, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 0.9971984000876546
Peak memory usage during training: 856.88671875 MB
Prediction time: 0.9671910996548831
Peak memory usage during prediction: 830.58984375 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'C': 1, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.0121335997246206
Peak memory usage during training: 858.87109375 MB
Prediction time: 0.9803324001841247
Peak memory usage during prediction: 829.93359375 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'C': 10, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 1.0180684998631477
Peak memory usage during training: 856.26171875 MB
Prediction time: 1.4263256001286209
Peak memory usage during prediction: 829.6875 MB
----------------------------------------------------------------------------------------------------
Processing model: KNeighbors
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'ball_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 0.9045508000999689
Peak memory usage during training: 858.21875 MB
Prediction time: 4.325039699673653
Peak memory usage during prediction: 2852.26953125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'kd_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 0.9111334001645446
Peak memory usage during training: 857.90625 MB
Prediction time: 4.294342200271785
Peak memory usage during prediction: 2810.6875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'brute'} and vectorizer TfidfVectorizer
Training time: 0.9203881002031267
Peak memory usage during training: 857.58203125 MB
Prediction time: 4.372627600096166
Peak memory usage during prediction: 2840.15625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'ball_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 1.0445170998573303
Peak memory usage during training: 857.375 MB
Prediction time: 4.305153000168502
Peak memory usage during prediction: 2839.0 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'kd_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 0.9047757000662386
Peak memory usage during training: 855.15625 MB
Prediction time: 4.328150500077754
Peak memory usage during prediction: 2812.67578125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'brute'} and vectorizer TfidfVectorizer
Training time: 0.9172972999513149
Peak memory usage during training: 857.75 MB
Prediction time: 4.432057499885559
Peak memory usage during prediction: 2854.7734375 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'ball_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 0.9114664001390338
Peak memory usage during training: 857.42578125 MB
Prediction time: 4.350685399957001
Peak memory usage during prediction: 2864.38671875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'kd_tree'} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 0.9139459999278188
Peak memory usage during training: 857.79296875 MB
Prediction time: 4.320077999960631
Peak memory usage during prediction: 2859.94921875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'brute'} and vectorizer TfidfVectorizer
Training time: 0.9074566001072526
Peak memory usage during training: 857.41796875 MB
Prediction time: 4.425591100007296
Peak memory usage during prediction: 2832.140625 MB
----------------------------------------------------------------------------------------------------
Processing model: DecisionTree
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'sqrt'} and vectorizer TfidfVectorizer
Training time: 2.2669456996954978
Peak memory usage during training: 859.91796875 MB
Prediction time: 0.9704534001648426
Peak memory usage during prediction: 851.4296875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'log2'} and vectorizer TfidfVectorizer
Training time: 3.0468679000623524
Peak memory usage during training: 863.91796875 MB
Prediction time: 1.4491236000321805
Peak memory usage during prediction: 835.640625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': None} and vectorizer TfidfVectorizer
Training time: 18.416674400214106
Peak memory usage during training: 867.53515625 MB
Prediction time: 0.9824007996357977
Peak memory usage during prediction: 844.86328125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'sqrt'} and vectorizer TfidfVectorizer
Training time: 2.1705526001751423
Peak memory usage during training: 859.73828125 MB
Prediction time: 0.9695858997292817
Peak memory usage during prediction: 851.44921875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'log2'} and vectorizer TfidfVectorizer
Training time: 2.9554221997968853
Peak memory usage during training: 864.26171875 MB
Prediction time: 0.9939410001970828
Peak memory usage during prediction: 856.6953125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': None} and vectorizer TfidfVectorizer
Training time: 15.61817350005731
Peak memory usage during training: 867.41015625 MB
Prediction time: 0.9852641997858882
Peak memory usage during prediction: 845.59375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'sqrt'} and vectorizer TfidfVectorizer
Training time: 2.168576099909842
Peak memory usage during training: 864.7421875 MB
Prediction time: 1.4347816002555192
Peak memory usage during prediction: 832.54296875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'log2'} and vectorizer TfidfVectorizer
Training time: 2.9609043998643756
Peak memory usage during training: 864.28515625 MB
Prediction time: 1.4418783001601696
Peak memory usage during prediction: 835.390625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': None} and vectorizer TfidfVectorizer
Training time: 15.668275500182062
Peak memory usage during training: 866.2578125 MB
Prediction time: 0.9815743998624384
Peak memory usage during prediction: 845.05859375 MB
----------------------------------------------------------------------------------------------------
Processing model: GradientBoosting
Training GradientBoosting with params {'n_estimators': 100, 'criterion': 'friedman_mse'} and vectorizer TfidfVectorizer
Training time: 19.082173000089824
Peak memory usage during training: 863.2578125 MB
Prediction time: 1.4481192003004253
Peak memory usage during prediction: 829.6484375 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 100, 'criterion': 'squared_error'} and vectorizer TfidfVectorizer
Training time: 19.015985599718988
Peak memory usage during training: 863.1328125 MB
Prediction time: 0.9804332996718585
Peak memory usage during prediction: 854.18359375 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 150, 'criterion': 'friedman_mse'} and vectorizer TfidfVectorizer
Training time: 27.76632050005719
Peak memory usage during training: 863.44140625 MB
Prediction time: 1.4455901999026537
Peak memory usage during prediction: 829.98046875 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 150, 'criterion': 'squared_error'} and vectorizer TfidfVectorizer
Training time: 27.98776359995827
Peak memory usage during training: 863.2421875 MB
Prediction time: 1.4503946998156607
Peak memory usage during prediction: 829.65625 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 200, 'criterion': 'friedman_mse'} and vectorizer TfidfVectorizer
Training time: 36.785888199694455
Peak memory usage during training: 863.5390625 MB
Prediction time: 0.9826275003142655
Peak memory usage during prediction: 829.2578125 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 200, 'criterion': 'squared_error'} and vectorizer TfidfVectorizer
Training time: 36.98373429989442
Peak memory usage during training: 863.1171875 MB
Prediction time: 1.4611466000787914
Peak memory usage during prediction: 829.5390625 MB
----------------------------------------------------------------------------------------------------
Processing model: AdaBoost
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 0.01} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 7.2869645999744534
Peak memory usage during training: 862.390625 MB
Prediction time: 1.0132710998877883
Peak memory usage during prediction: 829.4453125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 0.1} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 7.2751356000080705
Peak memory usage during training: 862.03125 MB
Prediction time: 1.0156164998188615
Peak memory usage during prediction: 829.328125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 1.0} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 7.263112099841237
Peak memory usage during training: 862.25390625 MB
Prediction time: 1.0028558997437358
Peak memory usage during prediction: 829.296875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 0.01} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 13.680374699644744
Peak memory usage during training: 861.90625 MB
Prediction time: 1.049111899919808
Peak memory usage during prediction: 829.34375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 0.1} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 13.710747200064361
Peak memory usage during training: 862.203125 MB
Prediction time: 1.0505488999187946
Peak memory usage during prediction: 829.34765625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 1.0} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 13.703530800063163
Peak memory usage during training: 862.11328125 MB
Prediction time: 1.047466800082475
Peak memory usage during prediction: 829.09375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 0.01} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 20.086989200208336
Peak memory usage during training: 862.421875 MB
Prediction time: 1.0751794003881514
Peak memory usage during prediction: 846.71875 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 0.1} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 20.058479100000113
Peak memory usage during training: 862.09375 MB
Prediction time: 1.08152320003137
Peak memory usage during prediction: 853.58203125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 1.0} and vectorizer TfidfVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 20.076332199852914
Peak memory usage during training: 862.41796875 MB
Prediction time: 1.093289100099355
Peak memory usage during prediction: 852.2421875 MB
----------------------------------------------------------------------------------------------------
Processing model: SGD
Training SGD with params {'alpha': 0.0001, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 0.9258333002217114
Peak memory usage during training: 859.5078125 MB
Prediction time: 1.4283237997442484
Peak memory usage during prediction: 828.68359375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.0001, 'penalty': 'l1'} and vectorizer TfidfVectorizer
Training time: 0.9574159001931548
Peak memory usage during training: 859.7109375 MB
Prediction time: 0.9758668998256326
Peak memory usage during prediction: 851.015625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.0001, 'penalty': 'elasticnet'} and vectorizer TfidfVectorizer
Training time: 0.9739453000947833
Peak memory usage during training: 859.67578125 MB
Prediction time: 0.968885499984026
Peak memory usage during prediction: 850.8515625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 0.939124200027436
Peak memory usage during training: 859.86328125 MB
Prediction time: 1.4281013999134302
Peak memory usage during prediction: 828.859375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'l1'} and vectorizer TfidfVectorizer
Training time: 0.9696955000981688
Peak memory usage during training: 859.58984375 MB
Prediction time: 1.4329770002514124
Peak memory usage during prediction: 828.828125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'elasticnet'} and vectorizer TfidfVectorizer
Training time: 0.9716175999492407
Peak memory usage during training: 859.859375 MB
Prediction time: 0.9743391000665724
Peak memory usage during prediction: 851.0390625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'l2'} and vectorizer TfidfVectorizer
Training time: 0.9228223999962211
Peak memory usage during training: 859.56640625 MB
Prediction time: 1.4187051998451352
Peak memory usage during prediction: 828.61328125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'l1'} and vectorizer TfidfVectorizer
Training time: 0.9432662003673613
Peak memory usage during training: 859.7109375 MB
Prediction time: 0.9737352998927236
Peak memory usage during prediction: 850.890625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'elasticnet'} and vectorizer TfidfVectorizer
Training time: 0.9364216001704335
Peak memory usage during training: 859.51953125 MB
Prediction time: 0.9607382998801768
Peak memory usage during prediction: 850.6953125 MB
----------------------------------------------------------------------------------------------------
Processing vectorizer: CountVectorizer
Processing model: RandomForest
Training RandomForest with params {'n_estimators': 50, 'criterion': 'gini'} and vectorizer CountVectorizer
Training time: 54.99898920021951
Peak memory usage during training: 860.50390625 MB
Prediction time: 1.2049191002734005
Peak memory usage during prediction: 631.1484375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'entropy'} and vectorizer CountVectorizer
Training time: 50.36767410021275
Peak memory usage during training: 642.41015625 MB
Prediction time: 1.1894922000356019
Peak memory usage during prediction: 622.37890625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 50, 'criterion': 'log_loss'} and vectorizer CountVectorizer
Training time: 50.49368850002065
Peak memory usage during training: 632.6484375 MB
Prediction time: 1.1944423001259565
Peak memory usage during prediction: 622.50390625 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'gini'} and vectorizer CountVectorizer
Training time: 108.56440139980987
Peak memory usage during training: 779.73046875 MB
Prediction time: 0.713077099993825
Peak memory usage during prediction: 778.3203125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'entropy'} and vectorizer CountVectorizer
Training time: 99.75928679993376
Peak memory usage during training: 791.9765625 MB
Prediction time: 0.7100331000983715
Peak memory usage during prediction: 763.36328125 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 100, 'criterion': 'log_loss'} and vectorizer CountVectorizer
Training time: 99.74699959997088
Peak memory usage during training: 776.1875 MB
Prediction time: 0.720620000269264
Peak memory usage during prediction: 766.796875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'gini'} and vectorizer CountVectorizer
Training time: 162.59334550006315
Peak memory usage during training: 917.0390625 MB
Prediction time: 0.8239783002063632
Peak memory usage during prediction: 915.1875 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'entropy'} and vectorizer CountVectorizer
Training time: 149.36286399979144
Peak memory usage during training: 930.46484375 MB
Prediction time: 0.8320247000083327
Peak memory usage during prediction: 878.859375 MB
----------------------------------------------------------------------------------------------------
Training RandomForest with params {'n_estimators': 150, 'criterion': 'log_loss'} and vectorizer CountVectorizer
Training time: 149.508969000075
Peak memory usage during training: 911.1875 MB
Prediction time: 0.8321448001079261
Peak memory usage during prediction: 878.93359375 MB
----------------------------------------------------------------------------------------------------
Processing model: SVC
Training SVC with params {'C': 0.1, 'kernel': 'linear'} and vectorizer CountVectorizer
Training time: 109.22469010017812
Peak memory usage during training: 1183.265625 MB
Prediction time: 2.446148300077766
Peak memory usage during prediction: 916.703125 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 0.1, 'kernel': 'rbf'} and vectorizer CountVectorizer
Training time: 213.79777059983462
Peak memory usage during training: 1149.21875 MB
Prediction time: 9.305658900178969
Peak memory usage during prediction: 927.59375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 0.1, 'kernel': 'sigmoid'} and vectorizer CountVectorizer
Training time: 131.12272229976952
Peak memory usage during training: 1148.625 MB
Prediction time: 4.78506000014022
Peak memory usage during prediction: 922.66796875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'linear'} and vectorizer CountVectorizer
Training time: 124.35492900013924
Peak memory usage during training: 1241.7109375 MB
Prediction time: 1.5212254002690315
Peak memory usage during prediction: 908.18359375 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'rbf'} and vectorizer CountVectorizer
Training time: 341.91346259973943
Peak memory usage during training: 1201.30859375 MB
Prediction time: 6.446537199895829
Peak memory usage during prediction: 915.796875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 1, 'kernel': 'sigmoid'} and vectorizer CountVectorizer
Training time: 113.88800069969147
Peak memory usage during training: 1155.5859375 MB
Prediction time: 2.2526493999175727
Peak memory usage during prediction: 909.78515625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'linear'} and vectorizer CountVectorizer
Training time: 116.8424243000336
Peak memory usage during training: 1252.18359375 MB
Prediction time: 1.246656599920243
Peak memory usage during prediction: 908.48046875 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'rbf'} and vectorizer CountVectorizer
Training time: 389.59550980012864
Peak memory usage during training: 1155.36328125 MB
Prediction time: 6.1071561998687685
Peak memory usage during prediction: 914.7265625 MB
----------------------------------------------------------------------------------------------------
Training SVC with params {'C': 10, 'kernel': 'sigmoid'} and vectorizer CountVectorizer
Training time: 87.66340020019561
Peak memory usage during training: 1151.51171875 MB
Prediction time: 1.4158550999127328
Peak memory usage during prediction: 910.375 MB
----------------------------------------------------------------------------------------------------
Processing model: MultinomialNB
Training MultinomialNB with params {'alpha': 0.01} and vectorizer CountVectorizer
Training time: 0.9696619999594986
Peak memory usage during training: 910.85546875 MB
Prediction time: 1.430809899698943
Peak memory usage during prediction: 874.05078125 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'alpha': 0.1} and vectorizer CountVectorizer
Training time: 0.9654798000119627
Peak memory usage during training: 910.625 MB
Prediction time: 1.421868400182575
Peak memory usage during prediction: 873.26953125 MB
----------------------------------------------------------------------------------------------------
Training MultinomialNB with params {'alpha': 1.0} and vectorizer CountVectorizer
Training time: 0.9580701999366283
Peak memory usage during training: 910.3359375 MB
Prediction time: 1.4175867000594735
Peak memory usage during prediction: 873.10546875 MB
----------------------------------------------------------------------------------------------------
Processing model: LogisticRegression
Training LogisticRegression with params {'C': 0.1, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.0469243000261486
Peak memory usage during training: 913.61328125 MB
Prediction time: 1.4381210999563336
Peak memory usage during prediction: 872.203125 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'C': 1, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.0795637001283467
Peak memory usage during training: 913.51171875 MB
Prediction time: 1.8713248996064067
Peak memory usage during prediction: 872.30859375 MB
----------------------------------------------------------------------------------------------------
Training LogisticRegression with params {'C': 10, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 1.0959829003550112
Peak memory usage during training: 913.25390625 MB
Prediction time: 1.4248681999742985
Peak memory usage during prediction: 872.08984375 MB
----------------------------------------------------------------------------------------------------
Processing model: KNeighbors
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'ball_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 0.8972047003917396
Peak memory usage during training: 910.5546875 MB
Prediction time: 4.514770099893212
Peak memory usage during prediction: 2914.1796875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'kd_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 0.9022675999440253
Peak memory usage during training: 903.0078125 MB
Prediction time: 4.617900300305337
Peak memory usage during prediction: 2887.3671875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 3, 'algorithm': 'brute'} and vectorizer CountVectorizer
Training time: 0.902397199999541
Peak memory usage during training: 902.94140625 MB
Prediction time: 4.503780199680477
Peak memory usage during prediction: 2904.35546875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'ball_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 0.8995031998492777
Peak memory usage during training: 902.7578125 MB
Prediction time: 4.621327000204474
Peak memory usage during prediction: 2890.05078125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'kd_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 0.9031003001146019
Peak memory usage during training: 901.234375 MB
Prediction time: 4.511790500022471
Peak memory usage during prediction: 2862.83203125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 5, 'algorithm': 'brute'} and vectorizer CountVectorizer
Training time: 0.9062246000394225
Peak memory usage during training: 899.58984375 MB
Prediction time: 4.626320700161159
Peak memory usage during prediction: 2921.40625 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'ball_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 0.9093288001604378
Peak memory usage during training: 902.34765625 MB
Prediction time: 4.530475600156933
Peak memory usage during prediction: 2887.16796875 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'kd_tree'} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\neighbors\_base.py:583: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

Training time: 0.9035378997214139
Peak memory usage during training: 902.7734375 MB
Prediction time: 4.625179400201887
Peak memory usage during prediction: 2855.7578125 MB
----------------------------------------------------------------------------------------------------
Training KNeighbors with params {'n_neighbors': 7, 'algorithm': 'brute'} and vectorizer CountVectorizer
Training time: 0.8995270999148488
Peak memory usage during training: 902.13671875 MB
Prediction time: 4.524752099998295
Peak memory usage during prediction: 2862.9609375 MB
----------------------------------------------------------------------------------------------------
Processing model: DecisionTree
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'sqrt'} and vectorizer CountVectorizer
Training time: 2.410177200101316
Peak memory usage during training: 904.4296875 MB
Prediction time: 1.4345823000185192
Peak memory usage during prediction: 875.0859375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': 'log2'} and vectorizer CountVectorizer
Training time: 3.9560405001975596
Peak memory usage during training: 913.65625 MB
Prediction time: 1.4474893999285996
Peak memory usage during prediction: 878.0546875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'gini', 'max_features': None} and vectorizer CountVectorizer
Training time: 11.466765299905092
Peak memory usage during training: 918.19140625 MB
Prediction time: 0.9785446999594569
Peak memory usage during prediction: 887.796875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'sqrt'} and vectorizer CountVectorizer
Training time: 2.32403580006212
Peak memory usage during training: 909.484375 MB
Prediction time: 0.9854280999861658
Peak memory usage during prediction: 893.4140625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': 'log2'} and vectorizer CountVectorizer
Training time: 3.843272300437093
Peak memory usage during training: 913.76171875 MB
Prediction time: 0.9820795999839902
Peak memory usage during prediction: 877.60546875 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'entropy', 'max_features': None} and vectorizer CountVectorizer
Training time: 9.020354500040412
Peak memory usage during training: 913.66015625 MB
Prediction time: 1.435711800120771
Peak memory usage during prediction: 871.52734375 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'sqrt'} and vectorizer CountVectorizer
Training time: 2.318343000020832
Peak memory usage during training: 909.24609375 MB
Prediction time: 0.9575696000829339
Peak memory usage during prediction: 893.203125 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': 'log2'} and vectorizer CountVectorizer
Training time: 3.881683399900794
Peak memory usage during training: 913.1875 MB
Prediction time: 0.9744847002439201
Peak memory usage during prediction: 877.5625 MB
----------------------------------------------------------------------------------------------------
Training DecisionTree with params {'criterion': 'log_loss', 'max_features': None} and vectorizer CountVectorizer
Training time: 9.007033499889076
Peak memory usage during training: 913.23828125 MB
Prediction time: 1.4427096000872552
Peak memory usage during prediction: 871.30078125 MB
----------------------------------------------------------------------------------------------------
Processing model: GradientBoosting
Training GradientBoosting with params {'n_estimators': 100, 'criterion': 'friedman_mse'} and vectorizer CountVectorizer
Training time: 8.097448500338942
Peak memory usage during training: 911.80078125 MB
Prediction time: 0.9769351999275386
Peak memory usage during prediction: 896.03125 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 100, 'criterion': 'squared_error'} and vectorizer CountVectorizer
Training time: 8.066576099954545
Peak memory usage during training: 911.83203125 MB
Prediction time: 1.4420075002126396
Peak memory usage during prediction: 871.578125 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 150, 'criterion': 'friedman_mse'} and vectorizer CountVectorizer
Training time: 11.66125850006938
Peak memory usage during training: 911.63671875 MB
Prediction time: 1.4499908997677267
Peak memory usage during prediction: 871.60546875 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 150, 'criterion': 'squared_error'} and vectorizer CountVectorizer
Training time: 11.643697199877352
Peak memory usage during training: 911.31640625 MB
Prediction time: 1.4585366998799145
Peak memory usage during prediction: 871.48046875 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 200, 'criterion': 'friedman_mse'} and vectorizer CountVectorizer
Training time: 15.17210640013218
Peak memory usage during training: 911.16796875 MB
Prediction time: 1.4471720000728965
Peak memory usage during prediction: 871.49609375 MB
----------------------------------------------------------------------------------------------------
Training GradientBoosting with params {'n_estimators': 200, 'criterion': 'squared_error'} and vectorizer CountVectorizer
Training time: 15.328010399825871
Peak memory usage during training: 911.234375 MB
Prediction time: 1.459612200036645
Peak memory usage during prediction: 871.47265625 MB
----------------------------------------------------------------------------------------------------
Processing model: AdaBoost
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 0.01} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 5.159617600031197
Peak memory usage during training: 909.4921875 MB
Prediction time: 1.0299518997780979
Peak memory usage during prediction: 871.734375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 0.1} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 5.139508199878037
Peak memory usage during training: 909.37890625 MB
Prediction time: 1.0041907001286745
Peak memory usage during prediction: 871.53515625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 50, 'learning_rate': 1.0} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 5.141971900127828
Peak memory usage during training: 909.4765625 MB
Prediction time: 1.0040319999679923
Peak memory usage during prediction: 871.515625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 0.01} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 9.416510100010782
Peak memory usage during training: 909.6640625 MB
Prediction time: 1.044613900128752
Peak memory usage during prediction: 871.55859375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 0.1} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 9.404312000144273
Peak memory usage during training: 909.55859375 MB
Prediction time: 1.040228699799627
Peak memory usage during prediction: 871.8515625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 100, 'learning_rate': 1.0} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 9.423176699783653
Peak memory usage during training: 909.89453125 MB
Prediction time: 1.0416542002931237
Peak memory usage during prediction: 871.578125 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 0.01} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 13.715483100153506
Peak memory usage during training: 909.90234375 MB
Prediction time: 1.0847824001684785
Peak memory usage during prediction: 871.65625 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 0.1} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 13.693845000118017
Peak memory usage during training: 909.578125 MB
Prediction time: 1.0805531996302307
Peak memory usage during prediction: 871.43359375 MB
----------------------------------------------------------------------------------------------------
Training AdaBoost with params {'n_estimators': 150, 'learning_rate': 1.0} and vectorizer CountVectorizer

c:\Users\Rafael\Desktop\Prog\TCC\venv\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Training time: 13.706735200248659
Peak memory usage during training: 909.96875 MB
Prediction time: 1.0705761001445353
Peak memory usage during prediction: 871.40625 MB
----------------------------------------------------------------------------------------------------
Processing model: SGD
Training SGD with params {'alpha': 0.0001, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 0.9397352999076247
Peak memory usage during training: 906.59375 MB
Prediction time: 0.9749640999361873
Peak memory usage during prediction: 902.17578125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.0001, 'penalty': 'l1'} and vectorizer CountVectorizer
Training time: 1.0067627998068929
Peak memory usage during training: 906.53125 MB
Prediction time: 1.4403043002821505
Peak memory usage during prediction: 871.54296875 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.0001, 'penalty': 'elasticnet'} and vectorizer CountVectorizer
Training time: 0.987637700047344
Peak memory usage during training: 906.53515625 MB
Prediction time: 1.4249089998193085
Peak memory usage during prediction: 871.4375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 0.932423799764365
Peak memory usage during training: 906.53515625 MB
Prediction time: 1.869306799955666
Peak memory usage during prediction: 871.37109375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'l1'} and vectorizer CountVectorizer
Training time: 0.9704129002057016
Peak memory usage during training: 906.46484375 MB
Prediction time: 1.894195199944079
Peak memory usage during prediction: 871.375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.001, 'penalty': 'elasticnet'} and vectorizer CountVectorizer
Training time: 0.9701223000884056
Peak memory usage during training: 906.53125 MB
Prediction time: 1.4238800997845829
Peak memory usage during prediction: 871.5390625 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'l2'} and vectorizer CountVectorizer
Training time: 0.9253691998310387
Peak memory usage during training: 906.53125 MB
Prediction time: 1.421469499822706
Peak memory usage during prediction: 871.359375 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'l1'} and vectorizer CountVectorizer
Training time: 0.9762605000287294
Peak memory usage during training: 906.46484375 MB
Prediction time: 0.9737664996646345
Peak memory usage during prediction: 902.05078125 MB
----------------------------------------------------------------------------------------------------
Training SGD with params {'alpha': 0.01, 'penalty': 'elasticnet'} and vectorizer CountVectorizer
Training time: 0.9597709001973271
Peak memory usage during training: 906.2890625 MB
Prediction time: 1.4277238002978265
Peak memory usage during prediction: 871.22265625 MB
----------------------------------------------------------------------------------------------------

# Process results

In [9]:
results.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 396 entries, 0 to 395
Data columns (total 15 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   seed                        396 non-null    object
 1   vectorizer                  396 non-null    object
 2   model                       396 non-null    object
 3   params                      396 non-null    object
 4   accuracy                    396 non-null    float64
 5   training_time               396 non-null    float64
 6   prediction_time             396 non-null    float64
 7   peak_memory_train           396 non-null    float64
 8   peak_memory_prediction      396 non-null    float64
 9   precision_class_democratic  396 non-null    float64
 10  recall_class_democratic     396 non-null    float64
 11  f1_class_democratic         396 non-null    float64
 12  precision_class_republican  396 non-null    float64
 13  recall_class_republican     396 non-null    float64
 14  f1_class_republican         396 non-null    float64
dtypes: float64(11), object(4)
memory usage: 46.5+ KB

In [10]:
results.head()

,seed,vectorizer,model,params,accuracy,training_time,prediction_time,peak_memory_train,peak_memory_prediction,precision_class_democratic,recall_class_democratic,f1_class_democratic,precision_class_republican,recall_class_republican,f1_class_republican
0,2,TfidfVectorizer,RandomForest,"{'n_estimators': 50, 'criterion': 'gini'}",0.94300,49.923073,1.210692,608.898438,603.574219,0.951120,0.9340,0.942482,0.935167,0.9520,0.943508
1,2,TfidfVectorizer,RandomForest,"{'n_estimators': 50, 'criterion': 'entropy'}",0.94275,45.519096,1.189076,610.558594,581.609375,0.953405,0.9310,0.942069,0.932584,0.9545,0.943415
2,2,TfidfVectorizer,RandomForest,"{'n_estimators': 50, 'criterion': 'log_loss'}",0.94275,45.980572,1.211146,605.835938,581.398438,0.953405,0.9310,0.942069,0.932584,0.9545,0.943415
3,2,TfidfVectorizer,RandomForest,"{'n_estimators': 100, 'criterion': 'gini'}",0.94225,99.168593,0.730074,745.375000,745.675781,0.954289,0.9290,0.941475,0.930833,0.9555,0.943005
4,2,TfidfVectorizer,RandomForest,"{'n_estimators': 100, 'criterion': 'entropy'}",0.94650,90.635450,0.722163,751.750000,721.429688,0.961260,0.9305,0.945630,0.932655,0.9625,0.947343

In [11]:
results['params'] = results['params'].astype(str)
results_avg_seed = results.groupby(['model', 'vectorizer', 'params']).mean().reset_index()
results_avg_seed['f1_avg'] = results_avg_seed[[col for col in results_avg_seed.columns if 'f1_class' in col]].mean(axis=1)
results_avg_seed

,model,vectorizer,params,seed,accuracy,training_time,prediction_time,peak_memory_train,peak_memory_prediction,precision_class_democratic,recall_class_democratic,f1_class_democratic,precision_class_republican,recall_class_republican,f1_class_republican,f1_avg
0,AdaBoost,CountVectorizer,"{'n_estimators': 100, 'learning_rate': 0.01}",3.333333,0.61200,9.442402,1.047595,907.980469,871.428385,0.962810,0.2330,0.375201,0.563709,0.9910,0.718637,0.546919
1,AdaBoost,CountVectorizer,"{'n_estimators': 100, 'learning_rate': 0.1}",3.333333,0.72525,9.409267,1.045796,908.072917,871.589844,0.952764,0.4740,0.633055,0.649917,0.9765,0.780420,0.706737
2,AdaBoost,CountVectorizer,"{'n_estimators': 100, 'learning_rate': 1.0}",3.333333,0.82325,9.404816,1.042994,908.135417,871.440104,0.966787,0.6695,0.791137,0.747228,0.9770,0.846804,0.818971
3,AdaBoost,CountVectorizer,"{'n_estimators': 150, 'learning_rate': 0.01}",3.333333,0.63350,13.751020,1.083501,908.225260,871.329427,0.968421,0.2760,0.429572,0.577843,0.9910,0.730018,0.579795
4,AdaBoost,CountVectorizer,"{'n_estimators': 150, 'learning_rate': 0.1}",3.333333,0.75575,13.692523,1.077666,907.938802,871.298177,0.962060,0.5325,0.685549,0.676806,0.9790,0.800327,0.742938
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
127,SVC,TfidfVectorizer,"{'C': 1, 'kernel': 'rbf'}",3.333333,0.96050,326.041834,5.910294,1137.243490,866.954427,0.970859,0.9495,0.960061,0.950587,0.9715,0.960930,0.960495
128,SVC,TfidfVectorizer,"{'C': 1, 'kernel': 'sigmoid'}",3.333333,0.95750,234.855735,2.452000,1125.575521,860.997396,0.971649,0.9425,0.956853,0.944175,0.9725,0.958128,0.957490
129,SVC,TfidfVectorizer,"{'C': 10, 'kernel': 'linear'}",3.333333,0.95575,163.741871,1.728122,1221.123698,858.875000,0.975483,0.9350,0.954812,0.937590,0.9765,0.956650,0.955731
130,SVC,TfidfVectorizer,"{'C': 10, 'kernel': 'rbf'}",3.333333,0.96025,454.242138,5.939008,1118.397135,863.945312,0.973752,0.9460,0.959675,0.947496,0.9745,0.960808,0.960242
131,SVC,TfidfVectorizer,"{'C': 10, 'kernel': 'sigmoid'}",3.333333,0.94925,546.503018,1.344472,1139.347656,859.274740,0.964822,0.9325,0.948385,0.934688,0.9660,0.950086,0.949236

In [12]:
best_result = results_avg_seed.loc[results_avg_seed['f1_avg'].idxmax()]

best_model = models[best_result['model']]['model']
best_params = eval(best_result['params'])
best_model.set_params(**best_params)

best_result_vectorizer = eval(best_result['vectorizer'])()

pipeline = Pipeline([
    ('vectorizer', best_result_vectorizer),
    ('model', best_model)
])

pipeline.fit(train['text'], train['label'])
y_pred = pipeline.predict(test['text'])

accuracy = accuracy_score(test['label'], y_pred)
precisions, recalls, f1s, supports = precision_recall_fscore_support(test['label'], y_pred, average=None, labels=classes, zero_division=0)

print(f"Best model: {best_result['model']}")
print(f"Best model params: {best_result['params']}")
print(f"Best vectorizer: {best_result['vectorizer']}")
print(f"Best accuracy: {accuracy}\n")

for i, c in enumerate(classes):
    print(f"Class {c}")
    print(f"Precision: {precisions[i]}")
    print(f"Recall: {recalls[i]}")
    print(f"F1: {f1s[i]}")
    print(f"Support: {supports[i]}\n")

Best model: MultinomialNB
Best model params: {'alpha': 1.0}
Best vectorizer: CountVectorizer
Best accuracy: 0.9593035714285715

Class democratic
Precision: 0.9678416821273964
Recall: 0.9501785714285714
F1: 0.9589287966984448
Support: 28000

Class republican
Precision: 0.9510715162568834
Recall: 0.9684285714285714
F1: 0.9596715683672206
Support: 28000

In [13]:
with open('models/best_model_sklearn_binary3.pkl', 'wb') as f:
    pickle.dump(pipeline, f)